# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MINH\OneDrive\문서\GitHub\quanlydo-giadung\quan-ly-dai-ly-kinh-doanh-do-gia-dung-main\ui\attendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Attendance(object):
    def setupUi(self, Attendance):
        Attendance.setObjectName("Attendance")
        Attendance.resize(1200, 800)
        Attendance.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 10px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnSaveAttendance {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnCheckIn {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnCheckOut {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExportAttendance {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QComboBox, QDateEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblCheckInTime, QLabel#lblCheckOutTime {\n"
"        font-size: 24px;\n"
"        font-weight: bold;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(Attendance)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(Attendance)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.lblEmployee = QtWidgets.QLabel(Attendance)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEmployee.setFont(font)
        self.lblEmployee.setObjectName("lblEmployee")
        self.controlLayout.addWidget(self.lblEmployee)
        self.cboEmployee = QtWidgets.QComboBox(Attendance)
        self.cboEmployee.setMinimumSize(QtCore.QSize(250, 0))
        self.cboEmployee.setObjectName("cboEmployee")
        self.controlLayout.addWidget(self.cboEmployee)
        self.lblMonth = QtWidgets.QLabel(Attendance)
        self.lblMonth.setObjectName("lblMonth")
        self.controlLayout.addWidget(self.lblMonth)
        self.dateMonth = QtWidgets.QDateEdit(Attendance)
        self.dateMonth.setCalendarPopup(True)
        self.dateMonth.setDate(QtCore.QDate(2026, 4, 1))
        self.dateMonth.setObjectName("dateMonth")
        self.controlLayout.addWidget(self.dateMonth)
        self.btnLoadAttendance = QtWidgets.QPushButton(Attendance)
        self.btnLoadAttendance.setObjectName("btnLoadAttendance")
        self.controlLayout.addWidget(self.btnLoadAttendance)
        self.btnSaveAttendance = QtWidgets.QPushButton(Attendance)
        self.btnSaveAttendance.setObjectName("btnSaveAttendance")
        self.controlLayout.addWidget(self.btnSaveAttendance)
        self.btnExportAttendance = QtWidgets.QPushButton(Attendance)
        self.btnExportAttendance.setObjectName("btnExportAttendance")
        self.controlLayout.addWidget(self.btnExportAttendance)
        self.verticalLayout.addLayout(self.controlLayout)
        self.groupBoxQuickCheck = QtWidgets.QGroupBox(Attendance)
        self.groupBoxQuickCheck.setObjectName("groupBoxQuickCheck")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxQuickCheck)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCheckIn = QtWidgets.QPushButton(self.groupBoxQuickCheck)
        self.btnCheckIn.setMinimumSize(QtCore.QSize(120, 50))
        self.btnCheckIn.setObjectName("btnCheckIn")
        self.horizontalLayout.addWidget(self.btnCheckIn)
        self.btnCheckOut = QtWidgets.QPushButton(self.groupBoxQuickCheck)
        self.btnCheckOut.setMinimumSize(QtCore.QSize(120, 50))
        self.btnCheckOut.setObjectName("btnCheckOut")
        self.horizontalLayout.addWidget(self.btnCheckOut)
        self.lblCheckInLabel = QtWidgets.QLabel(self.groupBoxQuickCheck)
        self.lblCheckInLabel.setObjectName("lblCheckInLabel")
        self.horizontalLayout.addWidget(self.lblCheckInLabel)
        self.lblCheckInTime = QtWidgets.QLabel(self.groupBoxQuickCheck)
        self.lblCheckInTime.setStyleSheet("color: #27ae60;")
        self.lblCheckInTime.setObjectName("lblCheckInTime")
        self.horizontalLayout.addWidget(self.lblCheckInTime)
        self.lblCheckOutLabel = QtWidgets.QLabel(self.groupBoxQuickCheck)
        self.lblCheckOutLabel.setObjectName("lblCheckOutLabel")
        self.horizontalLayout.addWidget(self.lblCheckOutLabel)
        self.lblCheckOutTime = QtWidgets.QLabel(self.groupBoxQuickCheck)
        self.lblCheckOutTime.setStyleSheet("color: #e74c3c;")
        self.lblCheckOutTime.setObjectName("lblCheckOutTime")
        self.horizontalLayout.addWidget(self.lblCheckOutTime)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBoxQuickCheck)
        self.tableAttendance = QtWidgets.QTableWidget(Attendance)
        self.tableAttendance.setAlternatingRowColors(True)
        self.tableAttendance.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableAttendance.setObjectName("tableAttendance")
        self.tableAttendance.setColumnCount(9)
        self.tableAttendance.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAttendance.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.tableAttendance)
        self.groupBoxSummary = QtWidgets.QGroupBox(Attendance)
        self.groupBoxSummary.setObjectName("groupBoxSummary")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBoxSummary)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblWorkDays = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblWorkDays.setObjectName("lblWorkDays")
        self.horizontalLayout_2.addWidget(self.lblWorkDays)
        self.lblWorkDaysValue = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblWorkDaysValue.setFont(font)
        self.lblWorkDaysValue.setObjectName("lblWorkDaysValue")
        self.horizontalLayout_2.addWidget(self.lblWorkDaysValue)
        self.lblLateDays = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblLateDays.setObjectName("lblLateDays")
        self.horizontalLayout_2.addWidget(self.lblLateDays)
        self.lblLateDaysValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblLateDaysValue.setStyleSheet("color: #e74c3c; font-weight: bold;")
        self.lblLateDaysValue.setObjectName("lblLateDaysValue")
        self.horizontalLayout_2.addWidget(self.lblLateDaysValue)
        self.lblLeaveDays = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblLeaveDays.setObjectName("lblLeaveDays")
        self.horizontalLayout_2.addWidget(self.lblLeaveDays)
        self.lblLeaveDaysValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblLeaveDaysValue.setObjectName("lblLeaveDaysValue")
        self.horizontalLayout_2.addWidget(self.lblLeaveDaysValue)
        self.lblTotalHours = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblTotalHours.setObjectName("lblTotalHours")
        self.horizontalLayout_2.addWidget(self.lblTotalHours)
        self.lblTotalHoursValue = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalHoursValue.setFont(font)
        self.lblTotalHoursValue.setObjectName("lblTotalHoursValue")
        self.horizontalLayout_2.addWidget(self.lblTotalHoursValue)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBoxSummary)

        self.retranslateUi(Attendance)

    def retranslateUi(self, Attendance):
        _translate = QtCore.QCoreApplication.translate
        Attendance.setWindowTitle(_translate("Attendance", "Chấm công nhân viên"))
        self.lblTitle.setText(_translate("Attendance", "⏰ CHẤM CÔNG NHÂN VIÊN"))
        self.lblEmployee.setText(_translate("Attendance", "Nhân viên:"))
        self.lblMonth.setText(_translate("Attendance", "Tháng:"))
        self.dateMonth.setDisplayFormat(_translate("Attendance", "MM/yyyy"))
        self.btnLoadAttendance.setText(_translate("Attendance", "📅 Tải dữ liệu"))
        self.btnSaveAttendance.setText(_translate("Attendance", "💾 Lưu chấm công"))
        self.btnExportAttendance.setText(_translate("Attendance", "📊 Xuất Excel"))
        self.groupBoxQuickCheck.setTitle(_translate("Attendance", "⚡ Chấm công nhanh hôm nay"))
        self.btnCheckIn.setText(_translate("Attendance", "✅ Check-in"))
        self.btnCheckOut.setText(_translate("Attendance", "❌ Check-out"))
        self.lblCheckInLabel.setText(_translate("Attendance", "Giờ vào:"))
        self.lblCheckInTime.setText(_translate("Attendance", "--:--:--"))
        self.lblCheckOutLabel.setText(_translate("Attendance", "Giờ ra:"))
        self.lblCheckOutTime.setText(_translate("Attendance", "--:--:--"))
        item = self.tableAttendance.horizontalHeaderItem(0)
        item.setText(_translate("Attendance", "Ngày"))
        item = self.tableAttendance.horizontalHeaderItem(1)
        item.setText(_translate("Attendance", "Thứ"))
        item = self.tableAttendance.horizontalHeaderItem(2)
        item.setText(_translate("Attendance", "Check-in"))
        item = self.tableAttendance.horizontalHeaderItem(3)
        item.setText(_translate("Attendance", "Check-out"))
        item = self.tableAttendance.horizontalHeaderItem(4)
        item.setText(_translate("Attendance", "Số giờ"))
        item = self.tableAttendance.horizontalHeaderItem(5)
        item.setText(_translate("Attendance", "Trạng thái"))
        item = self.tableAttendance.horizontalHeaderItem(6)
        item.setText(_translate("Attendance", "Đi muộn (phút)"))
        item = self.tableAttendance.horizontalHeaderItem(7)
        item.setText(_translate("Attendance", "Về sớm (phút)"))
        item = self.tableAttendance.horizontalHeaderItem(8)
        item.setText(_translate("Attendance", "Ghi chú"))
        self.groupBoxSummary.setTitle(_translate("Attendance", "Tổng kết tháng"))
        self.lblWorkDays.setText(_translate("Attendance", "Số ngày đi làm:"))
        self.lblWorkDaysValue.setText(_translate("Attendance", "0"))
        self.lblLateDays.setText(_translate("Attendance", "Số ngày đi muộn:"))
        self.lblLateDaysValue.setText(_translate("Attendance", "0"))
        self.lblLeaveDays.setText(_translate("Attendance", "Số ngày nghỉ:"))
        self.lblLeaveDaysValue.setText(_translate("Attendance", "0"))
        self.lblTotalHours.setText(_translate("Attendance", "Tổng số giờ làm:"))
        self.lblTotalHoursValue.setText(_translate("Attendance", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Attendance = QtWidgets.QWidget()
    ui = Ui_Attendance()
    ui.setupUi(Attendance)
    Attendance.show()
    sys.exit(app.exec_())
