# Form implementation generated from reading ui file 'ui\customer_management.ui'
#
# Created by: PyQt5 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerManagement(object):
    def setupUi(self, CustomerManagement):
        CustomerManagement.setObjectName("CustomerManagement")
        CustomerManagement.resize(1200, 800)
        CustomerManagement.setStyleSheet("\n"
"    QWidget { background-color: #f5f7fa; }\n"
"    QTableWidget { background-color: white; }\n"
"    QHeaderView::section { background-color: #9b59b6; color: white; padding: 10px; }\n"
"    QPushButton { border-radius: 6px; padding: 8px 15px; }\n"
"    QPushButton#btnAdd { background-color: #27ae60; color: white; }\n"
"    QPushButton#btnEdit { background-color: #3498db; color: white; }\n"
"    QPushButton#btnDelete { background-color: #e74c3c; color: white; }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomerManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=CustomerManagement)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.txtSearch = QtWidgets.QLineEdit(parent=CustomerManagement)
        self.txtSearch.setObjectName("txtSearch")
        self.searchLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(parent=CustomerManagement)
        self.btnSearch.setObjectName("btnSearch")
        self.searchLayout.addWidget(self.btnSearch)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.searchLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(parent=CustomerManagement)
        self.btnAdd.setObjectName("btnAdd")
        self.searchLayout.addWidget(self.btnAdd)
        self.verticalLayout.addLayout(self.searchLayout)
        
        # Add input fields for customer data
        self.groupBoxAddCustomer = QtWidgets.QGroupBox(parent=CustomerManagement)
        self.groupBoxAddCustomer.setObjectName("groupBoxAddCustomer")
        self.groupBoxAddCustomer.setTitle("Thêm/Sửa khách hàng")
        self.gridLayoutAddCustomer = QtWidgets.QGridLayout(self.groupBoxAddCustomer)
        self.gridLayoutAddCustomer.setObjectName("gridLayoutAddCustomer")
        
        # Customer Code
        self.lblCustomerCode = QtWidgets.QLabel(parent=self.groupBoxAddCustomer)
        self.lblCustomerCode.setObjectName("lblCustomerCode")
        self.lblCustomerCode.setText("Mã KH:")
        self.gridLayoutAddCustomer.addWidget(self.lblCustomerCode, 0, 0, 1, 1)
        self.txtCustomerCode = QtWidgets.QLineEdit(parent=self.groupBoxAddCustomer)
        self.txtCustomerCode.setObjectName("txtCustomerCode")
        self.gridLayoutAddCustomer.addWidget(self.txtCustomerCode, 0, 1, 1, 1)
        
        # Customer Name
        self.lblCustomerName = QtWidgets.QLabel(parent=self.groupBoxAddCustomer)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.lblCustomerName.setText("Tên KH:")
        self.gridLayoutAddCustomer.addWidget(self.lblCustomerName, 1, 0, 1, 1)
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.groupBoxAddCustomer)
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.gridLayoutAddCustomer.addWidget(self.txtCustomerName, 1, 1, 1, 1)
        
        # Phone
        self.lblPhone = QtWidgets.QLabel(parent=self.groupBoxAddCustomer)
        self.lblPhone.setObjectName("lblPhone")
        self.lblPhone.setText("Điện thoại:")
        self.gridLayoutAddCustomer.addWidget(self.lblPhone, 0, 2, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(parent=self.groupBoxAddCustomer)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayoutAddCustomer.addWidget(self.txtPhone, 0, 3, 1, 1)
        
        # Email
        self.lblEmail = QtWidgets.QLabel(parent=self.groupBoxAddCustomer)
        self.lblEmail.setObjectName("lblEmail")
        self.lblEmail.setText("Email:")
        self.gridLayoutAddCustomer.addWidget(self.lblEmail, 1, 2, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.groupBoxAddCustomer)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayoutAddCustomer.addWidget(self.txtEmail, 1, 3, 1, 1)
        
        # Address
        self.lblAddress = QtWidgets.QLabel(parent=self.groupBoxAddCustomer)
        self.lblAddress.setObjectName("lblAddress")
        self.lblAddress.setText("Địa chỉ:")
        self.gridLayoutAddCustomer.addWidget(self.lblAddress, 2, 0, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(parent=self.groupBoxAddCustomer)
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayoutAddCustomer.addWidget(self.txtAddress, 2, 1, 1, 3)
        
        # Action buttons
        self.btnEditCustomer = QtWidgets.QPushButton(parent=self.groupBoxAddCustomer)
        self.btnEditCustomer.setObjectName("btnEditCustomer")
        self.btnEditCustomer.setText("✏️ Cập nhật")
        self.gridLayoutAddCustomer.addWidget(self.btnEditCustomer, 3, 0, 1, 2)
        
        self.btnDelete = QtWidgets.QPushButton(parent=self.groupBoxAddCustomer)
        self.btnDelete.setObjectName("btnDelete")
        self.btnDelete.setText("🗑️ Xóa khách hàng")
        self.gridLayoutAddCustomer.addWidget(self.btnDelete, 3, 2, 1, 2)
        
        self.verticalLayout.addWidget(self.groupBoxAddCustomer)
        
        self.tableCustomers = QtWidgets.QTableWidget(parent=CustomerManagement)
        self.tableCustomers.setAlternatingRowColors(True)
        self.tableCustomers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableCustomers.setObjectName("tableCustomers")
        self.tableCustomers.setColumnCount(7)
        self.tableCustomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableCustomers)

        self.retranslateUi(CustomerManagement)

    def retranslateUi(self, CustomerManagement):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagement.setWindowTitle(_translate("CustomerManagement", "Quản lý khách hàng"))
        self.label.setText(_translate("CustomerManagement", "👥 QUẢN LÝ KHÁCH HÀNG"))
        self.txtSearch.setPlaceholderText(_translate("CustomerManagement", "Tìm kiếm khách hàng..."))
        self.btnSearch.setText(_translate("CustomerManagement", "🔍 Tìm"))
        self.btnAdd.setText(_translate("CustomerManagement", "➕ Thêm khách hàng"))
        self.txtCustomerCode.setPlaceholderText(_translate("CustomerManagement", "Nhập mã khách hàng"))
        self.txtCustomerName.setPlaceholderText(_translate("CustomerManagement", "Nhập tên khách hàng"))
        self.txtPhone.setPlaceholderText(_translate("CustomerManagement", "Nhập số điện thoại"))
        self.txtEmail.setPlaceholderText(_translate("CustomerManagement", "Nhập email"))
        self.txtAddress.setPlaceholderText(_translate("CustomerManagement", "Nhập địa chỉ"))
        item = self.tableCustomers.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagement", "ID"))
        item = self.tableCustomers.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagement", "Mã KH"))
        item = self.tableCustomers.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagement", "Tên khách hàng"))
        item = self.tableCustomers.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagement", "Điện thoại"))
        item = self.tableCustomers.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagement", "Email"))
        item = self.tableCustomers.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagement", "Địa chỉ"))
        item = self.tableCustomers.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagement", "Điểm tích lũy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerManagement = QtWidgets.QWidget()
    ui = Ui_CustomerManagement()
    ui.setupUi(CustomerManagement)
    CustomerManagement.show()
    sys.exit(app.exec())
