# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\customer_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomerManagement(object):
    def setupUi(self, CustomerManagement):
        CustomerManagement.setObjectName("CustomerManagement")
        CustomerManagement.resize(1400, 900)
        CustomerManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #9b59b6;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 13px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"        font-size: 13px;\n"
"    }\n"
"    QPushButton#btnAdd {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnAdd:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnEdit {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnEdit:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnDelete {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnDelete:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QPushButton#btnSave {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClear {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QTextEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 13px;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus {\n"
"        border-color: #9b59b6;\n"
"        outline: none;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 22px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomerManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(CustomerManagement)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxSearch = QtWidgets.QGroupBox(CustomerManagement)
        self.groupBoxSearch.setObjectName("groupBoxSearch")
        self.searchLayout = QtWidgets.QHBoxLayout(self.groupBoxSearch)
        self.searchLayout.setObjectName("searchLayout")
        self.lblSearch = QtWidgets.QLabel(self.groupBoxSearch)
        self.lblSearch.setObjectName("lblSearch")
        self.searchLayout.addWidget(self.lblSearch)
        self.txtSearch = QtWidgets.QLineEdit(self.groupBoxSearch)
        self.txtSearch.setMinimumSize(QtCore.QSize(350, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.searchLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnSearch.setObjectName("btnSearch")
        self.searchLayout.addWidget(self.btnSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnAdd.setObjectName("btnAdd")
        self.searchLayout.addWidget(self.btnAdd)
        self.verticalLayout.addWidget(self.groupBoxSearch)
        self.groupBoxCustomerList = QtWidgets.QGroupBox(CustomerManagement)
        self.groupBoxCustomerList.setObjectName("groupBoxCustomerList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxCustomerList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableCustomers = QtWidgets.QTableWidget(self.groupBoxCustomerList)
        self.tableCustomers.setAlternatingRowColors(True)
        self.tableCustomers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableCustomers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableCustomers.setObjectName("tableCustomers")
        self.tableCustomers.setColumnCount(8)
        self.tableCustomers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCustomers.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.tableCustomers)
        self.verticalLayout.addWidget(self.groupBoxCustomerList)
        self.groupBoxCustomerForm = QtWidgets.QGroupBox(CustomerManagement)
        self.groupBoxCustomerForm.setObjectName("groupBoxCustomerForm")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxCustomerForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lblCustomerCode = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCustomerCode.setFont(font)
        self.lblCustomerCode.setObjectName("lblCustomerCode")
        self.gridLayout.addWidget(self.lblCustomerCode, 0, 0, 1, 1)
        self.txtCustomerCode = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtCustomerCode.setObjectName("txtCustomerCode")
        self.gridLayout.addWidget(self.txtCustomerCode, 0, 1, 1, 1)
        self.lblCustomerName = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCustomerName.setFont(font)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.gridLayout.addWidget(self.lblCustomerName, 0, 2, 1, 1)
        self.txtCustomerName = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.gridLayout.addWidget(self.txtCustomerName, 0, 3, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPhone.setFont(font)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout.addWidget(self.lblPhone, 1, 0, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout.addWidget(self.txtPhone, 1, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail.setFont(font)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 1, 2, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout.addWidget(self.txtEmail, 1, 3, 1, 1)
        self.lblAddress = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAddress.setFont(font)
        self.lblAddress.setObjectName("lblAddress")
        self.gridLayout.addWidget(self.lblAddress, 2, 0, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayout.addWidget(self.txtAddress, 2, 1, 1, 3)
        self.lblPoints = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPoints.setFont(font)
        self.lblPoints.setObjectName("lblPoints")
        self.gridLayout.addWidget(self.lblPoints, 3, 0, 1, 1)
        self.txtPoints = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtPoints.setObjectName("txtPoints")
        self.gridLayout.addWidget(self.txtPoints, 3, 1, 1, 1)
        self.lblNotes = QtWidgets.QLabel(self.groupBoxCustomerForm)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblNotes.setFont(font)
        self.lblNotes.setObjectName("lblNotes")
        self.gridLayout.addWidget(self.lblNotes, 3, 2, 1, 1)
        self.txtNotes = QtWidgets.QLineEdit(self.groupBoxCustomerForm)
        self.txtNotes.setObjectName("txtNotes")
        self.gridLayout.addWidget(self.txtNotes, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxCustomerForm)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(CustomerManagement)
        self.btnSave.setMinimumSize(QtCore.QSize(140, 35))
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.btnEdit = QtWidgets.QPushButton(CustomerManagement)
        self.btnEdit.setMinimumSize(QtCore.QSize(140, 35))
        self.btnEdit.setObjectName("btnEdit")
        self.buttonLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(CustomerManagement)
        self.btnDelete.setMinimumSize(QtCore.QSize(140, 35))
        self.btnDelete.setObjectName("btnDelete")
        self.buttonLayout.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(CustomerManagement)
        self.btnClear.setMinimumSize(QtCore.QSize(140, 35))
        self.btnClear.setObjectName("btnClear")
        self.buttonLayout.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(CustomerManagement)

    def retranslateUi(self, CustomerManagement):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagement.setWindowTitle(_translate("CustomerManagement", "Quản lý khách hàng"))
        self.lblTitle.setText(_translate("CustomerManagement", "👥 QUẢN LÝ KHÁCH HÀNG"))
        self.groupBoxSearch.setTitle(_translate("CustomerManagement", "🔍 Tìm kiếm khách hàng"))
        self.lblSearch.setText(_translate("CustomerManagement", "Tìm kiếm:"))
        self.txtSearch.setPlaceholderText(_translate("CustomerManagement", "Tìm theo mã, tên, số điện thoại..."))
        self.btnSearch.setText(_translate("CustomerManagement", "🔍 Tìm kiếm"))
        self.btnAdd.setText(_translate("CustomerManagement", "➕ Thêm khách hàng"))
        self.groupBoxCustomerList.setTitle(_translate("CustomerManagement", "📋 Danh sách khách hàng"))
        item = self.tableCustomers.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagement", "ID"))
        item = self.tableCustomers.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagement", "Mã KH"))
        item = self.tableCustomers.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagement", "Tên khách hàng"))
        item = self.tableCustomers.horizontalHeaderItem(3)
        item.setText(_translate("CustomerManagement", "Điện thoại"))
        item = self.tableCustomers.horizontalHeaderItem(4)
        item.setText(_translate("CustomerManagement", "Email"))
        item = self.tableCustomers.horizontalHeaderItem(5)
        item.setText(_translate("CustomerManagement", "Địa chỉ"))
        item = self.tableCustomers.horizontalHeaderItem(6)
        item.setText(_translate("CustomerManagement", "Điểm tích lũy"))
        item = self.tableCustomers.horizontalHeaderItem(7)
        item.setText(_translate("CustomerManagement", "Ngày tạo"))
        self.groupBoxCustomerForm.setTitle(_translate("CustomerManagement", "📝 Nhập thông tin khách hàng"))
        self.lblCustomerCode.setText(_translate("CustomerManagement", "Mã khách hàng:"))
        self.txtCustomerCode.setPlaceholderText(_translate("CustomerManagement", "Nhập mã khách hàng (VD: KH001)"))
        self.lblCustomerName.setText(_translate("CustomerManagement", "Tên khách hàng:"))
        self.txtCustomerName.setPlaceholderText(_translate("CustomerManagement", "Nhập tên khách hàng"))
        self.lblPhone.setText(_translate("CustomerManagement", "Điện thoại:"))
        self.txtPhone.setPlaceholderText(_translate("CustomerManagement", "Nhập số điện thoại"))
        self.lblEmail.setText(_translate("CustomerManagement", "Email:"))
        self.txtEmail.setPlaceholderText(_translate("CustomerManagement", "Nhập địa chỉ email"))
        self.lblAddress.setText(_translate("CustomerManagement", "Địa chỉ:"))
        self.txtAddress.setPlaceholderText(_translate("CustomerManagement", "Nhập địa chỉ khách hàng"))
        self.lblPoints.setText(_translate("CustomerManagement", "Điểm tích lũy:"))
        self.txtPoints.setText(_translate("CustomerManagement", "0"))
        self.txtPoints.setPlaceholderText(_translate("CustomerManagement", "Điểm tích lũy"))
        self.lblNotes.setText(_translate("CustomerManagement", "Ghi chú:"))
        self.txtNotes.setPlaceholderText(_translate("CustomerManagement", "Ghi chú thêm (tùy chọn)"))
        self.btnSave.setText(_translate("CustomerManagement", "💾 Lưu khách hàng"))
        self.btnEdit.setText(_translate("CustomerManagement", "✏️ Sửa khách hàng"))
        self.btnDelete.setText(_translate("CustomerManagement", "🗑️ Xóa khách hàng"))
        self.btnClear.setText(_translate("CustomerManagement", "🔄 Xóa form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CustomerManagement = QtWidgets.QWidget()
    ui = Ui_CustomerManagement()
    ui.setupUi(CustomerManagement)
    CustomerManagement.show()
    sys.exit(app.exec_())
