# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\employee_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmployeeManagement(object):
    def setupUi(self, EmployeeManagement):
        EmployeeManagement.setObjectName("EmployeeManagement")
        EmployeeManagement.resize(1400, 900)
        EmployeeManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"        font-size: 13px;\n"
"    }\n"
"    QPushButton#btnAdd {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnAdd:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnSave {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSave:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnDelete {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnDelete:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QPushButton#btnClear {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClear:hover {\n"
"        background-color: #e67e22;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExportExcel {\n"
"        background-color: #1abc9c;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 13px;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QDateEdit:focus {\n"
"        border-color: #3498db;\n"
"        outline: none;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 1px solid #e1e8ed;\n"
"        border-radius: 10px;\n"
"        background-color: white;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background-color: #ecf0f1;\n"
"        padding: 10px 25px;\n"
"        margin-right: 3px;\n"
"        border-top-left-radius: 8px;\n"
"        border-top-right-radius: 8px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QRadioButton {\n"
"        margin-right: 15px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(EmployeeManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.label = QtWidgets.QLabel(EmployeeManagement)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.searchLayout.addWidget(self.label)
        self.txtSearch = QtWidgets.QLineEdit(EmployeeManagement)
        self.txtSearch.setMinimumSize(QtCore.QSize(300, 0))
        self.txtSearch.setObjectName("txtSearch")
        self.searchLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(EmployeeManagement)
        self.btnSearch.setObjectName("btnSearch")
        self.searchLayout.addWidget(self.btnSearch)
        self.label_2 = QtWidgets.QLabel(EmployeeManagement)
        self.label_2.setObjectName("label_2")
        self.searchLayout.addWidget(self.label_2)
        self.cboRoleFilter = QtWidgets.QComboBox(EmployeeManagement)
        self.cboRoleFilter.setObjectName("cboRoleFilter")
        self.cboRoleFilter.addItem("")
        self.cboRoleFilter.addItem("")
        self.cboRoleFilter.addItem("")
        self.cboRoleFilter.addItem("")
        self.cboRoleFilter.addItem("")
        self.searchLayout.addWidget(self.cboRoleFilter)
        self.label_3 = QtWidgets.QLabel(EmployeeManagement)
        self.label_3.setObjectName("label_3")
        self.searchLayout.addWidget(self.label_3)
        self.cboStatusFilter = QtWidgets.QComboBox(EmployeeManagement)
        self.cboStatusFilter.setObjectName("cboStatusFilter")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.cboStatusFilter.addItem("")
        self.searchLayout.addWidget(self.cboStatusFilter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(EmployeeManagement)
        self.btnAdd.setObjectName("btnAdd")
        self.searchLayout.addWidget(self.btnAdd)
        self.btnExportExcel = QtWidgets.QPushButton(EmployeeManagement)
        self.btnExportExcel.setObjectName("btnExportExcel")
        self.searchLayout.addWidget(self.btnExportExcel)
        self.verticalLayout.addLayout(self.searchLayout)
        self.tableEmployees = QtWidgets.QTableWidget(EmployeeManagement)
        self.tableEmployees.setAlternatingRowColors(True)
        self.tableEmployees.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableEmployees.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableEmployees.setObjectName("tableEmployees")
        self.tableEmployees.setColumnCount(10)
        self.tableEmployees.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployees.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tableEmployees)
        self.tabWidget = QtWidgets.QTabWidget(EmployeeManagement)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPersonal = QtWidgets.QWidget()
        self.tabPersonal.setObjectName("tabPersonal")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabPersonal)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBoxAvatar = QtWidgets.QGroupBox(self.tabPersonal)
        self.groupBoxAvatar.setMinimumSize(QtCore.QSize(220, 0))
        self.groupBoxAvatar.setMaximumSize(QtCore.QSize(220, 16777215))
        self.groupBoxAvatar.setObjectName("groupBoxAvatar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxAvatar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblAvatar = QtWidgets.QLabel(self.groupBoxAvatar)
        self.lblAvatar.setMinimumSize(QtCore.QSize(160, 160))
        self.lblAvatar.setFrameShape(QtWidgets.QFrame.Box)
        self.lblAvatar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAvatar.setStyleSheet("font-size: 80px;")
        self.lblAvatar.setObjectName("lblAvatar")
        self.verticalLayout_2.addWidget(self.lblAvatar)
        self.btnSelectAvatar = QtWidgets.QPushButton(self.groupBoxAvatar)
        self.btnSelectAvatar.setObjectName("btnSelectAvatar")
        self.verticalLayout_2.addWidget(self.btnSelectAvatar)
        self.horizontalLayout_2.addWidget(self.groupBoxAvatar)
        self.groupBoxPersonal = QtWidgets.QGroupBox(self.tabPersonal)
        self.groupBoxPersonal.setObjectName("groupBoxPersonal")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxPersonal)
        self.gridLayout.setObjectName("gridLayout")
        self.lblEmployeeCode = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblEmployeeCode.setObjectName("lblEmployeeCode")
        self.gridLayout.addWidget(self.lblEmployeeCode, 0, 0, 1, 1)
        self.txtEmployeeCode = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtEmployeeCode.setReadOnly(True)
        self.txtEmployeeCode.setStyleSheet("background-color: #f0f0f0;")
        self.txtEmployeeCode.setObjectName("txtEmployeeCode")
        self.gridLayout.addWidget(self.txtEmployeeCode, 0, 1, 1, 1)
        self.lblFullName = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblFullName.setObjectName("lblFullName")
        self.gridLayout.addWidget(self.lblFullName, 0, 2, 1, 1)
        self.txtFullName = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtFullName.setObjectName("txtFullName")
        self.gridLayout.addWidget(self.txtFullName, 0, 3, 1, 1)
        self.lblGender = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblGender.setObjectName("lblGender")
        self.gridLayout.addWidget(self.lblGender, 1, 0, 1, 1)
        self.genderLayout = QtWidgets.QHBoxLayout()
        self.genderLayout.setObjectName("genderLayout")
        self.rdMale = QtWidgets.QRadioButton(self.groupBoxPersonal)
        self.rdMale.setChecked(True)
        self.rdMale.setObjectName("rdMale")
        self.genderLayout.addWidget(self.rdMale)
        self.rdFemale = QtWidgets.QRadioButton(self.groupBoxPersonal)
        self.rdFemale.setObjectName("rdFemale")
        self.genderLayout.addWidget(self.rdFemale)
        self.rdOther = QtWidgets.QRadioButton(self.groupBoxPersonal)
        self.rdOther.setObjectName("rdOther")
        self.genderLayout.addWidget(self.rdOther)
        self.gridLayout.addLayout(self.genderLayout, 1, 1, 1, 1)
        self.lblBirthDate = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblBirthDate.setObjectName("lblBirthDate")
        self.gridLayout.addWidget(self.lblBirthDate, 1, 2, 1, 1)
        self.dateBirthDate = QtWidgets.QDateEdit(self.groupBoxPersonal)
        self.dateBirthDate.setCalendarPopup(True)
        self.dateBirthDate.setDate(QtCore.QDate(1990, 1, 1))
        self.dateBirthDate.setObjectName("dateBirthDate")
        self.gridLayout.addWidget(self.dateBirthDate, 1, 3, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout.addWidget(self.lblPhone, 2, 0, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout.addWidget(self.txtPhone, 2, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 2, 2, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout.addWidget(self.txtEmail, 2, 3, 1, 1)
        self.lblIdentityCard = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblIdentityCard.setObjectName("lblIdentityCard")
        self.gridLayout.addWidget(self.lblIdentityCard, 3, 0, 1, 1)
        self.txtIdentityCard = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtIdentityCard.setObjectName("txtIdentityCard")
        self.gridLayout.addWidget(self.txtIdentityCard, 3, 1, 1, 1)
        self.lblAddress = QtWidgets.QLabel(self.groupBoxPersonal)
        self.lblAddress.setObjectName("lblAddress")
        self.gridLayout.addWidget(self.lblAddress, 3, 2, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(self.groupBoxPersonal)
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayout.addWidget(self.txtAddress, 3, 3, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBoxPersonal)
        self.tabWidget.addTab(self.tabPersonal, "")
        self.tabWork = QtWidgets.QWidget()
        self.tabWork.setObjectName("tabWork")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabWork)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBoxWork = QtWidgets.QGroupBox(self.tabWork)
        self.groupBoxWork.setObjectName("groupBoxWork")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxWork)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblHireDate = QtWidgets.QLabel(self.groupBoxWork)
        self.lblHireDate.setObjectName("lblHireDate")
        self.gridLayout_3.addWidget(self.lblHireDate, 0, 0, 1, 1)
        self.dateHireDate = QtWidgets.QDateEdit(self.groupBoxWork)
        self.dateHireDate.setCalendarPopup(True)
        self.dateHireDate.setDate(QtCore.QDate(2024, 1, 1))
        self.dateHireDate.setObjectName("dateHireDate")
        self.gridLayout_3.addWidget(self.dateHireDate, 0, 1, 1, 1)
        self.lblRole = QtWidgets.QLabel(self.groupBoxWork)
        self.lblRole.setObjectName("lblRole")
        self.gridLayout_3.addWidget(self.lblRole, 0, 2, 1, 1)
        self.cboRole = QtWidgets.QComboBox(self.groupBoxWork)
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.gridLayout_3.addWidget(self.cboRole, 0, 3, 1, 1)
        self.lblBaseSalary = QtWidgets.QLabel(self.groupBoxWork)
        self.lblBaseSalary.setObjectName("lblBaseSalary")
        self.gridLayout_3.addWidget(self.lblBaseSalary, 1, 0, 1, 1)
        self.txtBaseSalary = QtWidgets.QLineEdit(self.groupBoxWork)
        self.txtBaseSalary.setObjectName("txtBaseSalary")
        self.gridLayout_3.addWidget(self.txtBaseSalary, 1, 1, 1, 1)
        self.lblCommission = QtWidgets.QLabel(self.groupBoxWork)
        self.lblCommission.setObjectName("lblCommission")
        self.gridLayout_3.addWidget(self.lblCommission, 1, 2, 1, 1)
        self.txtCommissionRate = QtWidgets.QLineEdit(self.groupBoxWork)
        self.txtCommissionRate.setObjectName("txtCommissionRate")
        self.gridLayout_3.addWidget(self.txtCommissionRate, 1, 3, 1, 1)
        self.lblUsername = QtWidgets.QLabel(self.groupBoxWork)
        self.lblUsername.setObjectName("lblUsername")
        self.gridLayout_3.addWidget(self.lblUsername, 2, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(self.groupBoxWork)
        self.txtUsername.setObjectName("txtUsername")
        self.gridLayout_3.addWidget(self.txtUsername, 2, 1, 1, 1)
        self.lblPassword = QtWidgets.QLabel(self.groupBoxWork)
        self.lblPassword.setObjectName("lblPassword")
        self.gridLayout_3.addWidget(self.lblPassword, 2, 2, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(self.groupBoxWork)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout_3.addWidget(self.txtPassword, 2, 3, 1, 1)
        self.lblStatus = QtWidgets.QLabel(self.groupBoxWork)
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout_3.addWidget(self.lblStatus, 3, 0, 1, 1)
        self.cboStatus = QtWidgets.QComboBox(self.groupBoxWork)
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.gridLayout_3.addWidget(self.cboStatus, 3, 1, 1, 1)
        self.lblNote = QtWidgets.QLabel(self.groupBoxWork)
        self.lblNote.setObjectName("lblNote")
        self.gridLayout_3.addWidget(self.lblNote, 3, 2, 1, 1)
        self.txtNote = QtWidgets.QLineEdit(self.groupBoxWork)
        self.txtNote.setObjectName("txtNote")
        self.gridLayout_3.addWidget(self.txtNote, 3, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxWork, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWork, "")
        self.tabStats = QtWidgets.QWidget()
        self.tabStats.setObjectName("tabStats")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabStats)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblStatsInfo = QtWidgets.QLabel(self.tabStats)
        self.lblStatsInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblStatsInfo.setStyleSheet("font-size: 16px; color: #7f8c8d; padding: 30px;")
        self.lblStatsInfo.setObjectName("lblStatsInfo")
        self.verticalLayout_3.addWidget(self.lblStatsInfo)
        self.tabWidget.addTab(self.tabStats, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(EmployeeManagement)
        self.btnSave.setMinimumSize(QtCore.QSize(100, 0))
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.btnUpdate = QtWidgets.QPushButton(EmployeeManagement)
        self.btnUpdate.setMinimumSize(QtCore.QSize(100, 0))
        self.btnUpdate.setObjectName("btnUpdate")
        self.buttonLayout.addWidget(self.btnUpdate)
        self.btnDelete = QtWidgets.QPushButton(EmployeeManagement)
        self.btnDelete.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDelete.setObjectName("btnDelete")
        self.buttonLayout.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(EmployeeManagement)
        self.btnClear.setMinimumSize(QtCore.QSize(100, 0))
        self.btnClear.setObjectName("btnClear")
        self.buttonLayout.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(EmployeeManagement)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, EmployeeManagement):
        _translate = QtCore.QCoreApplication.translate
        EmployeeManagement.setWindowTitle(_translate("EmployeeManagement", "Quản lý nhân viên"))
        self.label.setText(_translate("EmployeeManagement", "🔍 Tìm kiếm:"))
        self.txtSearch.setPlaceholderText(_translate("EmployeeManagement", "Tìm theo mã, tên, số điện thoại, email..."))
        self.btnSearch.setText(_translate("EmployeeManagement", "🔍 Tìm kiếm"))
        self.label_2.setText(_translate("EmployeeManagement", "Vai trò:"))
        self.cboRoleFilter.setItemText(0, _translate("EmployeeManagement", "Tất cả"))
        self.cboRoleFilter.setItemText(1, _translate("EmployeeManagement", "Admin"))
        self.cboRoleFilter.setItemText(2, _translate("EmployeeManagement", "Sale"))
        self.cboRoleFilter.setItemText(3, _translate("EmployeeManagement", "Warehouse"))
        self.cboRoleFilter.setItemText(4, _translate("EmployeeManagement", "Accountant"))
        self.label_3.setText(_translate("EmployeeManagement", "Trạng thái:"))
        self.cboStatusFilter.setItemText(0, _translate("EmployeeManagement", "Tất cả"))
        self.cboStatusFilter.setItemText(1, _translate("EmployeeManagement", "Đang làm"))
        self.cboStatusFilter.setItemText(2, _translate("EmployeeManagement", "Tạm nghỉ"))
        self.cboStatusFilter.setItemText(3, _translate("EmployeeManagement", "Đã nghỉ"))
        self.btnAdd.setText(_translate("EmployeeManagement", "➕ Thêm mới"))
        self.btnExportExcel.setText(_translate("EmployeeManagement", "📊 Xuất Excel"))
        item = self.tableEmployees.horizontalHeaderItem(0)
        item.setText(_translate("EmployeeManagement", "ID"))
        item = self.tableEmployees.horizontalHeaderItem(1)
        item.setText(_translate("EmployeeManagement", "Mã NV"))
        item = self.tableEmployees.horizontalHeaderItem(2)
        item.setText(_translate("EmployeeManagement", "Họ tên"))
        item = self.tableEmployees.horizontalHeaderItem(3)
        item.setText(_translate("EmployeeManagement", "Giới tính"))
        item = self.tableEmployees.horizontalHeaderItem(4)
        item.setText(_translate("EmployeeManagement", "Điện thoại"))
        item = self.tableEmployees.horizontalHeaderItem(5)
        item.setText(_translate("EmployeeManagement", "Email"))
        item = self.tableEmployees.horizontalHeaderItem(6)
        item.setText(_translate("EmployeeManagement", "Vai trò"))
        item = self.tableEmployees.horizontalHeaderItem(7)
        item.setText(_translate("EmployeeManagement", "Trạng thái"))
        item = self.tableEmployees.horizontalHeaderItem(8)
        item.setText(_translate("EmployeeManagement", "Lương CB"))
        item = self.tableEmployees.horizontalHeaderItem(9)
        item.setText(_translate("EmployeeManagement", "Ngày vào"))
        self.groupBoxAvatar.setTitle(_translate("EmployeeManagement", "Ảnh đại diện"))
        self.lblAvatar.setText(_translate("EmployeeManagement", "👤"))
        self.btnSelectAvatar.setText(_translate("EmployeeManagement", "📷 Chọn ảnh"))
        self.groupBoxPersonal.setTitle(_translate("EmployeeManagement", "Thông tin cơ bản"))
        self.lblEmployeeCode.setText(_translate("EmployeeManagement", "Mã nhân viên:"))
        self.lblFullName.setText(_translate("EmployeeManagement", "Họ và tên:"))
        self.lblGender.setText(_translate("EmployeeManagement", "Giới tính:"))
        self.rdMale.setText(_translate("EmployeeManagement", "Nam"))
        self.rdFemale.setText(_translate("EmployeeManagement", "Nữ"))
        self.rdOther.setText(_translate("EmployeeManagement", "Khác"))
        self.lblBirthDate.setText(_translate("EmployeeManagement", "Ngày sinh:"))
        self.lblPhone.setText(_translate("EmployeeManagement", "Điện thoại:"))
        self.lblEmail.setText(_translate("EmployeeManagement", "Email:"))
        self.lblIdentityCard.setText(_translate("EmployeeManagement", "CMND/CCCD:"))
        self.lblAddress.setText(_translate("EmployeeManagement", "Địa chỉ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPersonal), _translate("EmployeeManagement", "📝 Thông tin cá nhân"))
        self.groupBoxWork.setTitle(_translate("EmployeeManagement", "Thông tin công việc"))
        self.lblHireDate.setText(_translate("EmployeeManagement", "Ngày vào làm:"))
        self.lblRole.setText(_translate("EmployeeManagement", "Vai trò:"))
        self.cboRole.setItemText(0, _translate("EmployeeManagement", "Admin (Quản trị hệ thống)"))
        self.cboRole.setItemText(1, _translate("EmployeeManagement", "Sale (Nhân viên bán hàng)"))
        self.cboRole.setItemText(2, _translate("EmployeeManagement", "Warehouse (Quản lý kho)"))
        self.cboRole.setItemText(3, _translate("EmployeeManagement", "Accountant (Kế toán)"))
        self.lblBaseSalary.setText(_translate("EmployeeManagement", "Lương cơ bản:"))
        self.txtBaseSalary.setPlaceholderText(_translate("EmployeeManagement", "VNĐ"))
        self.lblCommission.setText(_translate("EmployeeManagement", "Hoa hồng (%):"))
        self.txtCommissionRate.setPlaceholderText(_translate("EmployeeManagement", "%"))
        self.lblUsername.setText(_translate("EmployeeManagement", "Tài khoản:"))
        self.lblPassword.setText(_translate("EmployeeManagement", "Mật khẩu:"))
        self.lblStatus.setText(_translate("EmployeeManagement", "Trạng thái:"))
        self.cboStatus.setItemText(0, _translate("EmployeeManagement", "✅ Đang làm"))
        self.cboStatus.setItemText(1, _translate("EmployeeManagement", "⏸️ Tạm nghỉ"))
        self.cboStatus.setItemText(2, _translate("EmployeeManagement", "❌ Đã nghỉ"))
        self.lblNote.setText(_translate("EmployeeManagement", "Ghi chú:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWork), _translate("EmployeeManagement", "💼 Thông tin làm việc"))
        self.lblStatsInfo.setText(_translate("EmployeeManagement", "📈 Chọn nhân viên từ danh sách để xem thống kê chi tiết"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabStats), _translate("EmployeeManagement", "📊 Thống kê & KPI"))
        self.btnSave.setText(_translate("EmployeeManagement", "💾 Lưu"))
        self.btnUpdate.setText(_translate("EmployeeManagement", "✏️ Cập nhật"))
        self.btnDelete.setText(_translate("EmployeeManagement", "🗑️ Xóa"))
        self.btnClear.setText(_translate("EmployeeManagement", "🔄 Xóa form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EmployeeManagement = QtWidgets.QWidget()
    ui = Ui_EmployeeManagement()
    ui.setupUi(EmployeeManagement)
    EmployeeManagement.show()
    sys.exit(app.exec_())
