# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\EmployeeSalesReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EmployeeSalesReport(object):
    def setupUi(self, EmployeeSalesReport):
        EmployeeSalesReport.setObjectName("EmployeeSalesReport")
        EmployeeSalesReport.resize(1400, 900)
        EmployeeSalesReport.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 10px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        min-width: 120px;\n"
"        min-height: 40px;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnExport {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExport:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnPrint {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnPrint:hover {\n"
"        background-color: #8e44ad;\n"
"    }\n"
"    QPushButton#btnReset {\n"
"        background-color: #e67e22;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit {\n"
"        padding: 12px 16px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 16px;\n"
"        min-height: 35px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 26px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblTotalRevenue {\n"
"        font-size: 28px;\n"
"        font-weight: bold;\n"
"        color: #27ae60;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(EmployeeSalesReport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(EmployeeSalesReport)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxFilter = QtWidgets.QGroupBox(EmployeeSalesReport)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.lblEmployee = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblEmployee.setObjectName("lblEmployee")
        self.gridLayout.addWidget(self.lblEmployee, 0, 0, 1, 1)
        self.cboEmployee = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboEmployee.setObjectName("cboEmployee")
        self.cboEmployee.addItem("")
        self.cboEmployee.addItem("")
        self.cboEmployee.addItem("")
        self.cboEmployee.addItem("")
        self.cboEmployee.addItem("")
        self.gridLayout.addWidget(self.cboEmployee, 0, 1, 1, 1)
        self.lblDateRange = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblDateRange.setObjectName("lblDateRange")
        self.gridLayout.addWidget(self.lblDateRange, 0, 2, 1, 1)
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setObjectName("dateLayout")
        self.dateFrom = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.dateLayout.addWidget(self.dateFrom)
        self.lblTo = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblTo.setObjectName("lblTo")
        self.dateLayout.addWidget(self.lblTo)
        self.dateTo = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.dateLayout.addWidget(self.dateTo)
        self.gridLayout.addLayout(self.dateLayout, 0, 3, 1, 1)
        self.lblQuickFilter = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblQuickFilter.setObjectName("lblQuickFilter")
        self.gridLayout.addWidget(self.lblQuickFilter, 1, 0, 1, 1)
        self.quickFilterLayout = QtWidgets.QHBoxLayout()
        self.quickFilterLayout.setObjectName("quickFilterLayout")
        self.btnToday = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnToday.setMinimumSize(QtCore.QSize(80, 35))
        self.btnToday.setObjectName("btnToday")
        self.quickFilterLayout.addWidget(self.btnToday)
        self.btnWeek = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnWeek.setObjectName("btnWeek")
        self.quickFilterLayout.addWidget(self.btnWeek)
        self.btnMonth = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnMonth.setObjectName("btnMonth")
        self.quickFilterLayout.addWidget(self.btnMonth)
        self.btnQuarter = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnQuarter.setObjectName("btnQuarter")
        self.quickFilterLayout.addWidget(self.btnQuarter)
        self.btnYear = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnYear.setObjectName("btnYear")
        self.quickFilterLayout.addWidget(self.btnYear)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.quickFilterLayout.addItem(spacerItem)
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnSearch.setObjectName("btnSearch")
        self.quickFilterLayout.addWidget(self.btnSearch)
        self.btnReset = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnReset.setObjectName("btnReset")
        self.quickFilterLayout.addWidget(self.btnReset)
        self.gridLayout.addLayout(self.quickFilterLayout, 1, 1, 1, 3)
        self.verticalLayout.addWidget(self.groupBoxFilter)
        self.groupBoxStats = QtWidgets.QGroupBox(EmployeeSalesReport)
        self.groupBoxStats.setObjectName("groupBoxStats")
        self.statsLayout = QtWidgets.QHBoxLayout(self.groupBoxStats)
        self.statsLayout.setObjectName("statsLayout")
        self.lblTotalOrders = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalOrders.setFont(font)
        self.lblTotalOrders.setObjectName("lblTotalOrders")
        self.statsLayout.addWidget(self.lblTotalOrders)
        self.lblTotalProductsSold = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalProductsSold.setFont(font)
        self.lblTotalProductsSold.setObjectName("lblTotalProductsSold")
        self.statsLayout.addWidget(self.lblTotalProductsSold)
        self.lblTotalRevenue = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalRevenue.setFont(font)
        self.lblTotalRevenue.setObjectName("lblTotalRevenue")
        self.statsLayout.addWidget(self.lblTotalRevenue)
        self.lblAvgOrderValue = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblAvgOrderValue.setFont(font)
        self.lblAvgOrderValue.setObjectName("lblAvgOrderValue")
        self.statsLayout.addWidget(self.lblAvgOrderValue)
        self.verticalLayout.addWidget(self.groupBoxStats)
        self.groupBoxEmployeeSales = QtWidgets.QGroupBox(EmployeeSalesReport)
        self.groupBoxEmployeeSales.setObjectName("groupBoxEmployeeSales")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxEmployeeSales)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableEmployeeSales = QtWidgets.QTableWidget(self.groupBoxEmployeeSales)
        self.tableEmployeeSales.setAlternatingRowColors(True)
        self.tableEmployeeSales.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableEmployeeSales.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableEmployeeSales.setMinimumSize(QtCore.QSize(0, 300))
        self.tableEmployeeSales.setObjectName("tableEmployeeSales")
        self.tableEmployeeSales.setColumnCount(9)
        self.tableEmployeeSales.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEmployeeSales.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.tableEmployeeSales)
        self.tableButtonLayout = QtWidgets.QHBoxLayout()
        self.tableButtonLayout.setObjectName("tableButtonLayout")
        self.btnExport = QtWidgets.QPushButton(self.groupBoxEmployeeSales)
        self.btnExport.setObjectName("btnExport")
        self.tableButtonLayout.addWidget(self.btnExport)
        self.btnPrint = QtWidgets.QPushButton(self.groupBoxEmployeeSales)
        self.btnPrint.setObjectName("btnPrint")
        self.tableButtonLayout.addWidget(self.btnPrint)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tableButtonLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.tableButtonLayout)
        self.verticalLayout.addWidget(self.groupBoxEmployeeSales)
        self.groupBoxDetail = QtWidgets.QGroupBox(EmployeeSalesReport)
        self.groupBoxDetail.setObjectName("groupBoxDetail")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxDetail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableOrderDetails = QtWidgets.QTableWidget(self.groupBoxDetail)
        self.tableOrderDetails.setAlternatingRowColors(True)
        self.tableOrderDetails.setMinimumSize(QtCore.QSize(0, 200))
        self.tableOrderDetails.setObjectName("tableOrderDetails")
        self.tableOrderDetails.setColumnCount(6)
        self.tableOrderDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableOrderDetails)
        self.verticalLayout.addWidget(self.groupBoxDetail)

        self.retranslateUi(EmployeeSalesReport)

    def retranslateUi(self, EmployeeSalesReport):
        _translate = QtCore.QCoreApplication.translate
        EmployeeSalesReport.setWindowTitle(_translate("EmployeeSalesReport", "Doanh số nhân viên"))
        self.lblTitle.setText(_translate("EmployeeSalesReport", "💲 DOANH SỐ NHÂN VIÊN"))
        self.groupBoxFilter.setTitle(_translate("EmployeeSalesReport", "🔍 Bộ lọc báo cáo"))
        self.lblEmployee.setText(_translate("EmployeeSalesReport", "Nhân viên:"))
        self.cboEmployee.setItemText(0, _translate("EmployeeSalesReport", "Tất cả nhân viên"))
        self.cboEmployee.setItemText(1, _translate("EmployeeSalesReport", "Nguyễn Văn A"))
        self.cboEmployee.setItemText(2, _translate("EmployeeSalesReport", "Trần Thị B"))
        self.cboEmployee.setItemText(3, _translate("EmployeeSalesReport", "Lê Văn C"))
        self.cboEmployee.setItemText(4, _translate("EmployeeSalesReport", "Phạm Thị D"))
        self.lblDateRange.setText(_translate("EmployeeSalesReport", "Khoảng thời gian:"))
        self.dateFrom.setDisplayFormat(_translate("EmployeeSalesReport", "dd/MM/yyyy"))
        self.lblTo.setText(_translate("EmployeeSalesReport", "→"))
        self.dateTo.setDisplayFormat(_translate("EmployeeSalesReport", "dd/MM/yyyy"))
        self.lblQuickFilter.setText(_translate("EmployeeSalesReport", "Nhanh:"))
        self.btnToday.setText(_translate("EmployeeSalesReport", "Hôm nay"))
        self.btnWeek.setText(_translate("EmployeeSalesReport", "Tuần này"))
        self.btnMonth.setText(_translate("EmployeeSalesReport", "Tháng này"))
        self.btnQuarter.setText(_translate("EmployeeSalesReport", "Quý này"))
        self.btnYear.setText(_translate("EmployeeSalesReport", "Năm nay"))
        self.btnSearch.setText(_translate("EmployeeSalesReport", "🔍 Xem báo cáo"))
        self.btnReset.setText(_translate("EmployeeSalesReport", "🔄 Đặt lại"))
        self.groupBoxStats.setTitle(_translate("EmployeeSalesReport", "📊 Tổng hợp doanh số"))
        self.lblTotalOrders.setText(_translate("EmployeeSalesReport", "Tổng hóa đơn: 0"))
        self.lblTotalProductsSold.setText(_translate("EmployeeSalesReport", "Tổng SP bán: 0"))
        self.lblTotalRevenue.setText(_translate("EmployeeSalesReport", "Tổng doanh thu: 0 VNĐ"))
        self.lblAvgOrderValue.setText(_translate("EmployeeSalesReport", "TB hóa đơn: 0 VNĐ"))
        self.groupBoxEmployeeSales.setTitle(_translate("EmployeeSalesReport", "👨‍💼 Bảng doanh số theo nhân viên"))
        item = self.tableEmployeeSales.horizontalHeaderItem(0)
        item.setText(_translate("EmployeeSalesReport", "STT"))
        item = self.tableEmployeeSales.horizontalHeaderItem(1)
        item.setText(_translate("EmployeeSalesReport", "Mã NV"))
        item = self.tableEmployeeSales.horizontalHeaderItem(2)
        item.setText(_translate("EmployeeSalesReport", "Tên nhân viên"))
        item = self.tableEmployeeSales.horizontalHeaderItem(3)
        item.setText(_translate("EmployeeSalesReport", "Chức vụ"))
        item = self.tableEmployeeSales.horizontalHeaderItem(4)
        item.setText(_translate("EmployeeSalesReport", "Số hóa đơn"))
        item = self.tableEmployeeSales.horizontalHeaderItem(5)
        item.setText(_translate("EmployeeSalesReport", "Số SP bán"))
        item = self.tableEmployeeSales.horizontalHeaderItem(6)
        item.setText(_translate("EmployeeSalesReport", "Doanh thu"))
        item = self.tableEmployeeSales.horizontalHeaderItem(7)
        item.setText(_translate("EmployeeSalesReport", "Tỷ lệ %"))
        item = self.tableEmployeeSales.horizontalHeaderItem(8)
        item.setText(_translate("EmployeeSalesReport", "Hiệu suất"))
        self.btnExport.setText(_translate("EmployeeSalesReport", "📊 Xuất Excel"))
        self.btnPrint.setText(_translate("EmployeeSalesReport", "🖨️ In báo cáo"))
        self.groupBoxDetail.setTitle(_translate("EmployeeSalesReport", "📋 Chi tiết hóa đơn theo nhân viên"))
        item = self.tableOrderDetails.horizontalHeaderItem(0)
        item.setText(_translate("EmployeeSalesReport", "Mã HD"))
        item = self.tableOrderDetails.horizontalHeaderItem(1)
        item.setText(_translate("EmployeeSalesReport", "Ngày bán"))
        item = self.tableOrderDetails.horizontalHeaderItem(2)
        item.setText(_translate("EmployeeSalesReport", "Khách hàng"))
        item = self.tableOrderDetails.horizontalHeaderItem(3)
        item.setText(_translate("EmployeeSalesReport", "Sản phẩm"))
        item = self.tableOrderDetails.horizontalHeaderItem(4)
        item.setText(_translate("EmployeeSalesReport", "Số lượng"))
        item = self.tableOrderDetails.horizontalHeaderItem(5)
        item.setText(_translate("EmployeeSalesReport", "Thành tiền"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EmployeeSalesReport = QtWidgets.QWidget()
    ui = Ui_EmployeeSalesReport()
    ui.setupUi(EmployeeSalesReport)
    EmployeeSalesReport.show()
    sys.exit(app.exec_())
