# Form implementation generated from reading ui file 'ui\import_goods.ui'
#
# Created by: PyQt5 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImportGoods(object):
    def setupUi(self, ImportGoods):
        ImportGoods.setObjectName("ImportGoods")
        ImportGoods.resize(1300, 850)
        ImportGoods.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 10px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnAddProduct {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSaveImport {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClearCart {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearchProduct {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblTotalAmount {\n"
"        font-size: 20px;\n"
"        font-weight: bold;\n"
"        color: #e74c3c;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(ImportGoods)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=ImportGoods)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.infoLayout = QtWidgets.QHBoxLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.groupBoxImportInfo = QtWidgets.QGroupBox(parent=ImportGoods)
        self.groupBoxImportInfo.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBoxImportInfo.setObjectName("groupBoxImportInfo")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxImportInfo)
        self.gridLayout.setObjectName("gridLayout")
        self.lblImportCode = QtWidgets.QLabel(parent=self.groupBoxImportInfo)
        self.lblImportCode.setObjectName("lblImportCode")
        self.gridLayout.addWidget(self.lblImportCode, 0, 0, 1, 1)
        self.txtImportCode = QtWidgets.QLineEdit(parent=self.groupBoxImportInfo)
        self.txtImportCode.setReadOnly(True)
        self.txtImportCode.setStyleSheet("background-color: #f0f0f0;")
        self.txtImportCode.setObjectName("txtImportCode")
        self.gridLayout.addWidget(self.txtImportCode, 0, 1, 1, 1)
        self.lblImportDate = QtWidgets.QLabel(parent=self.groupBoxImportInfo)
        self.lblImportDate.setObjectName("lblImportDate")
        self.gridLayout.addWidget(self.lblImportDate, 0, 2, 1, 1)
        self.dateImportDate = QtWidgets.QDateEdit(parent=self.groupBoxImportInfo)
        self.dateImportDate.setCalendarPopup(True)
        self.dateImportDate.setDate(QtCore.QDate(2026, 4, 14))
        self.dateImportDate.setObjectName("dateImportDate")
        self.gridLayout.addWidget(self.dateImportDate, 0, 3, 1, 1)
        self.lblSupplier = QtWidgets.QLabel(parent=self.groupBoxImportInfo)
        self.lblSupplier.setObjectName("lblSupplier")
        self.gridLayout.addWidget(self.lblSupplier, 1, 0, 1, 1)
        self.cboSupplier = QtWidgets.QComboBox(parent=self.groupBoxImportInfo)
        self.cboSupplier.setMinimumSize(QtCore.QSize(200, 0))
        self.cboSupplier.setObjectName("cboSupplier")
        self.gridLayout.addWidget(self.cboSupplier, 1, 1, 1, 1)
        self.btnAddSupplier = QtWidgets.QPushButton(parent=self.groupBoxImportInfo)
        self.btnAddSupplier.setObjectName("btnAddSupplier")
        self.gridLayout.addWidget(self.btnAddSupplier, 1, 2, 1, 1)
        self.lblPaymentStatus = QtWidgets.QLabel(parent=self.groupBoxImportInfo)
        self.lblPaymentStatus.setObjectName("lblPaymentStatus")
        self.gridLayout.addWidget(self.lblPaymentStatus, 1, 3, 1, 1)
        self.cboPaymentStatus = QtWidgets.QComboBox(parent=self.groupBoxImportInfo)
        self.cboPaymentStatus.setObjectName("cboPaymentStatus")
        self.cboPaymentStatus.addItem("")
        self.cboPaymentStatus.addItem("")
        self.cboPaymentStatus.addItem("")
        self.gridLayout.addWidget(self.cboPaymentStatus, 1, 4, 1, 1)
        self.infoLayout.addWidget(self.groupBoxImportInfo)
        self.verticalLayout.addLayout(self.infoLayout)
        self.productSearchLayout = QtWidgets.QHBoxLayout()
        self.productSearchLayout.setObjectName("productSearchLayout")
        self.groupBoxAddProduct = QtWidgets.QGroupBox(parent=ImportGoods)
        self.groupBoxAddProduct.setObjectName("groupBoxAddProduct")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxAddProduct)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblProductSearch = QtWidgets.QLabel(parent=self.groupBoxAddProduct)
        self.lblProductSearch.setObjectName("lblProductSearch")
        self.horizontalLayout.addWidget(self.lblProductSearch)
        self.txtProductSearch = QtWidgets.QLineEdit(parent=self.groupBoxAddProduct)
        self.txtProductSearch.setMinimumSize(QtCore.QSize(300, 0))
        self.txtProductSearch.setObjectName("txtProductSearch")
        self.horizontalLayout.addWidget(self.txtProductSearch)
        self.btnSearchProduct = QtWidgets.QPushButton(parent=self.groupBoxAddProduct)
        self.btnSearchProduct.setObjectName("btnSearchProduct")
        self.horizontalLayout.addWidget(self.btnSearchProduct)
        self.lblQuantity = QtWidgets.QLabel(parent=self.groupBoxAddProduct)
        self.lblQuantity.setObjectName("lblQuantity")
        self.horizontalLayout.addWidget(self.lblQuantity)
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.groupBoxAddProduct)
        self.txtQuantity.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.txtQuantity.setObjectName("txtQuantity")
        self.horizontalLayout.addWidget(self.txtQuantity)
        self.lblPrice = QtWidgets.QLabel(parent=self.groupBoxAddProduct)
        self.lblPrice.setObjectName("lblPrice")
        self.horizontalLayout.addWidget(self.lblPrice)
        self.txtPrice = QtWidgets.QLineEdit(parent=self.groupBoxAddProduct)
        self.txtPrice.setObjectName("txtPrice")
        self.horizontalLayout.addWidget(self.txtPrice)
        self.btnAddProduct = QtWidgets.QPushButton(parent=self.groupBoxAddProduct)
        self.btnAddProduct.setObjectName("btnAddProduct")
        self.horizontalLayout.addWidget(self.btnAddProduct)
        self.productSearchLayout.addWidget(self.groupBoxAddProduct)
        self.verticalLayout.addLayout(self.productSearchLayout)
        self.tableImportItems = QtWidgets.QTableWidget(parent=ImportGoods)
        self.tableImportItems.setAlternatingRowColors(True)
        self.tableImportItems.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableImportItems.setObjectName("tableImportItems")
        self.tableImportItems.setColumnCount(7)
        self.tableImportItems.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableImportItems.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.tableImportItems)
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setObjectName("summaryLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.summaryLayout.addItem(spacerItem)
        self.lblTotalLabel = QtWidgets.QLabel(parent=ImportGoods)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalLabel.setFont(font)
        self.lblTotalLabel.setObjectName("lblTotalLabel")
        self.summaryLayout.addWidget(self.lblTotalLabel)
        self.lblTotalAmount = QtWidgets.QLabel(parent=ImportGoods)
        self.lblTotalAmount.setObjectName("lblTotalAmount")
        self.summaryLayout.addWidget(self.lblTotalAmount)
        self.verticalLayout.addLayout(self.summaryLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.btnSaveImport = QtWidgets.QPushButton(parent=ImportGoods)
        self.btnSaveImport.setMinimumSize(QtCore.QSize(150, 40))
        self.btnSaveImport.setObjectName("btnSaveImport")
        self.buttonLayout.addWidget(self.btnSaveImport)
        self.btnClearCart = QtWidgets.QPushButton(parent=ImportGoods)
        self.btnClearCart.setMinimumSize(QtCore.QSize(150, 40))
        self.btnClearCart.setObjectName("btnClearCart")
        self.buttonLayout.addWidget(self.btnClearCart)
        self.btnPrintImport = QtWidgets.QPushButton(parent=ImportGoods)
        self.btnPrintImport.setMinimumSize(QtCore.QSize(150, 40))
        self.btnPrintImport.setObjectName("btnPrintImport")
        self.buttonLayout.addWidget(self.btnPrintImport)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ImportGoods)

    def retranslateUi(self, ImportGoods):
        _translate = QtCore.QCoreApplication.translate
        ImportGoods.setWindowTitle(_translate("ImportGoods", "Nhập hàng"))
        self.lblTitle.setText(_translate("ImportGoods", "📥 NHẬP HÀNG"))
        self.groupBoxImportInfo.setTitle(_translate("ImportGoods", "Thông tin phiếu nhập"))
        self.lblImportCode.setText(_translate("ImportGoods", "Mã phiếu nhập:"))
        self.lblImportDate.setText(_translate("ImportGoods", "Ngày nhập:"))
        self.lblSupplier.setText(_translate("ImportGoods", "Nhà cung cấp:"))
        self.btnAddSupplier.setText(_translate("ImportGoods", "➕ Thêm NCC"))
        self.lblPaymentStatus.setText(_translate("ImportGoods", "Thanh toán:"))
        self.cboPaymentStatus.setItemText(0, _translate("ImportGoods", "Chưa thanh toán"))
        self.cboPaymentStatus.setItemText(1, _translate("ImportGoods", "Đã thanh toán"))
        self.cboPaymentStatus.setItemText(2, _translate("ImportGoods", "Thanh toán một phần"))
        self.groupBoxAddProduct.setTitle(_translate("ImportGoods", "Thêm sản phẩm"))
        self.lblProductSearch.setText(_translate("ImportGoods", "Tìm sản phẩm:"))
        self.txtProductSearch.setPlaceholderText(_translate("ImportGoods", "Nhập mã hoặc tên sản phẩm..."))
        self.btnSearchProduct.setText(_translate("ImportGoods", "🔍 Tìm"))
        self.lblQuantity.setText(_translate("ImportGoods", "Số lượng:"))
        self.txtQuantity.setText(_translate("ImportGoods", "1"))
        self.lblPrice.setText(_translate("ImportGoods", "Giá nhập:"))
        self.txtPrice.setPlaceholderText(_translate("ImportGoods", "VNĐ"))
        self.btnAddProduct.setText(_translate("ImportGoods", "➕ Thêm vào phiếu"))
        item = self.tableImportItems.horizontalHeaderItem(0)
        item.setText(_translate("ImportGoods", "ID"))
        item = self.tableImportItems.horizontalHeaderItem(1)
        item.setText(_translate("ImportGoods", "Mã SP"))
        item = self.tableImportItems.horizontalHeaderItem(2)
        item.setText(_translate("ImportGoods", "Tên sản phẩm"))
        item = self.tableImportItems.horizontalHeaderItem(3)
        item.setText(_translate("ImportGoods", "Số lượng"))
        item = self.tableImportItems.horizontalHeaderItem(4)
        item.setText(_translate("ImportGoods", "Giá nhập"))
        item = self.tableImportItems.horizontalHeaderItem(5)
        item.setText(_translate("ImportGoods", "Thành tiền"))
        item = self.tableImportItems.horizontalHeaderItem(6)
        item.setText(_translate("ImportGoods", "Thao tác"))
        self.lblTotalLabel.setText(_translate("ImportGoods", "Tổng tiền:"))
        self.lblTotalAmount.setText(_translate("ImportGoods", "0 VNĐ"))
        self.btnSaveImport.setText(_translate("ImportGoods", "💾 Lưu phiếu nhập"))
        self.btnClearCart.setText(_translate("ImportGoods", "🗑️ Xóa giỏ nhập"))
        self.btnPrintImport.setText(_translate("ImportGoods", "🖨️ In phiếu nhập"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportGoods = QtWidgets.QWidget()
    ui = Ui_ImportGoods()
    ui.setupUi(ImportGoods)
    ImportGoods.show()
    sys.exit(app.exec())
