# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\InventoryReport.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryReport(object):
    def setupUi(self, InventoryReport):
        InventoryReport.setObjectName("InventoryReport")
        InventoryReport.resize(1400, 900)
        InventoryReport.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 10px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        min-width: 120px;\n"
"        min-height: 40px;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnExport {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExport:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnPrint {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnPrint:hover {\n"
"        background-color: #8e44ad;\n"
"    }\n"
"    QPushButton#btnReset {\n"
"        background-color: #e67e22;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox {\n"
"        padding: 12px 16px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 16px;\n"
"        min-height: 35px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 26px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblTotalValue {\n"
"        font-size: 28px;\n"
"        font-weight: bold;\n"
"        color: #27ae60;\n"
"    }\n"
"    QProgressBar {\n"
"        border-radius: 6px;\n"
"        text-align: center;\n"
"        font-weight: bold;\n"
"        height: 25px;\n"
"    }\n"
"    QProgressBar::chunk {\n"
"        border-radius: 6px;\n"
"        background-color: #3498db;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(InventoryReport)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(InventoryReport)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxFilter = QtWidgets.QGroupBox(InventoryReport)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.lblCategory = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblCategory.setObjectName("lblCategory")
        self.gridLayout.addWidget(self.lblCategory, 0, 0, 1, 1)
        self.cboCategory = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboCategory.setObjectName("cboCategory")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.gridLayout.addWidget(self.cboCategory, 0, 1, 1, 1)
        self.lblBrand = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblBrand.setObjectName("lblBrand")
        self.gridLayout.addWidget(self.lblBrand, 0, 2, 1, 1)
        self.cboBrand = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboBrand.setObjectName("cboBrand")
        self.cboBrand.addItem("")
        self.cboBrand.addItem("")
        self.cboBrand.addItem("")
        self.cboBrand.addItem("")
        self.cboBrand.addItem("")
        self.cboBrand.addItem("")
        self.gridLayout.addWidget(self.cboBrand, 0, 3, 1, 1)
        self.lblStockStatus = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblStockStatus.setObjectName("lblStockStatus")
        self.gridLayout.addWidget(self.lblStockStatus, 1, 0, 1, 1)
        self.cboStockStatus = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboStockStatus.setObjectName("cboStockStatus")
        self.cboStockStatus.addItem("")
        self.cboStockStatus.addItem("")
        self.cboStockStatus.addItem("")
        self.cboStockStatus.addItem("")
        self.cboStockStatus.addItem("")
        self.gridLayout.addWidget(self.cboStockStatus, 1, 1, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnSearch.setObjectName("btnSearch")
        self.buttonLayout.addWidget(self.btnSearch)
        self.btnReset = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnReset.setObjectName("btnReset")
        self.buttonLayout.addWidget(self.btnReset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.btnExport = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnExport.setObjectName("btnExport")
        self.buttonLayout.addWidget(self.btnExport)
        self.btnPrint = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnPrint.setObjectName("btnPrint")
        self.buttonLayout.addWidget(self.btnPrint)
        self.gridLayout.addLayout(self.buttonLayout, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.groupBoxFilter)
        self.groupBoxStats = QtWidgets.QGroupBox(InventoryReport)
        self.groupBoxStats.setObjectName("groupBoxStats")
        self.statsLayout = QtWidgets.QHBoxLayout(self.groupBoxStats)
        self.statsLayout.setObjectName("statsLayout")
        self.lblTotalProducts = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalProducts.setFont(font)
        self.lblTotalProducts.setObjectName("lblTotalProducts")
        self.statsLayout.addWidget(self.lblTotalProducts)
        self.lblTotalQuantity = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalQuantity.setFont(font)
        self.lblTotalQuantity.setObjectName("lblTotalQuantity")
        self.statsLayout.addWidget(self.lblTotalQuantity)
        self.lblTotalValue = QtWidgets.QLabel(self.groupBoxStats)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalValue.setFont(font)
        self.lblTotalValue.setObjectName("lblTotalValue")
        self.statsLayout.addWidget(self.lblTotalValue)
        self.verticalLayout.addWidget(self.groupBoxStats)
        self.groupBoxReport = QtWidgets.QGroupBox(InventoryReport)
        self.groupBoxReport.setObjectName("groupBoxReport")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxReport)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableInventory = QtWidgets.QTableWidget(self.groupBoxReport)
        self.tableInventory.setAlternatingRowColors(True)
        self.tableInventory.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableInventory.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableInventory.setMinimumSize(QtCore.QSize(0, 400))
        self.tableInventory.setObjectName("tableInventory")
        self.tableInventory.setColumnCount(9)
        self.tableInventory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableInventory.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.tableInventory)
        self.verticalLayout.addWidget(self.groupBoxReport)
        self.groupBoxChart = QtWidgets.QGroupBox(InventoryReport)
        self.groupBoxChart.setObjectName("groupBoxChart")
        self.chartLayout = QtWidgets.QVBoxLayout(self.groupBoxChart)
        self.chartLayout.setObjectName("chartLayout")
        self.tableTopInventory = QtWidgets.QTableWidget(self.groupBoxChart)
        self.tableTopInventory.setMinimumSize(QtCore.QSize(0, 150))
        self.tableTopInventory.setAlternatingRowColors(True)
        self.tableTopInventory.setObjectName("tableTopInventory")
        self.tableTopInventory.setColumnCount(4)
        self.tableTopInventory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopInventory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopInventory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopInventory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTopInventory.setHorizontalHeaderItem(3, item)
        self.chartLayout.addWidget(self.tableTopInventory)
        self.verticalLayout.addWidget(self.groupBoxChart)

        self.retranslateUi(InventoryReport)

    def retranslateUi(self, InventoryReport):
        _translate = QtCore.QCoreApplication.translate
        InventoryReport.setWindowTitle(_translate("InventoryReport", "Báo cáo tồn kho"))
        self.lblTitle.setText(_translate("InventoryReport", "📦 BÁO CÁO TỒN KHO"))
        self.groupBoxFilter.setTitle(_translate("InventoryReport", "🔍 Bộ lọc báo cáo"))
        self.lblCategory.setText(_translate("InventoryReport", "Danh mục:"))
        self.cboCategory.setItemText(0, _translate("InventoryReport", "Tất cả danh mục"))
        self.cboCategory.setItemText(1, _translate("InventoryReport", "Tủ lạnh"))
        self.cboCategory.setItemText(2, _translate("InventoryReport", "Máy giặt"))
        self.cboCategory.setItemText(3, _translate("InventoryReport", "TV"))
        self.cboCategory.setItemText(4, _translate("InventoryReport", "Điều hòa"))
        self.cboCategory.setItemText(5, _translate("InventoryReport", "Bếp từ"))
        self.cboCategory.setItemText(6, _translate("InventoryReport", "Quạt"))
        self.lblBrand.setText(_translate("InventoryReport", "Thương hiệu:"))
        self.cboBrand.setItemText(0, _translate("InventoryReport", "Tất cả"))
        self.cboBrand.setItemText(1, _translate("InventoryReport", "Samsung"))
        self.cboBrand.setItemText(2, _translate("InventoryReport", "Panasonic"))
        self.cboBrand.setItemText(3, _translate("InventoryReport", "Sony"))
        self.cboBrand.setItemText(4, _translate("InventoryReport", "LG"))
        self.cboBrand.setItemText(5, _translate("InventoryReport", "Toshiba"))
        self.lblStockStatus.setText(_translate("InventoryReport", "Trạng thái tồn:"))
        self.cboStockStatus.setItemText(0, _translate("InventoryReport", "Tất cả"))
        self.cboStockStatus.setItemText(1, _translate("InventoryReport", "Còn hàng (>0)"))
        self.cboStockStatus.setItemText(2, _translate("InventoryReport", "Sắp hết (≤10)"))
        self.cboStockStatus.setItemText(3, _translate("InventoryReport", "Hết hàng (=0)"))
        self.cboStockStatus.setItemText(4, _translate("InventoryReport", "Tồn nhiều (>50)"))
        self.btnSearch.setText(_translate("InventoryReport", "🔍 Xem báo cáo"))
        self.btnReset.setText(_translate("InventoryReport", "🔄 Đặt lại"))
        self.btnExport.setText(_translate("InventoryReport", "📊 Xuất Excel"))
        self.btnPrint.setText(_translate("InventoryReport", "🖨️ In báo cáo"))
        self.groupBoxStats.setTitle(_translate("InventoryReport", "📊 Thống kê nhanh"))
        self.lblTotalProducts.setText(_translate("InventoryReport", "Tổng sản phẩm: 0"))
        self.lblTotalQuantity.setText(_translate("InventoryReport", "Tổng tồn kho: 0"))
        self.lblTotalValue.setText(_translate("InventoryReport", "Tổng giá trị: 0 VNĐ"))
        self.groupBoxReport.setTitle(_translate("InventoryReport", "📋 Chi tiết tồn kho"))
        item = self.tableInventory.horizontalHeaderItem(0)
        item.setText(_translate("InventoryReport", "Mã SP"))
        item = self.tableInventory.horizontalHeaderItem(1)
        item.setText(_translate("InventoryReport", "Tên sản phẩm"))
        item = self.tableInventory.horizontalHeaderItem(2)
        item.setText(_translate("InventoryReport", "Danh mục"))
        item = self.tableInventory.horizontalHeaderItem(3)
        item.setText(_translate("InventoryReport", "Thương hiệu"))
        item = self.tableInventory.horizontalHeaderItem(4)
        item.setText(_translate("InventoryReport", "Giá nhập"))
        item = self.tableInventory.horizontalHeaderItem(5)
        item.setText(_translate("InventoryReport", "Giá bán"))
        item = self.tableInventory.horizontalHeaderItem(6)
        item.setText(_translate("InventoryReport", "Tồn kho"))
        item = self.tableInventory.horizontalHeaderItem(7)
        item.setText(_translate("InventoryReport", "Giá trị tồn"))
        item = self.tableInventory.horizontalHeaderItem(8)
        item.setText(_translate("InventoryReport", "Tỷ lệ %"))
        self.groupBoxChart.setTitle(_translate("InventoryReport", "📈 Top sản phẩm tồn kho nhiều nhất"))
        item = self.tableTopInventory.horizontalHeaderItem(0)
        item.setText(_translate("InventoryReport", "STT"))
        item = self.tableTopInventory.horizontalHeaderItem(1)
        item.setText(_translate("InventoryReport", "Sản phẩm"))
        item = self.tableTopInventory.horizontalHeaderItem(2)
        item.setText(_translate("InventoryReport", "Số lượng tồn"))
        item = self.tableTopInventory.horizontalHeaderItem(3)
        item.setText(_translate("InventoryReport", "Giá trị tồn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InventoryReport = QtWidgets.QWidget()
    ui = Ui_InventoryReport()
    ui.setupUi(InventoryReport)
    InventoryReport.show()
    sys.exit(app.exec_())
