# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(450, 580)
        LoginDialog.setStyleSheet("\n"
"    QDialog {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #667eea, stop:1 #764ba2);\n"
"    }\n"
"    QFrame#frameLogin {\n"
"        background-color: white;\n"
"        border-radius: 20px;\n"
"        padding: 30px;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 28px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        font-size: 16px;\n"
"        color: #7f8c8d;\n"
"        margin-bottom: 20px;\n"
"    }\n"
"    QLineEdit {\n"
"        padding: 12px;\n"
"        border: 2px solid #e0e0e0;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"        background-color: #f8f9fa;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border-color: #667eea;\n"
"        background-color: white;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 10px;\n"
"        padding: 12px;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnLogin {\n"
"        background-color: #667eea;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnLogin:hover {\n"
"        background-color: #5a67d8;\n"
"    }\n"
"    QPushButton#btnRegister {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnRegister:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnExit {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExit:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QCheckBox {\n"
"        color: #555;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLogin = QtWidgets.QFrame(LoginDialog)
        self.frameLogin.setObjectName("frameLogin")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameLogin)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTitle = QtWidgets.QLabel(self.frameLogin)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(self.frameLogin)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_2.addWidget(self.lblSubtitle)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lblUsername = QtWidgets.QLabel(self.frameLogin)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblUsername.setFont(font)
        self.lblUsername.setObjectName("lblUsername")
        self.verticalLayout_2.addWidget(self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(self.frameLogin)
        self.txtUsername.setObjectName("txtUsername")
        self.verticalLayout_2.addWidget(self.txtUsername)
        self.lblPassword = QtWidgets.QLabel(self.frameLogin)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPassword.setFont(font)
        self.lblPassword.setObjectName("lblPassword")
        self.verticalLayout_2.addWidget(self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.frameLogin)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.verticalLayout_2.addWidget(self.txtPassword)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chkRemember = QtWidgets.QCheckBox(self.frameLogin)
        self.chkRemember.setObjectName("chkRemember")
        self.horizontalLayout_2.addWidget(self.chkRemember)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lblForgotPassword = QtWidgets.QLabel(self.frameLogin)
        self.lblForgotPassword.setStyleSheet("color: #667eea; text-decoration: underline;")
        self.lblForgotPassword.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lblForgotPassword.setObjectName("lblForgotPassword")
        self.horizontalLayout_2.addWidget(self.lblForgotPassword)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLogin = QtWidgets.QPushButton(self.frameLogin)
        self.btnLogin.setDefault(True)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        self.btnRegister = QtWidgets.QPushButton(self.frameLogin)
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout.addWidget(self.btnRegister)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.exitLayout = QtWidgets.QHBoxLayout()
        self.exitLayout.setObjectName("exitLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exitLayout.addItem(spacerItem3)
        self.btnExit = QtWidgets.QPushButton(self.frameLogin)
        self.btnExit.setObjectName("btnExit")
        self.exitLayout.addWidget(self.btnExit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.exitLayout.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.exitLayout)
        self.verticalLayout.addWidget(self.frameLogin)

        self.retranslateUi(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Đăng nhập - Quản lý đồ gia dụng"))
        self.lblTitle.setText(_translate("LoginDialog", "🏠 QUẢN LÝ ĐỒ GIA DỤNG"))
        self.lblSubtitle.setText(_translate("LoginDialog", "Hệ thống quản lý bán hàng chuyên nghiệp"))
        self.lblUsername.setText(_translate("LoginDialog", "👤 Tên đăng nhập"))
        self.txtUsername.setPlaceholderText(_translate("LoginDialog", "Nhập tên đăng nhập"))
        self.lblPassword.setText(_translate("LoginDialog", "🔒 Mật khẩu"))
        self.txtPassword.setPlaceholderText(_translate("LoginDialog", "Nhập mật khẩu"))
        self.chkRemember.setText(_translate("LoginDialog", "Ghi nhớ đăng nhập"))
        self.lblForgotPassword.setText(_translate("LoginDialog", "Quên mật khẩu?"))
        self.btnLogin.setText(_translate("LoginDialog", "Đăng nhập"))
        self.btnRegister.setText(_translate("LoginDialog", "📝 Đăng ký"))
        self.btnExit.setText(_translate("LoginDialog", "Thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginDialog = QtWidgets.QDialog()
    ui = Ui_LoginDialog()
    ui.setupUi(LoginDialog)
    LoginDialog.show()
    sys.exit(app.exec_())
