# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 850)
        MainWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    \n"
"    /* ===== MENU BAR ===== */\n"
"    QMenuBar {\n"
"        background-color: #2c3e50;\n"
"        color: white;\n"
"        padding: 12px 8px;\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"        min-height: 50px;\n"
"    }\n"
"    \n"
"    QMenuBar::item {\n"
"        padding: 10px 22px;\n"
"        margin: 0 5px;\n"
"        border-radius: 6px;\n"
"        font-size: 17px;\n"
"    }\n"
"    \n"
"    QMenuBar::item:selected {\n"
"        background-color: #3498db;\n"
"    }\n"
"    \n"
"    QMenuBar::item:pressed {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    \n"
"    /* ===== MENU DROP DOWN - CHỮ TO HƠN ===== */\n"
"    QMenu {\n"
"        background-color: white;\n"
"        color: #2c3e50;\n"
"        border: 1px solid #ddd;\n"
"        border-radius: 10px;\n"
"        padding: 10px;\n"
"        font-size: 16px;\n"
"    }\n"
"    \n"
"    QMenu::item {\n"
"        padding: 12px 50px;\n"
"        margin: 4px 8px;\n"
"        border-radius: 6px;\n"
"        font-size: 16px;\n"
"    }\n"
"    \n"
"    QMenu::item:selected {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    \n"
"    QMenu::separator {\n"
"        height: 2px;\n"
"        background-color: #ddd;\n"
"        margin: 8px 12px;\n"
"    }\n"
"    \n"
"    /* ===== STATUS BAR ===== */\n"
"    QStatusBar {\n"
"        background-color: #34495e;\n"
"        color: white;\n"
"        font-size: 13px;\n"
"        padding: 8px;\n"
"    }\n"
"    \n"
"    QStatusBar::item {\n"
"        border: none;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 55))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuManage = QtWidgets.QMenu(self.menubar)
        self.menuManage.setObjectName("menuManage")
        self.menuSale = QtWidgets.QMenu(self.menubar)
        self.menuSale.setObjectName("menuSale")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChangePassword = QtWidgets.QAction(MainWindow)
        self.actionChangePassword.setObjectName("actionChangePassword")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProducts = QtWidgets.QAction(MainWindow)
        self.actionProducts.setObjectName("actionProducts")
        self.actionCustomers = QtWidgets.QAction(MainWindow)
        self.actionCustomers.setObjectName("actionCustomers")
        self.actionEmployees = QtWidgets.QAction(MainWindow)
        self.actionEmployees.setObjectName("actionEmployees")
        self.actionNewOrder = QtWidgets.QAction(MainWindow)
        self.actionNewOrder.setObjectName("actionNewOrder")
        self.actionOrderManagement = QtWidgets.QAction(MainWindow)
        self.actionOrderManagement.setObjectName("actionOrderManagement")
        self.actionWarranty = QtWidgets.QAction(MainWindow)
        self.actionWarranty.setObjectName("actionWarranty")
        self.actionImportGoods = QtWidgets.QAction(MainWindow)
        self.actionImportGoods.setObjectName("actionImportGoods")
        self.actionSupplierManagement = QtWidgets.QAction(MainWindow)
        self.actionSupplierManagement.setObjectName("actionSupplierManagement")
        self.actionRevenueReport = QtWidgets.QAction(MainWindow)
        self.actionRevenueReport.setObjectName("actionRevenueReport")
        self.actionInventoryReport = QtWidgets.QAction(MainWindow)
        self.actionInventoryReport.setObjectName("actionInventoryReport")
        self.actionEmployeeSalesReport = QtWidgets.QAction(MainWindow)
        self.actionEmployeeSalesReport.setObjectName("actionEmployeeSalesReport")
        self.actionSalaryReport = QtWidgets.QAction(MainWindow)
        self.actionSalaryReport.setObjectName("actionSalaryReport")
        self.actionShiftSchedule = QtWidgets.QAction(MainWindow)
        self.actionShiftSchedule.setObjectName("actionShiftSchedule")
        self.actionAttendance = QtWidgets.QAction(MainWindow)
        self.actionAttendance.setObjectName("actionAttendance")
        self.actionSalaryCalculation = QtWidgets.QAction(MainWindow)
        self.actionSalaryCalculation.setObjectName("actionSalaryCalculation")
        self.actionBackup = QtWidgets.QAction(MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtWidgets.QAction(MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionGuide = QtWidgets.QAction(MainWindow)
        self.actionGuide.setObjectName("actionGuide")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menuFile.addAction(self.actionChangePassword)
        self.menuFile.addAction(self.actionLogout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuManage.addAction(self.actionProducts)
        self.menuManage.addAction(self.actionCustomers)
        self.menuManage.addAction(self.actionEmployees)
        self.menuSale.addAction(self.actionNewOrder)
        self.menuSale.addAction(self.actionOrderManagement)
        self.menuSale.addAction(self.actionWarranty)
        self.menuImport.addAction(self.actionImportGoods)
        self.menuImport.addAction(self.actionSupplierManagement)
        self.menuReport.addAction(self.actionRevenueReport)
        self.menuReport.addAction(self.actionInventoryReport)
        self.menuReport.addAction(self.actionEmployeeSalesReport)
        self.menuReport.addAction(self.actionSalaryReport)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuManage.menuAction())
        self.menubar.addAction(self.menuSale.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phần mềm quản lý kinh doanh đồ gia dụng"))
        self.menuFile.setTitle(_translate("MainWindow", "📁 File"))
        self.menuManage.setTitle(_translate("MainWindow", "📦 Quản lý"))
        self.menuSale.setTitle(_translate("MainWindow", "🧾 Bán hàng"))
        self.menuImport.setTitle(_translate("MainWindow", "📥 Nhập hàng"))
        self.menuReport.setTitle(_translate("MainWindow", "📊 Báo cáo"))
        self.actionChangePassword.setText(_translate("MainWindow", "🔐 Đổi mật khẩu"))
        self.actionLogout.setText(_translate("MainWindow", "🚪 Đăng xuất"))
        self.actionExit.setText(_translate("MainWindow", "❌ Thoát"))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+F4"))
        self.actionProducts.setText(_translate("MainWindow", "📦 Sản phẩm"))
        self.actionProducts.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionCustomers.setText(_translate("MainWindow", "👥 Khách hàng"))
        self.actionCustomers.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionEmployees.setText(_translate("MainWindow", "👨‍💼 Nhân viên"))
        self.actionEmployees.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionNewOrder.setText(_translate("MainWindow", "🛒 Hóa đơn mới"))
        self.actionNewOrder.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOrderManagement.setText(_translate("MainWindow", "📋 Quản lý hóa đơn"))
        self.actionWarranty.setText(_translate("MainWindow", "🔧 Quản lý bảo hành"))
        self.actionImportGoods.setText(_translate("MainWindow", "📥 Nhập kho"))
        self.actionSupplierManagement.setText(_translate("MainWindow", "🏭 Quản lý nhà cung cấp"))
        self.actionRevenueReport.setText(_translate("MainWindow", "💰 Báo cáo doanh thu"))
        self.actionInventoryReport.setText(_translate("MainWindow", "📦 Báo cáo tồn kho"))
        self.actionEmployeeSalesReport.setText(_translate("MainWindow", "👨‍💼 Doanh số nhân viên"))
        self.actionSalaryReport.setText(_translate("MainWindow", "💵 Báo cáo lương"))
        self.actionShiftSchedule.setText(_translate("MainWindow", "📅 Phân ca làm việc"))
        self.actionAttendance.setText(_translate("MainWindow", "⏰ Chấm công"))
        self.actionAttendance.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionSalaryCalculation.setText(_translate("MainWindow", "💰 Tính lương"))
        self.actionBackup.setText(_translate("MainWindow", "💾 Sao lưu dữ liệu"))
        self.actionRestore.setText(_translate("MainWindow", "🔄 Phục hồi dữ liệu"))
        self.actionSettings.setText(_translate("MainWindow", "⚙️ Cài đặt"))
        self.actionLogs.setText(_translate("MainWindow", "📝 Nhật ký hệ thống"))
        self.actionGuide.setText(_translate("MainWindow", "📖 Hướng dẫn sử dụng"))
        self.actionGuide.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "ℹ️ Giới thiệu"))
        self.actionHome.setText(_translate("MainWindow", "🏠 Trang chủ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
