# Form implementation generated from reading ui file 'ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 850)
        MainWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QMenuBar {\n"
"        background-color: #2c3e50;\n"
"        color: white;\n"
"        padding: 5px;\n"
"    }\n"
"    QMenuBar::item:selected {\n"
"        background-color: #34495e;\n"
"    }\n"
"    QMenu {\n"
"        background-color: white;\n"
"        color: #333;\n"
"    }\n"
"    QToolBar {\n"
"        background-color: white;\n"
"        border: none;\n"
"        spacing: 10px;\n"
"        padding: 10px;\n"
"    }\n"
"    QToolButton {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        border-radius: 8px;\n"
"        padding: 8px 15px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QToolButton:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QStatusBar {\n"
"        background-color: #34495e;\n"
"        color: white;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuManage = QtWidgets.QMenu(parent=self.menubar)
        self.menuManage.setObjectName("menuManage")
        self.menuSale = QtWidgets.QMenu(parent=self.menubar)
        self.menuSale.setObjectName("menuSale")
        self.menuImport = QtWidgets.QMenu(parent=self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuReport = QtWidgets.QMenu(parent=self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuSystem = QtWidgets.QMenu(parent=self.menubar)
        self.menuSystem.setObjectName("menuSystem")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionChangePassword = QtWidgets.QAction(parent=MainWindow)
        self.actionChangePassword.setObjectName("actionChangePassword")
        self.actionLogout = QtWidgets.QAction(parent=MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProducts = QtWidgets.QAction(parent=MainWindow)
        self.actionProducts.setObjectName("actionProducts")
        self.actionCustomers = QtWidgets.QAction(parent=MainWindow)
        self.actionCustomers.setObjectName("actionCustomers")
        self.actionEmployees = QtWidgets.QAction(parent=MainWindow)
        self.actionEmployees.setObjectName("actionEmployees")
        self.actionSuppliers = QtWidgets.QAction(parent=MainWindow)
        self.actionSuppliers.setObjectName("actionSuppliers")
        self.actionNewOrder = QtWidgets.QAction(parent=MainWindow)
        self.actionNewOrder.setObjectName("actionNewOrder")
        self.actionOrderManagement = QtWidgets.QAction(parent=MainWindow)
        self.actionOrderManagement.setObjectName("actionOrderManagement")
        self.actionWarranty = QtWidgets.QAction(parent=MainWindow)
        self.actionWarranty.setObjectName("actionWarranty")
        self.actionImportGoods = QtWidgets.QAction(parent=MainWindow)
        self.actionImportGoods.setObjectName("actionImportGoods")
        self.actionSupplierManagement = QtWidgets.QAction(parent=MainWindow)
        self.actionSupplierManagement.setObjectName("actionSupplierManagement")
        self.actionRevenueReport = QtWidgets.QAction(parent=MainWindow)
        self.actionRevenueReport.setObjectName("actionRevenueReport")
        self.actionInventoryReport = QtWidgets.QAction(parent=MainWindow)
        self.actionInventoryReport.setObjectName("actionInventoryReport")
        self.actionEmployeeSalesReport = QtWidgets.QAction(parent=MainWindow)
        self.actionEmployeeSalesReport.setObjectName("actionEmployeeSalesReport")
        self.actionSalaryReport = QtWidgets.QAction(parent=MainWindow)
        self.actionSalaryReport.setObjectName("actionSalaryReport")
        self.actionBackup = QtWidgets.QAction(parent=MainWindow)
        self.actionBackup.setObjectName("actionBackup")
        self.actionRestore = QtWidgets.QAction(parent=MainWindow)
        self.actionRestore.setObjectName("actionRestore")
        self.actionSettings = QtWidgets.QAction(parent=MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionLogs = QtWidgets.QAction(parent=MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionGuide = QtWidgets.QAction(parent=MainWindow)
        self.actionGuide.setObjectName("actionGuide")
        self.actionAbout = QtWidgets.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHome = QtWidgets.QAction(parent=MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menuFile.addAction(self.actionChangePassword)
        self.menuFile.addAction(self.actionLogout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuManage.addAction(self.actionProducts)
        self.menuManage.addAction(self.actionCustomers)
        self.menuManage.addAction(self.actionEmployees)
        self.menuManage.addAction(self.actionSuppliers)
        self.menuSale.addAction(self.actionNewOrder)
        self.menuSale.addAction(self.actionOrderManagement)
        self.menuSale.addAction(self.actionWarranty)
        self.menuImport.addAction(self.actionImportGoods)
        self.menuImport.addAction(self.actionSupplierManagement)
        self.menuReport.addAction(self.actionRevenueReport)
        self.menuReport.addAction(self.actionInventoryReport)
        self.menuReport.addAction(self.actionEmployeeSalesReport)
        self.menuReport.addAction(self.actionSalaryReport)
        self.menuSystem.addAction(self.actionBackup)
        self.menuSystem.addAction(self.actionRestore)
        self.menuSystem.addAction(self.actionSettings)
        self.menuSystem.addAction(self.actionLogs)
        self.menuHelp.addAction(self.actionGuide)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuManage.menuAction())
        self.menubar.addAction(self.menuSale.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionHome)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionProducts)
        self.toolBar.addAction(self.actionCustomers)
        self.toolBar.addAction(self.actionEmployees)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionNewOrder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRevenueReport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSettings)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phần mềm quản lý kinh doanh đồ gia dụng"))
        self.menuFile.setTitle(_translate("MainWindow", "📁 File"))
        self.menuManage.setTitle(_translate("MainWindow", "📦 Quản lý"))
        self.menuSale.setTitle(_translate("MainWindow", "🧾 Bán hàng"))
        self.menuImport.setTitle(_translate("MainWindow", "📥 Nhập hàng"))
        self.menuReport.setTitle(_translate("MainWindow", "📊 Báo cáo"))
        self.menuSystem.setTitle(_translate("MainWindow", "⚙️ Hệ thống"))
        self.menuHelp.setTitle(_translate("MainWindow", "❓ Trợ giúp"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionChangePassword.setText(_translate("MainWindow", "🔐 Đổi mật khẩu"))
        self.actionLogout.setText(_translate("MainWindow", "🚪 Đăng xuất"))
        self.actionExit.setText(_translate("MainWindow", "❌ Thoát"))
        self.actionProducts.setText(_translate("MainWindow", "📦 Sản phẩm"))
        self.actionCustomers.setText(_translate("MainWindow", "👥 Khách hàng"))
        self.actionEmployees.setText(_translate("MainWindow", "👨‍💼 Nhân viên"))
        self.actionSuppliers.setText(_translate("MainWindow", "🏭 Nhà cung cấp"))
        self.actionNewOrder.setText(_translate("MainWindow", "🛒 Hóa đơn mới"))
        self.actionOrderManagement.setText(_translate("MainWindow", "📋 Quản lý hóa đơn"))
        self.actionWarranty.setText(_translate("MainWindow", "🔧 Quản lý bảo hành"))
        self.actionImportGoods.setText(_translate("MainWindow", "📦 Nhập kho"))
        self.actionSupplierManagement.setText(_translate("MainWindow", "🏭 Quản lý nhà cung cấp"))
        self.actionRevenueReport.setText(_translate("MainWindow", "💰 Báo cáo doanh thu"))
        self.actionInventoryReport.setText(_translate("MainWindow", "📊 Báo cáo tồn kho"))
        self.actionEmployeeSalesReport.setText(_translate("MainWindow", "👨‍💼 Doanh số nhân viên"))
        self.actionSalaryReport.setText(_translate("MainWindow", "💵 Báo cáo lương"))
        self.actionBackup.setText(_translate("MainWindow", "💾 Sao lưu dữ liệu"))
        self.actionRestore.setText(_translate("MainWindow", "🔄 Phục hồi dữ liệu"))
        self.actionSettings.setText(_translate("MainWindow", "⚙️ Cài đặt"))
        self.actionLogs.setText(_translate("MainWindow", "📝 Nhật ký hệ thống"))
        self.actionGuide.setText(_translate("MainWindow", "📖 Hướng dẫn sử dụng"))
        self.actionAbout.setText(_translate("MainWindow", "ℹ️ Giới thiệu"))
        self.actionHome.setText(_translate("MainWindow", "🏠 Trang chủ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
