# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\OrderManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderManagement(object):
    def setupUi(self, OrderManagement):
        OrderManagement.setObjectName("OrderManagement")
        OrderManagement.resize(1400, 900)
        OrderManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 10px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        min-width: 120px;\n"
"        min-height: 40px;\n"
"    }\n"
"    QPushButton#btnViewDetail {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnViewDetail:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnPrint {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnPrint:hover {\n"
"        background-color: #8e44ad;\n"
"    }\n"
"    QPushButton#btnCancel {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnCancel:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnExport {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExport:hover {\n"
"        background-color: #e67e22;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit {\n"
"        padding: 12px 16px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 16px;\n"
"        min-height: 35px;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus {\n"
"        border-color: #3498db;\n"
"        border: 2px solid #3498db;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 26px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 1px solid #ddd;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"    }\n"
"    QTabBar::tab {\n"
"        padding: 12px 24px;\n"
"        font-size: 15px;\n"
"        font-weight: bold;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(OrderManagement)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxFilter = QtWidgets.QGroupBox(OrderManagement)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.lblOrderCode = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblOrderCode.setObjectName("lblOrderCode")
        self.gridLayout.addWidget(self.lblOrderCode, 0, 0, 1, 1)
        self.txtOrderCode = QtWidgets.QLineEdit(self.groupBoxFilter)
        self.txtOrderCode.setObjectName("txtOrderCode")
        self.gridLayout.addWidget(self.txtOrderCode, 0, 1, 1, 1)
        self.lblCustomer = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblCustomer.setObjectName("lblCustomer")
        self.gridLayout.addWidget(self.lblCustomer, 0, 2, 1, 1)
        self.txtCustomer = QtWidgets.QLineEdit(self.groupBoxFilter)
        self.txtCustomer.setObjectName("txtCustomer")
        self.gridLayout.addWidget(self.txtCustomer, 0, 3, 1, 1)
        self.lblStatus = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout.addWidget(self.lblStatus, 1, 0, 1, 1)
        self.cboStatus = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.gridLayout.addWidget(self.cboStatus, 1, 1, 1, 1)
        self.lblDateRange = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblDateRange.setObjectName("lblDateRange")
        self.gridLayout.addWidget(self.lblDateRange, 1, 2, 1, 1)
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setObjectName("dateLayout")
        self.dateFrom = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.dateLayout.addWidget(self.dateFrom)
        self.lblTo = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblTo.setObjectName("lblTo")
        self.dateLayout.addWidget(self.lblTo)
        self.dateTo = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.dateLayout.addWidget(self.dateTo)
        self.gridLayout.addLayout(self.dateLayout, 1, 3, 1, 1)
        self.buttonFilterLayout = QtWidgets.QHBoxLayout()
        self.buttonFilterLayout.setObjectName("buttonFilterLayout")
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnSearch.setObjectName("btnSearch")
        self.buttonFilterLayout.addWidget(self.btnSearch)
        self.btnReset = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnReset.setObjectName("btnReset")
        self.buttonFilterLayout.addWidget(self.btnReset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonFilterLayout.addItem(spacerItem)
        self.btnExport = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnExport.setObjectName("btnExport")
        self.buttonFilterLayout.addWidget(self.btnExport)
        self.gridLayout.addLayout(self.buttonFilterLayout, 2, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBoxFilter)
        self.groupBoxOrderList = QtWidgets.QGroupBox(OrderManagement)
        self.groupBoxOrderList.setObjectName("groupBoxOrderList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxOrderList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableOrders = QtWidgets.QTableWidget(self.groupBoxOrderList)
        self.tableOrders.setAlternatingRowColors(True)
        self.tableOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableOrders.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableOrders.setMinimumSize(QtCore.QSize(0, 350))
        self.tableOrders.setObjectName("tableOrders")
        self.tableOrders.setColumnCount(9)
        self.tableOrders.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrders.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.tableOrders)
        self.verticalLayout.addWidget(self.groupBoxOrderList)
        self.groupBoxOrderDetail = QtWidgets.QGroupBox(OrderManagement)
        self.groupBoxOrderDetail.setObjectName("groupBoxOrderDetail")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxOrderDetail)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableOrderDetails = QtWidgets.QTableWidget(self.groupBoxOrderDetail)
        self.tableOrderDetails.setAlternatingRowColors(True)
        self.tableOrderDetails.setMinimumSize(QtCore.QSize(0, 200))
        self.tableOrderDetails.setObjectName("tableOrderDetails")
        self.tableOrderDetails.setColumnCount(5)
        self.tableOrderDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOrderDetails.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableOrderDetails)
        self.detailButtonLayout = QtWidgets.QHBoxLayout()
        self.detailButtonLayout.setObjectName("detailButtonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.detailButtonLayout.addItem(spacerItem1)
        self.btnViewDetail = QtWidgets.QPushButton(self.groupBoxOrderDetail)
        self.btnViewDetail.setObjectName("btnViewDetail")
        self.detailButtonLayout.addWidget(self.btnViewDetail)
        self.btnPrint = QtWidgets.QPushButton(self.groupBoxOrderDetail)
        self.btnPrint.setObjectName("btnPrint")
        self.detailButtonLayout.addWidget(self.btnPrint)
        self.btnCancel = QtWidgets.QPushButton(self.groupBoxOrderDetail)
        self.btnCancel.setObjectName("btnCancel")
        self.detailButtonLayout.addWidget(self.btnCancel)
        self.verticalLayout_3.addLayout(self.detailButtonLayout)
        self.verticalLayout.addWidget(self.groupBoxOrderDetail)

        self.retranslateUi(OrderManagement)

    def retranslateUi(self, OrderManagement):
        _translate = QtCore.QCoreApplication.translate
        OrderManagement.setWindowTitle(_translate("OrderManagement", "Quản lý hóa đơn"))
        self.lblTitle.setText(_translate("OrderManagement", "📋 QUẢN LÝ HÓA ĐƠN"))
        self.groupBoxFilter.setTitle(_translate("OrderManagement", "🔍 Tìm kiếm & Bộ lọc"))
        self.lblOrderCode.setText(_translate("OrderManagement", "Mã hóa đơn:"))
        self.txtOrderCode.setPlaceholderText(_translate("OrderManagement", "Nhập mã hóa đơn"))
        self.lblCustomer.setText(_translate("OrderManagement", "Khách hàng:"))
        self.txtCustomer.setPlaceholderText(_translate("OrderManagement", "Tên hoặc SĐT khách hàng"))
        self.lblStatus.setText(_translate("OrderManagement", "Trạng thái:"))
        self.cboStatus.setItemText(0, _translate("OrderManagement", "Tất cả"))
        self.cboStatus.setItemText(1, _translate("OrderManagement", "Đã thanh toán"))
        self.cboStatus.setItemText(2, _translate("OrderManagement", "Chưa thanh toán"))
        self.cboStatus.setItemText(3, _translate("OrderManagement", "Đã hủy"))
        self.lblDateRange.setText(_translate("OrderManagement", "Ngày tạo:"))
        self.dateFrom.setDisplayFormat(_translate("OrderManagement", "dd/MM/yyyy"))
        self.lblTo.setText(_translate("OrderManagement", "→"))
        self.dateTo.setDisplayFormat(_translate("OrderManagement", "dd/MM/yyyy"))
        self.btnSearch.setText(_translate("OrderManagement", "🔍 Tìm kiếm"))
        self.btnReset.setText(_translate("OrderManagement", "🔄 Xóa bộ lọc"))
        self.btnExport.setText(_translate("OrderManagement", "📊 Xuất Excel"))
        self.groupBoxOrderList.setTitle(_translate("OrderManagement", "📋 Danh sách hóa đơn"))
        item = self.tableOrders.horizontalHeaderItem(0)
        item.setText(_translate("OrderManagement", "Mã HD"))
        item = self.tableOrders.horizontalHeaderItem(1)
        item.setText(_translate("OrderManagement", "Ngày tạo"))
        item = self.tableOrders.horizontalHeaderItem(2)
        item.setText(_translate("OrderManagement", "Khách hàng"))
        item = self.tableOrders.horizontalHeaderItem(3)
        item.setText(_translate("OrderManagement", "SĐT"))
        item = self.tableOrders.horizontalHeaderItem(4)
        item.setText(_translate("OrderManagement", "Tổng tiền"))
        item = self.tableOrders.horizontalHeaderItem(5)
        item.setText(_translate("OrderManagement", "Đã thanh toán"))
        item = self.tableOrders.horizontalHeaderItem(6)
        item.setText(_translate("OrderManagement", "Còn nợ"))
        item = self.tableOrders.horizontalHeaderItem(7)
        item.setText(_translate("OrderManagement", "Trạng thái"))
        item = self.tableOrders.horizontalHeaderItem(8)
        item.setText(_translate("OrderManagement", "Thao tác"))
        self.groupBoxOrderDetail.setTitle(_translate("OrderManagement", "📄 Chi tiết hóa đơn"))
        item = self.tableOrderDetails.horizontalHeaderItem(0)
        item.setText(_translate("OrderManagement", "Mã SP"))
        item = self.tableOrderDetails.horizontalHeaderItem(1)
        item.setText(_translate("OrderManagement", "Tên sản phẩm"))
        item = self.tableOrderDetails.horizontalHeaderItem(2)
        item.setText(_translate("OrderManagement", "Số lượng"))
        item = self.tableOrderDetails.horizontalHeaderItem(3)
        item.setText(_translate("OrderManagement", "Đơn giá"))
        item = self.tableOrderDetails.horizontalHeaderItem(4)
        item.setText(_translate("OrderManagement", "Thành tiền"))
        self.btnViewDetail.setText(_translate("OrderManagement", "👁️ Xem chi tiết"))
        self.btnPrint.setText(_translate("OrderManagement", "🖨️ In hóa đơn"))
        self.btnCancel.setText(_translate("OrderManagement", "❌ Hủy hóa đơn"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderManagement = QtWidgets.QWidget()
    ui = Ui_OrderManagement()
    ui.setupUi(OrderManagement)
    OrderManagement.show()
    sys.exit(app.exec_())
