# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\product_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductManagement(object):
    def setupUi(self, ProductManagement):
        ProductManagement.setObjectName("ProductManagement")
        ProductManagement.resize(1400, 950)
        ProductManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 16px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 12px 28px;\n"
"        font-weight: bold;\n"
"        font-size: 18px;\n"
"        min-width: 140px;\n"
"        min-height: 50px;\n"
"    }\n"
"    QPushButton#btnAdd {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnAdd:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnEdit {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnEdit:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnDelete {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnDelete:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QPushButton#btnSave {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClear {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QTextEdit {\n"
"        padding: 16px 18px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 20px;\n"
"        min-height: 45px;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus {\n"
"        border-color: #3498db;\n"
"        border: 2px solid #3498db;\n"
"        outline: none;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 28px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(ProductManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(ProductManagement)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxSearch = QtWidgets.QGroupBox(ProductManagement)
        self.groupBoxSearch.setObjectName("groupBoxSearch")
        self.searchLayout = QtWidgets.QHBoxLayout(self.groupBoxSearch)
        self.searchLayout.setObjectName("searchLayout")
        self.lblSearch = QtWidgets.QLabel(self.groupBoxSearch)
        self.lblSearch.setObjectName("lblSearch")
        self.searchLayout.addWidget(self.lblSearch)
        self.txtSearch = QtWidgets.QLineEdit(self.groupBoxSearch)
        self.txtSearch.setMinimumSize(QtCore.QSize(350, 40))
        self.txtSearch.setObjectName("txtSearch")
        self.searchLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnSearch.setMinimumSize(QtCore.QSize(120, 45))
        self.btnSearch.setObjectName("btnSearch")
        self.searchLayout.addWidget(self.btnSearch)
        self.lblCategory = QtWidgets.QLabel(self.groupBoxSearch)
        self.lblCategory.setObjectName("lblCategory")
        self.searchLayout.addWidget(self.lblCategory)
        self.cboCategory = QtWidgets.QComboBox(self.groupBoxSearch)
        self.cboCategory.setMinimumSize(QtCore.QSize(180, 40))
        self.cboCategory.setObjectName("cboCategory")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.cboCategory.addItem("")
        self.searchLayout.addWidget(self.cboCategory)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnAdd.setMinimumSize(QtCore.QSize(160, 50))
        self.btnAdd.setObjectName("btnAdd")
        self.searchLayout.addWidget(self.btnAdd)
        self.verticalLayout.addWidget(self.groupBoxSearch)
        self.groupBoxProductList = QtWidgets.QGroupBox(ProductManagement)
        self.groupBoxProductList.setObjectName("groupBoxProductList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxProductList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableProducts = QtWidgets.QTableWidget(self.groupBoxProductList)
        self.tableProducts.setAlternatingRowColors(True)
        self.tableProducts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableProducts.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableProducts.setMinimumSize(QtCore.QSize(0, 350))
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.setColumnCount(9)
        self.tableProducts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProducts.setHorizontalHeaderItem(8, item)
        self.verticalLayout_2.addWidget(self.tableProducts)
        self.verticalLayout.addWidget(self.groupBoxProductList)
        self.groupBoxProductForm = QtWidgets.QGroupBox(ProductManagement)
        self.groupBoxProductForm.setObjectName("groupBoxProductForm")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxProductForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lblProductCode = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblProductCode.setObjectName("lblProductCode")
        self.gridLayout.addWidget(self.lblProductCode, 0, 0, 1, 1)
        self.txtProductCode = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtProductCode.setMinimumSize(QtCore.QSize(220, 40))
        self.txtProductCode.setObjectName("txtProductCode")
        self.gridLayout.addWidget(self.txtProductCode, 0, 1, 1, 1)
        self.lblProductName = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblProductName.setObjectName("lblProductName")
        self.gridLayout.addWidget(self.lblProductName, 0, 2, 1, 1)
        self.txtProductName = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtProductName.setMinimumSize(QtCore.QSize(280, 40))
        self.txtProductName.setObjectName("txtProductName")
        self.gridLayout.addWidget(self.txtProductName, 0, 3, 1, 1)
        self.lblCategoryForm = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblCategoryForm.setObjectName("lblCategoryForm")
        self.gridLayout.addWidget(self.lblCategoryForm, 1, 0, 1, 1)
        self.cboProductCategory = QtWidgets.QComboBox(self.groupBoxProductForm)
        self.cboProductCategory.setMinimumSize(QtCore.QSize(220, 40))
        self.cboProductCategory.setObjectName("cboProductCategory")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.cboProductCategory.addItem("")
        self.gridLayout.addWidget(self.cboProductCategory, 1, 1, 1, 1)
        self.lblBrand = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblBrand.setObjectName("lblBrand")
        self.gridLayout.addWidget(self.lblBrand, 1, 2, 1, 1)
        self.txtBrand = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtBrand.setMinimumSize(QtCore.QSize(280, 40))
        self.txtBrand.setObjectName("txtBrand")
        self.gridLayout.addWidget(self.txtBrand, 1, 3, 1, 1)
        self.lblPurchasePrice = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblPurchasePrice.setObjectName("lblPurchasePrice")
        self.gridLayout.addWidget(self.lblPurchasePrice, 2, 0, 1, 1)
        self.txtPurchasePrice = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtPurchasePrice.setMinimumSize(QtCore.QSize(220, 40))
        self.txtPurchasePrice.setObjectName("txtPurchasePrice")
        self.gridLayout.addWidget(self.txtPurchasePrice, 2, 1, 1, 1)
        self.lblSellingPrice = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblSellingPrice.setObjectName("lblSellingPrice")
        self.gridLayout.addWidget(self.lblSellingPrice, 2, 2, 1, 1)
        self.txtSellingPrice = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtSellingPrice.setMinimumSize(QtCore.QSize(280, 40))
        self.txtSellingPrice.setObjectName("txtSellingPrice")
        self.gridLayout.addWidget(self.txtSellingPrice, 2, 3, 1, 1)
        self.lblQuantity = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblQuantity.setObjectName("lblQuantity")
        self.gridLayout.addWidget(self.lblQuantity, 3, 0, 1, 1)
        self.txtQuantity = QtWidgets.QLineEdit(self.groupBoxProductForm)
        self.txtQuantity.setMinimumSize(QtCore.QSize(220, 40))
        self.txtQuantity.setObjectName("txtQuantity")
        self.gridLayout.addWidget(self.txtQuantity, 3, 1, 1, 1)
        self.lblUnit = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblUnit.setObjectName("lblUnit")
        self.gridLayout.addWidget(self.lblUnit, 3, 2, 1, 1)
        self.cboUnit = QtWidgets.QComboBox(self.groupBoxProductForm)
        self.cboUnit.setMinimumSize(QtCore.QSize(140, 40))
        self.cboUnit.setObjectName("cboUnit")
        self.cboUnit.addItem("")
        self.cboUnit.addItem("")
        self.cboUnit.addItem("")
        self.gridLayout.addWidget(self.cboUnit, 3, 3, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.groupBoxProductForm)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 4, 0, 1, 1)
        self.txtDescription = QtWidgets.QTextEdit(self.groupBoxProductForm)
        self.txtDescription.setMaximumSize(QtCore.QSize(16777215, 100))
        self.txtDescription.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDescription.setFont(font)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 4, 1, 1, 3)
        self.verticalLayout.addWidget(self.groupBoxProductForm)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(ProductManagement)
        self.btnSave.setMinimumSize(QtCore.QSize(160, 55))
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.btnEdit = QtWidgets.QPushButton(ProductManagement)
        self.btnEdit.setMinimumSize(QtCore.QSize(160, 55))
        self.btnEdit.setObjectName("btnEdit")
        self.buttonLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(ProductManagement)
        self.btnDelete.setMinimumSize(QtCore.QSize(160, 55))
        self.btnDelete.setObjectName("btnDelete")
        self.buttonLayout.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(ProductManagement)
        self.btnClear.setMinimumSize(QtCore.QSize(160, 55))
        self.btnClear.setObjectName("btnClear")
        self.buttonLayout.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(ProductManagement)

    def retranslateUi(self, ProductManagement):
        _translate = QtCore.QCoreApplication.translate
        ProductManagement.setWindowTitle(_translate("ProductManagement", "Quản lý sản phẩm"))
        self.lblTitle.setText(_translate("ProductManagement", "📦 QUẢN LÝ SẢN PHẨM"))
        self.groupBoxSearch.setTitle(_translate("ProductManagement", "🔍 Tìm kiếm & Bộ lọc"))
        self.lblSearch.setText(_translate("ProductManagement", "Tìm kiếm:"))
        self.txtSearch.setPlaceholderText(_translate("ProductManagement", "Tìm theo mã, tên sản phẩm..."))
        self.btnSearch.setText(_translate("ProductManagement", "🔍 Tìm kiếm"))
        self.lblCategory.setText(_translate("ProductManagement", "Danh mục:"))
        self.cboCategory.setItemText(0, _translate("ProductManagement", "Tất cả danh mục"))
        self.cboCategory.setItemText(1, _translate("ProductManagement", "Tủ lạnh"))
        self.cboCategory.setItemText(2, _translate("ProductManagement", "Máy giặt"))
        self.cboCategory.setItemText(3, _translate("ProductManagement", "TV"))
        self.cboCategory.setItemText(4, _translate("ProductManagement", "Điều hòa"))
        self.cboCategory.setItemText(5, _translate("ProductManagement", "Bếp từ"))
        self.cboCategory.setItemText(6, _translate("ProductManagement", "Quạt"))
        self.cboCategory.setItemText(7, _translate("ProductManagement", "Máy hút bụi"))
        self.btnAdd.setText(_translate("ProductManagement", "➕ Thêm sản phẩm"))
        self.groupBoxProductList.setTitle(_translate("ProductManagement", "📋 Danh sách sản phẩm"))
        item = self.tableProducts.horizontalHeaderItem(0)
        item.setText(_translate("ProductManagement", "ID"))
        item = self.tableProducts.horizontalHeaderItem(1)
        item.setText(_translate("ProductManagement", "Mã SP"))
        item = self.tableProducts.horizontalHeaderItem(2)
        item.setText(_translate("ProductManagement", "Tên sản phẩm"))
        item = self.tableProducts.horizontalHeaderItem(3)
        item.setText(_translate("ProductManagement", "Danh mục"))
        item = self.tableProducts.horizontalHeaderItem(4)
        item.setText(_translate("ProductManagement", "Thương hiệu"))
        item = self.tableProducts.horizontalHeaderItem(5)
        item.setText(_translate("ProductManagement", "Giá nhập"))
        item = self.tableProducts.horizontalHeaderItem(6)
        item.setText(_translate("ProductManagement", "Giá bán"))
        item = self.tableProducts.horizontalHeaderItem(7)
        item.setText(_translate("ProductManagement", "Tồn kho"))
        item = self.tableProducts.horizontalHeaderItem(8)
        item.setText(_translate("ProductManagement", "Trạng thái"))
        self.groupBoxProductForm.setTitle(_translate("ProductManagement", "📝 Nhập thông tin sản phẩm"))
        self.lblProductCode.setText(_translate("ProductManagement", "Mã sản phẩm:"))
        self.txtProductCode.setPlaceholderText(_translate("ProductManagement", "Nhập mã sản phẩm (VD: SP001)"))
        self.lblProductName.setText(_translate("ProductManagement", "Tên sản phẩm:"))
        self.txtProductName.setPlaceholderText(_translate("ProductManagement", "Nhập tên sản phẩm"))
        self.lblCategoryForm.setText(_translate("ProductManagement", "Danh mục:"))
        self.cboProductCategory.setItemText(0, _translate("ProductManagement", "Tủ lạnh"))
        self.cboProductCategory.setItemText(1, _translate("ProductManagement", "Máy giặt"))
        self.cboProductCategory.setItemText(2, _translate("ProductManagement", "TV"))
        self.cboProductCategory.setItemText(3, _translate("ProductManagement", "Điều hòa"))
        self.cboProductCategory.setItemText(4, _translate("ProductManagement", "Bếp từ"))
        self.cboProductCategory.setItemText(5, _translate("ProductManagement", "Quạt"))
        self.cboProductCategory.setItemText(6, _translate("ProductManagement", "Máy hút bụi"))
        self.lblBrand.setText(_translate("ProductManagement", "Thương hiệu:"))
        self.txtBrand.setPlaceholderText(_translate("ProductManagement", "VD: Samsung, Panasonic, Sony..."))
        self.lblPurchasePrice.setText(_translate("ProductManagement", "Giá nhập:"))
        self.txtPurchasePrice.setPlaceholderText(_translate("ProductManagement", "Nhập giá nhập (VNĐ)"))
        self.lblSellingPrice.setText(_translate("ProductManagement", "Giá bán:"))
        self.txtSellingPrice.setPlaceholderText(_translate("ProductManagement", "Nhập giá bán (VNĐ)"))
        self.lblQuantity.setText(_translate("ProductManagement", "Tồn kho:"))
        self.txtQuantity.setPlaceholderText(_translate("ProductManagement", "Nhập số lượng tồn"))
        self.lblUnit.setText(_translate("ProductManagement", "Đơn vị tính:"))
        self.cboUnit.setItemText(0, _translate("ProductManagement", "cái"))
        self.cboUnit.setItemText(1, _translate("ProductManagement", "chiếc"))
        self.cboUnit.setItemText(2, _translate("ProductManagement", "bộ"))
        self.lblDescription.setText(_translate("ProductManagement", "Mô tả:"))
        self.txtDescription.setPlaceholderText(_translate("ProductManagement", "Nhập mô tả sản phẩm (tùy chọn)"))
        self.btnSave.setText(_translate("ProductManagement", "💾 Lưu sản phẩm"))
        self.btnEdit.setText(_translate("ProductManagement", "✏️ Sửa sản phẩm"))
        self.btnDelete.setText(_translate("ProductManagement", "🗑️ Xóa sản phẩm"))
        self.btnClear.setText(_translate("ProductManagement", "🔄 Xóa form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProductManagement = QtWidgets.QWidget()
    ui = Ui_ProductManagement()
    ui.setupUi(ProductManagement)
    ProductManagement.show()
    sys.exit(app.exec_())
