# Form implementation generated from reading ui file 'ui\register.ui'
#
# Created by: PyQt5 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(720, 820)
        RegisterDialog.setMinimumSize(680, 780)
        RegisterDialog.setStyleSheet("\n"
"    QDialog {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #667eea, stop:1 #764ba2);\n"
"    }\n"
"    QFrame#frameRegister {\n"
"        background-color: white;\n"
"        border-radius: 20px;\n"
"        padding: 30px;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 34px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        font-size: 18px;\n"
"        color: #7f8c8d;\n"
"        margin-bottom: 24px;\n"
"    }\n"
"    QLineEdit {\n"
"        padding: 18px;\n"
"        min-height: 48px;\n"
"        border: 2px solid #e0e0e0;\n"
"        border-radius: 10px;\n"
"        font-size: 24px;\n"
"        background-color: #f8f9fa;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border-color: #667eea;\n"
"        background-color: white;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 10px;\n"
"        padding: 14px;\n"
"        font-size: 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnRegister {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnRegister:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnBack {\n"
"        background-color: #95a5a6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnBack:hover {\n"
"        background-color: #bdc3c7;\n"
"    }\n"
"    QLabel {\n"
"        color: #34495e;\n"
"    }\n"
"    ")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameRegister = QtWidgets.QFrame(parent=RegisterDialog)
        self.frameRegister.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameRegister.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameRegister.setObjectName("frameRegister")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameRegister)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTitle = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_2.addWidget(self.lblSubtitle)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frameRegister)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUsername)
        self.lblEmail = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.frameRegister)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtEmail)
        self.lblPassword = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frameRegister)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPassword)
        self.lblConfirmPassword = QtWidgets.QLabel(parent=self.frameRegister)
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblConfirmPassword)
        self.txtConfirmPassword = QtWidgets.QLineEdit(parent=self.frameRegister)
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtConfirmPassword)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.btnRegister = QtWidgets.QPushButton(parent=self.frameRegister)
        self.btnRegister.setObjectName("btnRegister")
        self.verticalLayout_2.addWidget(self.btnRegister)
        self.btnBack = QtWidgets.QPushButton(parent=self.frameRegister)
        self.btnBack.setObjectName("btnBack")
        self.verticalLayout_2.addWidget(self.btnBack)
        self.verticalLayout.addWidget(self.frameRegister)

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Đăng ký tài khoản"))
        self.lblTitle.setText(_translate("RegisterDialog", "ĐĂNG KÝ"))
        self.lblSubtitle.setText(_translate("RegisterDialog", "Tạo tài khoản mới"))
        self.lblUsername.setText(_translate("RegisterDialog", "Tên đăng nhập:"))
        self.txtUsername.setPlaceholderText(_translate("RegisterDialog", "Nhập tên đăng nhập"))
        self.lblEmail.setText(_translate("RegisterDialog", "Email:"))
        self.txtEmail.setPlaceholderText(_translate("RegisterDialog", "Nhập email"))
        self.lblPassword.setText(_translate("RegisterDialog", "Mật khẩu:"))
        self.txtPassword.setPlaceholderText(_translate("RegisterDialog", "Nhập mật khẩu"))
        self.lblConfirmPassword.setText(_translate("RegisterDialog", "Xác nhận mật khẩu:"))
        self.txtConfirmPassword.setPlaceholderText(_translate("RegisterDialog", "Nhập lại mật khẩu"))
        self.btnRegister.setText(_translate("RegisterDialog", "ĐĂNG KÝ"))
        self.btnBack.setText(_translate("RegisterDialog", "QUAY LẠI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterDialog = QtWidgets.QWidget()
    ui = Ui_RegisterDialog()
    ui.setupUi(RegisterDialog)
    RegisterDialog.show()
    sys.exit(app.exec())