# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MINH\OneDrive\문서\GitHub\quanlydo-giadung\quan-ly-dai-ly-kinh-doanh-do-gia-dung-main\ui\register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(550, 700)
        RegisterDialog.setStyleSheet("\n"
"    QDialog {\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"            stop:0 #667eea, stop:1 #764ba2);\n"
"    }\n"
"    QFrame#frameRegister {\n"
"        background-color: white;\n"
"        border-radius: 20px;\n"
"        padding: 30px;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 28px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblSubtitle {\n"
"        font-size: 14px;\n"
"        color: #7f8c8d;\n"
"        margin-bottom: 20px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLineEdit {\n"
"        padding: 12px;\n"
"        border: 2px solid #e0e0e0;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"        background-color: #f8f9fa;\n"
"    }\n"
"    QLineEdit:focus {\n"
"        border-color: #667eea;\n"
"        background-color: white;\n"
"    }\n"
"    QComboBox {\n"
"        padding: 10px;\n"
"        border: 2px solid #e0e0e0;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"        background-color: #f8f9fa;\n"
"    }\n"
"    QComboBox:focus {\n"
"        border-color: #667eea;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 10px;\n"
"        padding: 12px;\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnRegister {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnRegister:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnCancel {\n"
"        background-color: #95a5a6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnCancel:hover {\n"
"        background-color: #7f8c8d;\n"
"    }\n"
"    QPushButton#btnLogin {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnLogin:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QCheckBox {\n"
"        color: #555;\n"
"    }\n"
"    QLabel#lblError {\n"
"        color: #e74c3c;\n"
"        font-size: 12px;\n"
"    }\n"
"    QLabel#lblSuccess {\n"
"        color: #27ae60;\n"
"        font-size: 12px;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameRegister = QtWidgets.QFrame(RegisterDialog)
        self.frameRegister.setObjectName("frameRegister")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameRegister)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTitle = QtWidgets.QLabel(self.frameRegister)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.lblSubtitle = QtWidgets.QLabel(self.frameRegister)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.verticalLayout_2.addWidget(self.lblSubtitle)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.lblAccountInfo = QtWidgets.QLabel(self.frameRegister)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblAccountInfo.setFont(font)
        self.lblAccountInfo.setStyleSheet("color: #667eea; margin-top: 10px;")
        self.lblAccountInfo.setObjectName("lblAccountInfo")
        self.verticalLayout_2.addWidget(self.lblAccountInfo)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblUsername = QtWidgets.QLabel(self.frameRegister)
        self.lblUsername.setObjectName("lblUsername")
        self.gridLayout.addWidget(self.lblUsername, 0, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(self.frameRegister)
        self.txtUsername.setObjectName("txtUsername")
        self.gridLayout.addWidget(self.txtUsername, 0, 1, 1, 1)
        self.lblPassword = QtWidgets.QLabel(self.frameRegister)
        self.lblPassword.setObjectName("lblPassword")
        self.gridLayout.addWidget(self.lblPassword, 1, 0, 1, 1)
        self.txtPassword = QtWidgets.QLineEdit(self.frameRegister)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.gridLayout.addWidget(self.txtPassword, 1, 1, 1, 1)
        self.lblConfirmPassword = QtWidgets.QLabel(self.frameRegister)
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.gridLayout.addWidget(self.lblConfirmPassword, 2, 0, 1, 1)
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.frameRegister)
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.gridLayout.addWidget(self.txtConfirmPassword, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.lblPersonalInfo = QtWidgets.QLabel(self.frameRegister)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblPersonalInfo.setFont(font)
        self.lblPersonalInfo.setStyleSheet("color: #667eea; margin-top: 10px;")
        self.lblPersonalInfo.setObjectName("lblPersonalInfo")
        self.verticalLayout_2.addWidget(self.lblPersonalInfo)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblFullName = QtWidgets.QLabel(self.frameRegister)
        self.lblFullName.setObjectName("lblFullName")
        self.gridLayout_2.addWidget(self.lblFullName, 0, 0, 1, 1)
        self.txtFullName = QtWidgets.QLineEdit(self.frameRegister)
        self.txtFullName.setObjectName("txtFullName")
        self.gridLayout_2.addWidget(self.txtFullName, 0, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.frameRegister)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout_2.addWidget(self.lblEmail, 1, 0, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.frameRegister)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout_2.addWidget(self.txtEmail, 1, 1, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.frameRegister)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout_2.addWidget(self.lblPhone, 2, 0, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.frameRegister)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout_2.addWidget(self.txtPhone, 2, 1, 1, 1)
        self.lblRole = QtWidgets.QLabel(self.frameRegister)
        self.lblRole.setObjectName("lblRole")
        self.gridLayout_2.addWidget(self.lblRole, 3, 0, 1, 1)
        self.cboRole = QtWidgets.QComboBox(self.frameRegister)
        self.cboRole.setObjectName("cboRole")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.cboRole.addItem("")
        self.gridLayout_2.addWidget(self.cboRole, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.chkTerms = QtWidgets.QCheckBox(self.frameRegister)
        self.chkTerms.setObjectName("chkTerms")
        self.verticalLayout_2.addWidget(self.chkTerms)
        self.lblMessage = QtWidgets.QLabel(self.frameRegister)
        self.lblMessage.setText("")
        self.lblMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMessage.setWordWrap(True)
        self.lblMessage.setObjectName("lblMessage")
        self.verticalLayout_2.addWidget(self.lblMessage)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnRegister = QtWidgets.QPushButton(self.frameRegister)
        self.btnRegister.setDefault(True)
        self.btnRegister.setObjectName("btnRegister")
        self.buttonLayout.addWidget(self.btnRegister)
        self.btnCancel = QtWidgets.QPushButton(self.frameRegister)
        self.btnCancel.setObjectName("btnCancel")
        self.buttonLayout.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.buttonLayout)
        self.loginLayout = QtWidgets.QHBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginLayout.addItem(spacerItem4)
        self.lblHaveAccount = QtWidgets.QLabel(self.frameRegister)
        self.lblHaveAccount.setObjectName("lblHaveAccount")
        self.loginLayout.addWidget(self.lblHaveAccount)
        self.btnLogin = QtWidgets.QPushButton(self.frameRegister)
        self.btnLogin.setFlat(True)
        self.btnLogin.setStyleSheet("color: #3498db; text-decoration: underline; background: transparent;")
        self.btnLogin.setObjectName("btnLogin")
        self.loginLayout.addWidget(self.btnLogin)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.loginLayout)
        self.verticalLayout.addWidget(self.frameRegister)

        self.retranslateUi(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Đăng ký tài khoản"))
        self.lblTitle.setText(_translate("RegisterDialog", "📝 ĐĂNG KÝ TÀI KHOẢN"))
        self.lblSubtitle.setText(_translate("RegisterDialog", "Tạo tài khoản mới để bắt đầu sử dụng hệ thống"))
        self.lblAccountInfo.setText(_translate("RegisterDialog", "🔐 THÔNG TIN TÀI KHOẢN"))
        self.lblUsername.setText(_translate("RegisterDialog", "👤 Tên đăng nhập:"))
        self.txtUsername.setPlaceholderText(_translate("RegisterDialog", "Nhập tên đăng nhập"))
        self.lblPassword.setText(_translate("RegisterDialog", "🔒 Mật khẩu:"))
        self.txtPassword.setPlaceholderText(_translate("RegisterDialog", "Nhập mật khẩu (tối thiểu 6 ký tự)"))
        self.lblConfirmPassword.setText(_translate("RegisterDialog", "🔐 Xác nhận MK:"))
        self.txtConfirmPassword.setPlaceholderText(_translate("RegisterDialog", "Nhập lại mật khẩu"))
        self.lblPersonalInfo.setText(_translate("RegisterDialog", "👨‍💼 THÔNG TIN CÁ NHÂN"))
        self.lblFullName.setText(_translate("RegisterDialog", "📛 Họ và tên:"))
        self.txtFullName.setPlaceholderText(_translate("RegisterDialog", "Nhập họ và tên đầy đủ"))
        self.lblEmail.setText(_translate("RegisterDialog", "📧 Email:"))
        self.txtEmail.setPlaceholderText(_translate("RegisterDialog", "Nhập địa chỉ email"))
        self.lblPhone.setText(_translate("RegisterDialog", "📱 Số điện thoại:"))
        self.txtPhone.setPlaceholderText(_translate("RegisterDialog", "Nhập số điện thoại"))
        self.lblRole.setText(_translate("RegisterDialog", "🎯 Vai trò:"))
        self.cboRole.setItemText(0, _translate("RegisterDialog", "Nhân viên bán hàng"))
        self.cboRole.setItemText(1, _translate("RegisterDialog", "Quản lý kho"))
        self.cboRole.setItemText(2, _translate("RegisterDialog", "Kế toán"))
        self.chkTerms.setText(_translate("RegisterDialog", "Tôi đồng ý với "))
        self.btnRegister.setText(_translate("RegisterDialog", "✅ Đăng ký"))
        self.btnCancel.setText(_translate("RegisterDialog", "❌ Hủy bỏ"))
        self.lblHaveAccount.setText(_translate("RegisterDialog", "Đã có tài khoản?"))
        self.btnLogin.setText(_translate("RegisterDialog", "Đăng nhập ngay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterDialog = QtWidgets.QDialog()
    ui = Ui_RegisterDialog()
    ui.setupUi(RegisterDialog)
    RegisterDialog.show()
    sys.exit(app.exec_())
