# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\report_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportViewer(object):
    def setupUi(self, ReportViewer):
        ReportViewer.setObjectName("ReportViewer")
        ReportViewer.resize(1400, 900)
        ReportViewer.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 10px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnViewReport {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExportExcel {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExportPDF {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnPrintReport {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QComboBox, QDateEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblChart {\n"
"        background-color: white;\n"
"        border: 1px solid #ddd;\n"
"        border-radius: 10px;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(ReportViewer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(ReportViewer)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.groupBoxFilter = QtWidgets.QGroupBox(ReportViewer)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxFilter)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblReportType = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblReportType.setObjectName("lblReportType")
        self.horizontalLayout.addWidget(self.lblReportType)
        self.cboReportType = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboReportType.setMinimumSize(QtCore.QSize(200, 0))
        self.cboReportType.setObjectName("cboReportType")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.cboReportType.addItem("")
        self.horizontalLayout.addWidget(self.cboReportType)
        self.lblFromDate = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblFromDate.setObjectName("lblFromDate")
        self.horizontalLayout.addWidget(self.lblFromDate)
        self.dateFrom = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setDate(QtCore.QDate(2026, 1, 1))
        self.dateFrom.setObjectName("dateFrom")
        self.horizontalLayout.addWidget(self.dateFrom)
        self.lblToDate = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblToDate.setObjectName("lblToDate")
        self.horizontalLayout.addWidget(self.lblToDate)
        self.dateTo = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setDate(QtCore.QDate(2026, 4, 14))
        self.dateTo.setObjectName("dateTo")
        self.horizontalLayout.addWidget(self.dateTo)
        self.btnViewReport = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnViewReport.setObjectName("btnViewReport")
        self.horizontalLayout.addWidget(self.btnViewReport)
        self.filterLayout.addWidget(self.groupBoxFilter)
        self.verticalLayout.addLayout(self.filterLayout)
        self.actionLayout = QtWidgets.QHBoxLayout()
        self.actionLayout.setObjectName("actionLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.actionLayout.addItem(spacerItem)
        self.btnExportExcel = QtWidgets.QPushButton(ReportViewer)
        self.btnExportExcel.setObjectName("btnExportExcel")
        self.actionLayout.addWidget(self.btnExportExcel)
        self.btnExportPDF = QtWidgets.QPushButton(ReportViewer)
        self.btnExportPDF.setObjectName("btnExportPDF")
        self.actionLayout.addWidget(self.btnExportPDF)
        self.btnPrintReport = QtWidgets.QPushButton(ReportViewer)
        self.btnPrintReport.setObjectName("btnPrintReport")
        self.actionLayout.addWidget(self.btnPrintReport)
        self.verticalLayout.addLayout(self.actionLayout)
        self.tabWidget = QtWidgets.QTabWidget(ReportViewer)
        self.tabWidget.setObjectName("tabWidget")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabData)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableReport = QtWidgets.QTableWidget(self.tabData)
        self.tableReport.setAlternatingRowColors(True)
        self.tableReport.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableReport.setObjectName("tableReport")
        self.tableReport.setColumnCount(0)
        self.tableReport.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableReport)
        self.tabWidget.addTab(self.tabData, "")
        self.tabChart = QtWidgets.QWidget()
        self.tabChart.setObjectName("tabChart")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabChart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblChart = QtWidgets.QLabel(self.tabChart)
        self.lblChart.setAlignment(QtCore.Qt.AlignCenter)
        self.lblChart.setMinimumSize(QtCore.QSize(0, 400))
        self.lblChart.setObjectName("lblChart")
        self.verticalLayout_3.addWidget(self.lblChart)
        self.tabWidget.addTab(self.tabChart, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBoxSummary = QtWidgets.QGroupBox(ReportViewer)
        self.groupBoxSummary.setObjectName("groupBoxSummary")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxSummary)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblTotalRevenue = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalRevenue.setFont(font)
        self.lblTotalRevenue.setObjectName("lblTotalRevenue")
        self.gridLayout_2.addWidget(self.lblTotalRevenue, 0, 0, 1, 1)
        self.lblTotalRevenueValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblTotalRevenueValue.setStyleSheet("color: #27ae60; font-size: 16px; font-weight: bold;")
        self.lblTotalRevenueValue.setObjectName("lblTotalRevenueValue")
        self.gridLayout_2.addWidget(self.lblTotalRevenueValue, 0, 1, 1, 1)
        self.lblTotalOrders = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalOrders.setFont(font)
        self.lblTotalOrders.setObjectName("lblTotalOrders")
        self.gridLayout_2.addWidget(self.lblTotalOrders, 0, 2, 1, 1)
        self.lblTotalOrdersValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblTotalOrdersValue.setStyleSheet("font-size: 16px; font-weight: bold;")
        self.lblTotalOrdersValue.setObjectName("lblTotalOrdersValue")
        self.gridLayout_2.addWidget(self.lblTotalOrdersValue, 0, 3, 1, 1)
        self.lblAvgOrderValue = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblAvgOrderValue.setFont(font)
        self.lblAvgOrderValue.setObjectName("lblAvgOrderValue")
        self.gridLayout_2.addWidget(self.lblAvgOrderValue, 1, 0, 1, 1)
        self.lblAvgOrderValueValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblAvgOrderValueValue.setObjectName("lblAvgOrderValueValue")
        self.gridLayout_2.addWidget(self.lblAvgOrderValueValue, 1, 1, 1, 1)
        self.lblTopProduct = QtWidgets.QLabel(self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTopProduct.setFont(font)
        self.lblTopProduct.setObjectName("lblTopProduct")
        self.gridLayout_2.addWidget(self.lblTopProduct, 1, 2, 1, 1)
        self.lblTopProductValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.lblTopProductValue.setObjectName("lblTopProductValue")
        self.gridLayout_2.addWidget(self.lblTopProductValue, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxSummary)

        self.retranslateUi(ReportViewer)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, ReportViewer):
        _translate = QtCore.QCoreApplication.translate
        ReportViewer.setWindowTitle(_translate("ReportViewer", "Báo cáo thống kê"))
        self.lblTitle.setText(_translate("ReportViewer", "📊 BÁO CÁO THỐNG KÊ"))
        self.groupBoxFilter.setTitle(_translate("ReportViewer", "Bộ lọc báo cáo"))
        self.lblReportType.setText(_translate("ReportViewer", "Loại báo cáo:"))
        self.cboReportType.setItemText(0, _translate("ReportViewer", "📈 Báo cáo doanh thu"))
        self.cboReportType.setItemText(1, _translate("ReportViewer", "📦 Báo cáo tồn kho"))
        self.cboReportType.setItemText(2, _translate("ReportViewer", "👨‍💼 Doanh số nhân viên"))
        self.cboReportType.setItemText(3, _translate("ReportViewer", "🏆 Top sản phẩm bán chạy"))
        self.cboReportType.setItemText(4, _translate("ReportViewer", "💰 Báo cáo lương"))
        self.cboReportType.setItemText(5, _translate("ReportViewer", "👥 Báo cáo khách hàng"))
        self.lblFromDate.setText(_translate("ReportViewer", "Từ ngày:"))
        self.lblToDate.setText(_translate("ReportViewer", "Đến ngày:"))
        self.btnViewReport.setText(_translate("ReportViewer", "👁️ Xem báo cáo"))
        self.btnExportExcel.setText(_translate("ReportViewer", "📊 Xuất Excel"))
        self.btnExportPDF.setText(_translate("ReportViewer", "📄 Xuất PDF"))
        self.btnPrintReport.setText(_translate("ReportViewer", "🖨️ In báo cáo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("ReportViewer", "📋 Dữ liệu báo cáo"))
        self.lblChart.setText(_translate("ReportViewer", "Khu vực hiển thị biểu đồ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabChart), _translate("ReportViewer", "📈 Biểu đồ"))
        self.groupBoxSummary.setTitle(_translate("ReportViewer", "Tổng kết"))
        self.lblTotalRevenue.setText(_translate("ReportViewer", "Tổng doanh thu:"))
        self.lblTotalRevenueValue.setText(_translate("ReportViewer", "0 VNĐ"))
        self.lblTotalOrders.setText(_translate("ReportViewer", "Tổng số hóa đơn:"))
        self.lblTotalOrdersValue.setText(_translate("ReportViewer", "0"))
        self.lblAvgOrderValue.setText(_translate("ReportViewer", "Trung bình/đơn:"))
        self.lblAvgOrderValueValue.setText(_translate("ReportViewer", "0 VNĐ"))
        self.lblTopProduct.setText(_translate("ReportViewer", "Sản phẩm bán chạy:"))
        self.lblTopProductValue.setText(_translate("ReportViewer", "--"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportViewer = QtWidgets.QWidget()
    ui = Ui_ReportViewer()
    ui.setupUi(ReportViewer)
    ReportViewer.show()
    sys.exit(app.exec_())
