# Form implementation generated from reading ui file 'ui\salary_calculation.ui'
#
# Created by: PyQt5 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SalaryCalculation(object):
    def setupUi(self, SalaryCalculation):
        SalaryCalculation.setObjectName("SalaryCalculation")
        SalaryCalculation.resize(1400, 900)
        SalaryCalculation.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnCalculate {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"        font-size: 14px;\n"
"    }\n"
"    QPushButton#btnCalculate:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnExportSalary {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnPrintSalary {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnConfirmPayment {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QComboBox, QDateEdit, QLineEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 13px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QLabel#lblTotalSalary {\n"
"        font-size: 24px;\n"
"        font-weight: bold;\n"
"        color: #e74c3c;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(SalaryCalculation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=SalaryCalculation)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.lblMonth = QtWidgets.QLabel(parent=SalaryCalculation)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMonth.setFont(font)
        self.lblMonth.setObjectName("lblMonth")
        self.controlLayout.addWidget(self.lblMonth)
        self.dateSalaryMonth = QtWidgets.QDateEdit(parent=SalaryCalculation)
        self.dateSalaryMonth.setCalendarPopup(True)
        self.dateSalaryMonth.setDate(QtCore.QDate(2026, 4, 1))
        self.dateSalaryMonth.setObjectName("dateSalaryMonth")
        self.controlLayout.addWidget(self.dateSalaryMonth)
        self.btnCalculate = QtWidgets.QPushButton(parent=SalaryCalculation)
        self.btnCalculate.setObjectName("btnCalculate")
        self.controlLayout.addWidget(self.btnCalculate)
        self.btnExportSalary = QtWidgets.QPushButton(parent=SalaryCalculation)
        self.btnExportSalary.setObjectName("btnExportSalary")
        self.controlLayout.addWidget(self.btnExportSalary)
        self.btnPrintSalary = QtWidgets.QPushButton(parent=SalaryCalculation)
        self.btnPrintSalary.setObjectName("btnPrintSalary")
        self.controlLayout.addWidget(self.btnPrintSalary)
        self.verticalLayout.addLayout(self.controlLayout)
        self.tableSalary = QtWidgets.QTableWidget(parent=SalaryCalculation)
        self.tableSalary.setAlternatingRowColors(True)
        self.tableSalary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableSalary.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableSalary.setObjectName("tableSalary")
        self.tableSalary.setColumnCount(13)
        self.tableSalary.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSalary.setHorizontalHeaderItem(12, item)
        self.verticalLayout.addWidget(self.tableSalary)
        self.summaryLayout = QtWidgets.QHBoxLayout()
        self.summaryLayout.setObjectName("summaryLayout")
        self.groupBoxSummary = QtWidgets.QGroupBox(parent=SalaryCalculation)
        self.groupBoxSummary.setObjectName("groupBoxSummary")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSummary)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTotalEmployees = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalEmployees.setObjectName("lblTotalEmployees")
        self.gridLayout.addWidget(self.lblTotalEmployees, 0, 0, 1, 1)
        self.lblTotalEmployeesValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalEmployeesValue.setFont(font)
        self.lblTotalEmployeesValue.setObjectName("lblTotalEmployeesValue")
        self.gridLayout.addWidget(self.lblTotalEmployeesValue, 0, 1, 1, 1)
        self.lblTotalBaseSalary = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalBaseSalary.setObjectName("lblTotalBaseSalary")
        self.gridLayout.addWidget(self.lblTotalBaseSalary, 0, 2, 1, 1)
        self.lblTotalBaseSalaryValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalBaseSalaryValue.setFont(font)
        self.lblTotalBaseSalaryValue.setObjectName("lblTotalBaseSalaryValue")
        self.gridLayout.addWidget(self.lblTotalBaseSalaryValue, 0, 3, 1, 1)
        self.lblTotalCommission = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalCommission.setObjectName("lblTotalCommission")
        self.gridLayout.addWidget(self.lblTotalCommission, 1, 0, 1, 1)
        self.lblTotalCommissionValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalCommissionValue.setFont(font)
        self.lblTotalCommissionValue.setObjectName("lblTotalCommissionValue")
        self.gridLayout.addWidget(self.lblTotalCommissionValue, 1, 1, 1, 1)
        self.lblTotalAllowance = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalAllowance.setObjectName("lblTotalAllowance")
        self.gridLayout.addWidget(self.lblTotalAllowance, 1, 2, 1, 1)
        self.lblTotalAllowanceValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalAllowanceValue.setFont(font)
        self.lblTotalAllowanceValue.setObjectName("lblTotalAllowanceValue")
        self.gridLayout.addWidget(self.lblTotalAllowanceValue, 1, 3, 1, 1)
        self.lblTotalBonus = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalBonus.setObjectName("lblTotalBonus")
        self.gridLayout.addWidget(self.lblTotalBonus, 2, 0, 1, 1)
        self.lblTotalBonusValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalBonusValue.setFont(font)
        self.lblTotalBonusValue.setObjectName("lblTotalBonusValue")
        self.gridLayout.addWidget(self.lblTotalBonusValue, 2, 1, 1, 1)
        self.lblTotalSalary = QtWidgets.QLabel(parent=self.groupBoxSummary)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblTotalSalary.setFont(font)
        self.lblTotalSalary.setObjectName("lblTotalSalary")
        self.gridLayout.addWidget(self.lblTotalSalary, 2, 2, 1, 1)
        self.lblTotalSalaryValue = QtWidgets.QLabel(parent=self.groupBoxSummary)
        self.lblTotalSalaryValue.setStyleSheet("font-size: 18px; font-weight: bold; color: #e74c3c;")
        self.lblTotalSalaryValue.setObjectName("lblTotalSalaryValue")
        self.gridLayout.addWidget(self.lblTotalSalaryValue, 2, 3, 1, 1)
        self.summaryLayout.addWidget(self.groupBoxSummary)
        self.verticalLayout.addLayout(self.summaryLayout)
        self.actionLayout = QtWidgets.QHBoxLayout()
        self.actionLayout.setObjectName("actionLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.actionLayout.addItem(spacerItem)
        self.btnConfirmPayment = QtWidgets.QPushButton(parent=SalaryCalculation)
        self.btnConfirmPayment.setMinimumSize(QtCore.QSize(200, 40))
        self.btnConfirmPayment.setObjectName("btnConfirmPayment")
        self.actionLayout.addWidget(self.btnConfirmPayment)
        self.btnPrintPayslip = QtWidgets.QPushButton(parent=SalaryCalculation)
        self.btnPrintPayslip.setMinimumSize(QtCore.QSize(150, 40))
        self.btnPrintPayslip.setObjectName("btnPrintPayslip")
        self.actionLayout.addWidget(self.btnPrintPayslip)
        self.verticalLayout.addLayout(self.actionLayout)

        self.retranslateUi(SalaryCalculation)

    def retranslateUi(self, SalaryCalculation):
        _translate = QtCore.QCoreApplication.translate
        SalaryCalculation.setWindowTitle(_translate("SalaryCalculation", "Tính lương nhân viên"))
        self.lblTitle.setText(_translate("SalaryCalculation", "💰 TÍNH LƯƠNG NHÂN VIÊN"))
        self.lblMonth.setText(_translate("SalaryCalculation", "Tháng tính lương:"))
        self.dateSalaryMonth.setDisplayFormat(_translate("SalaryCalculation", "MM/yyyy"))
        self.btnCalculate.setText(_translate("SalaryCalculation", "🔄 Tính lương"))
        self.btnExportSalary.setText(_translate("SalaryCalculation", "📊 Xuất Excel"))
        self.btnPrintSalary.setText(_translate("SalaryCalculation", "🖨️ In bảng lương"))
        item = self.tableSalary.horizontalHeaderItem(0)
        item.setText(_translate("SalaryCalculation", "ID"))
        item = self.tableSalary.horizontalHeaderItem(1)
        item.setText(_translate("SalaryCalculation", "Mã NV"))
        item = self.tableSalary.horizontalHeaderItem(2)
        item.setText(_translate("SalaryCalculation", "Họ tên"))
        item = self.tableSalary.horizontalHeaderItem(3)
        item.setText(_translate("SalaryCalculation", "Lương CB"))
        item = self.tableSalary.horizontalHeaderItem(4)
        item.setText(_translate("SalaryCalculation", "Doanh số"))
        item = self.tableSalary.horizontalHeaderItem(5)
        item.setText(_translate("SalaryCalculation", "Hoa hồng"))
        item = self.tableSalary.horizontalHeaderItem(6)
        item.setText(_translate("SalaryCalculation", "Thưởng"))
        item = self.tableSalary.horizontalHeaderItem(7)
        item.setText(_translate("SalaryCalculation", "Phụ cấp"))
        item = self.tableSalary.horizontalHeaderItem(8)
        item.setText(_translate("SalaryCalculation", "Tạm ứng"))
        item = self.tableSalary.horizontalHeaderItem(9)
        item.setText(_translate("SalaryCalculation", "BHXH"))
        item = self.tableSalary.horizontalHeaderItem(10)
        item.setText(_translate("SalaryCalculation", "Thuế TNCN"))
        item = self.tableSalary.horizontalHeaderItem(11)
        item.setText(_translate("SalaryCalculation", "Thực lĩnh"))
        item = self.tableSalary.horizontalHeaderItem(12)
        item.setText(_translate("SalaryCalculation", "Trạng thái"))
        self.groupBoxSummary.setTitle(_translate("SalaryCalculation", "Tổng hợp lương tháng"))
        self.lblTotalEmployees.setText(_translate("SalaryCalculation", "Tổng số nhân viên:"))
        self.lblTotalEmployeesValue.setText(_translate("SalaryCalculation", "0"))
        self.lblTotalBaseSalary.setText(_translate("SalaryCalculation", "Tổng lương cơ bản:"))
        self.lblTotalBaseSalaryValue.setText(_translate("SalaryCalculation", "0 VNĐ"))
        self.lblTotalCommission.setText(_translate("SalaryCalculation", "Tổng hoa hồng:"))
        self.lblTotalCommissionValue.setText(_translate("SalaryCalculation", "0 VNĐ"))
        self.lblTotalAllowance.setText(_translate("SalaryCalculation", "Tổng phụ cấp:"))
        self.lblTotalAllowanceValue.setText(_translate("SalaryCalculation", "0 VNĐ"))
        self.lblTotalBonus.setText(_translate("SalaryCalculation", "Tổng thưởng:"))
        self.lblTotalBonusValue.setText(_translate("SalaryCalculation", "0 VNĐ"))
        self.lblTotalSalary.setText(_translate("SalaryCalculation", "TỔNG THỰC LĨNH:"))
        self.lblTotalSalaryValue.setText(_translate("SalaryCalculation", "0 VNĐ"))
        self.btnConfirmPayment.setText(_translate("SalaryCalculation", "💰 Xác nhận đã trả lương"))
        self.btnPrintPayslip.setText(_translate("SalaryCalculation", "🖨️ In phiếu lương"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SalaryCalculation = QtWidgets.QWidget()
    ui = Ui_SalaryCalculation()
    ui.setupUi(SalaryCalculation)
    SalaryCalculation.show()
    sys.exit(app.exec())
