# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\sale_order.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaleOrder(object):
    def setupUi(self, SaleOrder):
        SaleOrder.setObjectName("SaleOrder")
        SaleOrder.resize(1300, 900)
        SaleOrder.setStyleSheet("\n"
"    QWidget { background-color: #f5f7fa; }\n"
"    QGroupBox { font-weight: bold; border: 2px solid #ddd; border-radius: 10px; margin-top: 10px; padding-top: 10px; background-color: white; }\n"
"    QTableWidget { background-color: white; }\n"
"    QHeaderView::section { background-color: #e67e22; color: white; padding: 10px; }\n"
"    QPushButton { border-radius: 6px; padding: 10px 20px; font-weight: bold; }\n"
"    QPushButton#btnAddToCart { background-color: #3498db; color: white; }\n"
"    QPushButton#btnCheckout { background-color: #27ae60; color: white; font-size: 16px; }\n"
"    QPushButton#btnClearCart { background-color: #e74c3c; color: white; }\n"
"    QLineEdit, QComboBox { padding: 8px; border: 1px solid #ddd; border-radius: 6px; }\n"
"    QLabel#lblTotal { font-size: 20px; font-weight: bold; color: #e74c3c; }\n"
"   ")
        self.horizontalLayout = QtWidgets.QHBoxLayout(SaleOrder)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBoxProducts = QtWidgets.QGroupBox(SaleOrder)
        self.groupBoxProducts.setObjectName("groupBoxProducts")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxProducts)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.productSearchLayout = QtWidgets.QHBoxLayout()
        self.productSearchLayout.setObjectName("productSearchLayout")
        self.txtProductSearch = QtWidgets.QLineEdit(self.groupBoxProducts)
        self.txtProductSearch.setObjectName("txtProductSearch")
        self.productSearchLayout.addWidget(self.txtProductSearch)
        self.btnSearchProduct = QtWidgets.QPushButton(self.groupBoxProducts)
        self.btnSearchProduct.setObjectName("btnSearchProduct")
        self.productSearchLayout.addWidget(self.btnSearchProduct)
        self.verticalLayout_2.addLayout(self.productSearchLayout)
        self.tableProducts = QtWidgets.QTableWidget(self.groupBoxProducts)
        self.tableProducts.setObjectName("tableProducts")
        self.tableProducts.setColumnCount(0)
        self.tableProducts.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableProducts)
        self.horizontalLayout.addWidget(self.groupBoxProducts)
        self.groupBoxCart = QtWidgets.QGroupBox(SaleOrder)
        self.groupBoxCart.setObjectName("groupBoxCart")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBoxCart)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableCart = QtWidgets.QTableWidget(self.groupBoxCart)
        self.tableCart.setObjectName("tableCart")
        self.tableCart.setColumnCount(0)
        self.tableCart.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableCart)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBoxCart)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lblTotal = QtWidgets.QLabel(self.groupBoxCart)
        self.lblTotal.setObjectName("lblTotal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblTotal)
        self.label_2 = QtWidgets.QLabel(self.groupBoxCart)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lblVAT = QtWidgets.QLabel(self.groupBoxCart)
        self.lblVAT.setObjectName("lblVAT")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblVAT)
        self.label_3 = QtWidgets.QLabel(self.groupBoxCart)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblGrandTotal = QtWidgets.QLabel(self.groupBoxCart)
        self.lblGrandTotal.setStyleSheet("font-size: 18px; font-weight: bold; color: #e74c3c;")
        self.lblGrandTotal.setObjectName("lblGrandTotal")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblGrandTotal)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.cartButtonLayout = QtWidgets.QHBoxLayout()
        self.cartButtonLayout.setObjectName("cartButtonLayout")
        self.btnAddToCart = QtWidgets.QPushButton(self.groupBoxCart)
        self.btnAddToCart.setObjectName("btnAddToCart")
        self.cartButtonLayout.addWidget(self.btnAddToCart)
        self.btnRemoveFromCart = QtWidgets.QPushButton(self.groupBoxCart)
        self.btnRemoveFromCart.setObjectName("btnRemoveFromCart")
        self.cartButtonLayout.addWidget(self.btnRemoveFromCart)
        self.btnClearCart = QtWidgets.QPushButton(self.groupBoxCart)
        self.btnClearCart.setObjectName("btnClearCart")
        self.cartButtonLayout.addWidget(self.btnClearCart)
        self.verticalLayout_3.addLayout(self.cartButtonLayout)
        self.btnCheckout = QtWidgets.QPushButton(self.groupBoxCart)
        self.btnCheckout.setObjectName("btnCheckout")
        self.verticalLayout_3.addWidget(self.btnCheckout)
        self.horizontalLayout.addWidget(self.groupBoxCart)

        self.retranslateUi(SaleOrder)

    def retranslateUi(self, SaleOrder):
        _translate = QtCore.QCoreApplication.translate
        SaleOrder.setWindowTitle(_translate("SaleOrder", "Bán hàng"))
        self.groupBoxProducts.setTitle(_translate("SaleOrder", "📦 Danh sách sản phẩm"))
        self.txtProductSearch.setPlaceholderText(_translate("SaleOrder", "Tìm kiếm sản phẩm..."))
        self.btnSearchProduct.setText(_translate("SaleOrder", "🔍 Tìm"))
        self.groupBoxCart.setTitle(_translate("SaleOrder", "🛒 Giỏ hàng"))
        self.label.setText(_translate("SaleOrder", "Tổng tiền:"))
        self.lblTotal.setText(_translate("SaleOrder", "0 VNĐ"))
        self.label_2.setText(_translate("SaleOrder", "Thuế VAT (10%):"))
        self.lblVAT.setText(_translate("SaleOrder", "0 VNĐ"))
        self.label_3.setText(_translate("SaleOrder", "Thành tiền:"))
        self.lblGrandTotal.setText(_translate("SaleOrder", "0 VNĐ"))
        self.btnAddToCart.setText(_translate("SaleOrder", "➕ Thêm vào giỏ"))
        self.btnRemoveFromCart.setText(_translate("SaleOrder", "❌ Xóa khỏi giỏ"))
        self.btnClearCart.setText(_translate("SaleOrder", "🗑️ Xóa giỏ hàng"))
        self.btnCheckout.setText(_translate("SaleOrder", "💳 THANH TOÁN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaleOrder = QtWidgets.QWidget()
    ui = Ui_SaleOrder()
    ui.setupUi(SaleOrder)
    SaleOrder.show()
    sys.exit(app.exec_())
