# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\shift_schedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShiftSchedule(object):
    def setupUi(self, ShiftSchedule):
        ShiftSchedule.setObjectName("ShiftSchedule")
        ShiftSchedule.resize(1300, 850)
        ShiftSchedule.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f5f7fa;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 8px 18px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton#btnSaveSchedule {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSaveSchedule:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnCopyWeek {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClearSchedule {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExportSchedule {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QComboBox, QDateEdit {\n"
"        padding: 8px 12px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 13px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 1px solid #e1e8ed;\n"
"        border-radius: 10px;\n"
"        background-color: white;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background-color: #ecf0f1;\n"
"        padding: 10px 25px;\n"
"        margin-right: 3px;\n"
"        border-top-left-radius: 8px;\n"
"        border-top-right-radius: 8px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(ShiftSchedule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(ShiftSchedule)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.controlLayout = QtWidgets.QHBoxLayout()
        self.controlLayout.setObjectName("controlLayout")
        self.lblMonth = QtWidgets.QLabel(ShiftSchedule)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblMonth.setFont(font)
        self.lblMonth.setObjectName("lblMonth")
        self.controlLayout.addWidget(self.lblMonth)
        self.dateMonth = QtWidgets.QDateEdit(ShiftSchedule)
        self.dateMonth.setCalendarPopup(True)
        self.dateMonth.setDate(QtCore.QDate(2026, 4, 1))
        self.dateMonth.setObjectName("dateMonth")
        self.controlLayout.addWidget(self.dateMonth)
        self.btnLoadSchedule = QtWidgets.QPushButton(ShiftSchedule)
        self.btnLoadSchedule.setObjectName("btnLoadSchedule")
        self.controlLayout.addWidget(self.btnLoadSchedule)
        self.btnCopyWeek = QtWidgets.QPushButton(ShiftSchedule)
        self.btnCopyWeek.setObjectName("btnCopyWeek")
        self.controlLayout.addWidget(self.btnCopyWeek)
        self.btnSaveSchedule = QtWidgets.QPushButton(ShiftSchedule)
        self.btnSaveSchedule.setObjectName("btnSaveSchedule")
        self.controlLayout.addWidget(self.btnSaveSchedule)
        self.btnClearSchedule = QtWidgets.QPushButton(ShiftSchedule)
        self.btnClearSchedule.setObjectName("btnClearSchedule")
        self.controlLayout.addWidget(self.btnClearSchedule)
        self.btnExportSchedule = QtWidgets.QPushButton(ShiftSchedule)
        self.btnExportSchedule.setObjectName("btnExportSchedule")
        self.controlLayout.addWidget(self.btnExportSchedule)
        self.verticalLayout.addLayout(self.controlLayout)
        self.tabWidget = QtWidgets.QTabWidget(ShiftSchedule)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGridView = QtWidgets.QWidget()
        self.tabGridView.setObjectName("tabGridView")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabGridView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableSchedule = QtWidgets.QTableWidget(self.tabGridView)
        self.tableSchedule.setAlternatingRowColors(True)
        self.tableSchedule.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableSchedule.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableSchedule.setObjectName("tableSchedule")
        self.tableSchedule.setColumnCount(0)
        self.tableSchedule.setRowCount(0)
        self.tableSchedule.verticalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableSchedule)
        self.tabWidget.addTab(self.tabGridView, "")
        self.tabEmployeeView = QtWidgets.QWidget()
        self.tabEmployeeView.setObjectName("tabEmployeeView")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabEmployeeView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.employeeSelectLayout = QtWidgets.QHBoxLayout()
        self.employeeSelectLayout.setObjectName("employeeSelectLayout")
        self.lblEmployee = QtWidgets.QLabel(self.tabEmployeeView)
        self.lblEmployee.setObjectName("lblEmployee")
        self.employeeSelectLayout.addWidget(self.lblEmployee)
        self.cboEmployee = QtWidgets.QComboBox(self.tabEmployeeView)
        self.cboEmployee.setMinimumSize(QtCore.QSize(250, 0))
        self.cboEmployee.setObjectName("cboEmployee")
        self.employeeSelectLayout.addWidget(self.cboEmployee)
        self.btnViewEmployeeSchedule = QtWidgets.QPushButton(self.tabEmployeeView)
        self.btnViewEmployeeSchedule.setObjectName("btnViewEmployeeSchedule")
        self.employeeSelectLayout.addWidget(self.btnViewEmployeeSchedule)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.employeeSelectLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.employeeSelectLayout)
        self.tableEmployeeSchedule = QtWidgets.QTableWidget(self.tabEmployeeView)
        self.tableEmployeeSchedule.setAlternatingRowColors(True)
        self.tableEmployeeSchedule.setObjectName("tableEmployeeSchedule")
        self.tableEmployeeSchedule.setColumnCount(0)
        self.tableEmployeeSchedule.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableEmployeeSchedule)
        self.tabWidget.addTab(self.tabEmployeeView, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBoxLegend = QtWidgets.QGroupBox(ShiftSchedule)
        self.groupBoxLegend.setObjectName("groupBoxLegend")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxLegend)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblMorning = QtWidgets.QLabel(self.groupBoxLegend)
        self.lblMorning.setStyleSheet("color: #27ae60; font-weight: bold;")
        self.lblMorning.setObjectName("lblMorning")
        self.horizontalLayout.addWidget(self.lblMorning)
        self.lblAfternoon = QtWidgets.QLabel(self.groupBoxLegend)
        self.lblAfternoon.setStyleSheet("color: #f39c12; font-weight: bold;")
        self.lblAfternoon.setObjectName("lblAfternoon")
        self.horizontalLayout.addWidget(self.lblAfternoon)
        self.lblEvening = QtWidgets.QLabel(self.groupBoxLegend)
        self.lblEvening.setStyleSheet("color: #e74c3c; font-weight: bold;")
        self.lblEvening.setObjectName("lblEvening")
        self.horizontalLayout.addWidget(self.lblEvening)
        self.lblOff = QtWidgets.QLabel(self.groupBoxLegend)
        self.lblOff.setStyleSheet("color: #95a5a6; font-weight: bold;")
        self.lblOff.setObjectName("lblOff")
        self.horizontalLayout.addWidget(self.lblOff)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBoxLegend)

        self.retranslateUi(ShiftSchedule)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, ShiftSchedule):
        _translate = QtCore.QCoreApplication.translate
        ShiftSchedule.setWindowTitle(_translate("ShiftSchedule", "Phân ca làm việc"))
        self.lblTitle.setText(_translate("ShiftSchedule", "📅 PHÂN CA LÀM VIỆC"))
        self.lblMonth.setText(_translate("ShiftSchedule", "Chọn tháng:"))
        self.dateMonth.setDisplayFormat(_translate("ShiftSchedule", "MM/yyyy"))
        self.btnLoadSchedule.setText(_translate("ShiftSchedule", "📅 Tải lịch"))
        self.btnCopyWeek.setText(_translate("ShiftSchedule", "📋 Copy tuần"))
        self.btnSaveSchedule.setText(_translate("ShiftSchedule", "💾 Lưu lịch"))
        self.btnClearSchedule.setText(_translate("ShiftSchedule", "🗑️ Xóa lịch"))
        self.btnExportSchedule.setText(_translate("ShiftSchedule", "📊 Xuất Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGridView), _translate("ShiftSchedule", "📊 Lịch phân ca"))
        self.lblEmployee.setText(_translate("ShiftSchedule", "Chọn nhân viên:"))
        self.btnViewEmployeeSchedule.setText(_translate("ShiftSchedule", "👁️ Xem lịch"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEmployeeView), _translate("ShiftSchedule", "👨‍💼 Lịch theo nhân viên"))
        self.groupBoxLegend.setTitle(_translate("ShiftSchedule", "Chú thích"))
        self.lblMorning.setText(_translate("ShiftSchedule", "🟢 Ca sáng (08:00 - 12:00)"))
        self.lblAfternoon.setText(_translate("ShiftSchedule", "🟡 Ca chiều (13:00 - 17:00)"))
        self.lblEvening.setText(_translate("ShiftSchedule", "🔴 Ca tối (18:00 - 22:00)"))
        self.lblOff.setText(_translate("ShiftSchedule", "⚪ Nghỉ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShiftSchedule = QtWidgets.QWidget()
    ui = Ui_ShiftSchedule()
    ui.setupUi(ShiftSchedule)
    ShiftSchedule.show()
    sys.exit(app.exec_())
