# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MINH\OneDrive\문서\GitHub\quanlydo-giadung\quan-ly-dai-ly-kinh-doanh-do-gia-dung-main\ui\SupplierManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SupplierManagement(object):
    def setupUi(self, SupplierManagement):
        SupplierManagement.setObjectName("SupplierManagement")
        SupplierManagement.resize(1400, 950)
        SupplierManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 10px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        min-width: 120px;\n"
"        min-height: 40px;\n"
"    }\n"
"    QPushButton#btnAdd {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnAdd:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnEdit {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnEdit:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnDelete {\n"
"        background-color: #e74c3c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnDelete:hover {\n"
"        background-color: #c0392b;\n"
"    }\n"
"    QPushButton#btnSave {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnClear {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch:hover {\n"
"        background-color: #8e44ad;\n"
"    }\n"
"    QPushButton#btnImport {\n"
"        background-color: #1abc9c;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnExport {\n"
"        background-color: #e67e22;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QTextEdit {\n"
"        padding: 12px 16px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 16px;\n"
"        min-height: 35px;\n"
"    }\n"
"    QLineEdit:focus, QComboBox:focus, QTextEdit:focus {\n"
"        border-color: #3498db;\n"
"        border: 2px solid #3498db;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 26px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(SupplierManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(SupplierManagement)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxSearch = QtWidgets.QGroupBox(SupplierManagement)
        self.groupBoxSearch.setObjectName("groupBoxSearch")
        self.searchLayout = QtWidgets.QHBoxLayout(self.groupBoxSearch)
        self.searchLayout.setObjectName("searchLayout")
        self.lblSearch = QtWidgets.QLabel(self.groupBoxSearch)
        self.lblSearch.setObjectName("lblSearch")
        self.searchLayout.addWidget(self.lblSearch)
        self.txtSearch = QtWidgets.QLineEdit(self.groupBoxSearch)
        self.txtSearch.setMinimumSize(QtCore.QSize(350, 40))
        self.txtSearch.setObjectName("txtSearch")
        self.searchLayout.addWidget(self.txtSearch)
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnSearch.setMinimumSize(QtCore.QSize(120, 45))
        self.btnSearch.setObjectName("btnSearch")
        self.searchLayout.addWidget(self.btnSearch)
        self.lblStatus = QtWidgets.QLabel(self.groupBoxSearch)
        self.lblStatus.setObjectName("lblStatus")
        self.searchLayout.addWidget(self.lblStatus)
        self.cboStatus = QtWidgets.QComboBox(self.groupBoxSearch)
        self.cboStatus.setMinimumSize(QtCore.QSize(150, 40))
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.searchLayout.addWidget(self.cboStatus)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchLayout.addItem(spacerItem)
        self.btnAdd = QtWidgets.QPushButton(self.groupBoxSearch)
        self.btnAdd.setMinimumSize(QtCore.QSize(160, 50))
        self.btnAdd.setObjectName("btnAdd")
        self.searchLayout.addWidget(self.btnAdd)
        self.verticalLayout.addWidget(self.groupBoxSearch)
        self.groupBoxSupplierList = QtWidgets.QGroupBox(SupplierManagement)
        self.groupBoxSupplierList.setObjectName("groupBoxSupplierList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxSupplierList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableSuppliers = QtWidgets.QTableWidget(self.groupBoxSupplierList)
        self.tableSuppliers.setAlternatingRowColors(True)
        self.tableSuppliers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableSuppliers.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSuppliers.setMinimumSize(QtCore.QSize(0, 350))
        self.tableSuppliers.setObjectName("tableSuppliers")
        self.tableSuppliers.setColumnCount(8)
        self.tableSuppliers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSuppliers.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.tableSuppliers)
        self.lblTotalDebt = QtWidgets.QLabel(self.groupBoxSupplierList)
        self.lblTotalDebt.setObjectName("lblTotalDebt")
        self.lblTotalDebt.setMinimumSize(QtCore.QSize(0, 40))
        self.lblTotalDebt.setStyleSheet("font-weight: bold; color: #c0392b;")
        self.verticalLayout_2.addWidget(self.lblTotalDebt)
        self.tableButtonLayout = QtWidgets.QHBoxLayout()
        self.tableButtonLayout.setObjectName("tableButtonLayout")
        self.btnEdit = QtWidgets.QPushButton(self.groupBoxSupplierList)
        self.btnEdit.setMinimumSize(QtCore.QSize(100, 40))
        self.btnEdit.setObjectName("btnEdit")
        self.tableButtonLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.groupBoxSupplierList)
        self.btnDelete.setMinimumSize(QtCore.QSize(100, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.tableButtonLayout.addWidget(self.btnDelete)
        self.btnImport = QtWidgets.QPushButton(self.groupBoxSupplierList)
        self.btnImport.setMinimumSize(QtCore.QSize(120, 40))
        self.btnImport.setObjectName("btnImport")
        self.tableButtonLayout.addWidget(self.btnImport)
        self.btnExport = QtWidgets.QPushButton(self.groupBoxSupplierList)
        self.btnExport.setMinimumSize(QtCore.QSize(120, 40))
        self.btnExport.setObjectName("btnExport")
        self.tableButtonLayout.addWidget(self.btnExport)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tableButtonLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.tableButtonLayout)
        self.verticalLayout.addWidget(self.groupBoxSupplierList)
        self.groupBoxSupplierForm = QtWidgets.QGroupBox(SupplierManagement)
        self.groupBoxSupplierForm.setObjectName("groupBoxSupplierForm")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSupplierForm)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSupplierCode = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblSupplierCode.setObjectName("lblSupplierCode")
        self.gridLayout.addWidget(self.lblSupplierCode, 0, 0, 1, 1)
        self.txtSupplierCode = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtSupplierCode.setReadOnly(True)
        self.txtSupplierCode.setMinimumSize(QtCore.QSize(200, 40))
        self.txtSupplierCode.setObjectName("txtSupplierCode")
        self.gridLayout.addWidget(self.txtSupplierCode, 0, 1, 1, 1)
        self.lblSupplierName = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblSupplierName.setObjectName("lblSupplierName")
        self.gridLayout.addWidget(self.lblSupplierName, 0, 2, 1, 1)
        self.txtSupplierName = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtSupplierName.setMinimumSize(QtCore.QSize(300, 40))
        self.txtSupplierName.setObjectName("txtSupplierName")
        self.gridLayout.addWidget(self.txtSupplierName, 0, 3, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout.addWidget(self.lblPhone, 1, 0, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtPhone.setMinimumSize(QtCore.QSize(200, 40))
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout.addWidget(self.txtPhone, 1, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 1, 2, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtEmail.setMinimumSize(QtCore.QSize(300, 40))
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout.addWidget(self.txtEmail, 1, 3, 1, 1)
        self.lblAddress = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblAddress.setObjectName("lblAddress")
        self.gridLayout.addWidget(self.lblAddress, 2, 0, 1, 1)
        self.txtAddress = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtAddress.setMinimumSize(QtCore.QSize(0, 40))
        self.txtAddress.setObjectName("txtAddress")
        self.gridLayout.addWidget(self.txtAddress, 2, 1, 1, 3)
        self.lblTaxCode = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblTaxCode.setObjectName("lblTaxCode")
        self.gridLayout.addWidget(self.lblTaxCode, 3, 0, 1, 1)
        self.txtTaxCode = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtTaxCode.setMinimumSize(QtCore.QSize(200, 40))
        self.txtTaxCode.setObjectName("txtTaxCode")
        self.gridLayout.addWidget(self.txtTaxCode, 3, 1, 1, 1)
        self.lblContactPerson = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblContactPerson.setObjectName("lblContactPerson")
        self.gridLayout.addWidget(self.lblContactPerson, 3, 2, 1, 1)
        self.txtContactPerson = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtContactPerson.setMinimumSize(QtCore.QSize(300, 40))
        self.txtContactPerson.setObjectName("txtContactPerson")
        self.gridLayout.addWidget(self.txtContactPerson, 3, 3, 1, 1)
        self.lblBankAccount = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblBankAccount.setObjectName("lblBankAccount")
        self.gridLayout.addWidget(self.lblBankAccount, 4, 0, 1, 1)
        self.txtBankAccount = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtBankAccount.setMinimumSize(QtCore.QSize(200, 40))
        self.txtBankAccount.setObjectName("txtBankAccount")
        self.gridLayout.addWidget(self.txtBankAccount, 4, 1, 1, 1)
        self.lblBankName = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblBankName.setObjectName("lblBankName")
        self.gridLayout.addWidget(self.lblBankName, 4, 2, 1, 1)
        self.txtBankName = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtBankName.setMinimumSize(QtCore.QSize(300, 40))
        self.txtBankName.setObjectName("txtBankName")
        self.gridLayout.addWidget(self.txtBankName, 4, 3, 1, 1)
        self.lblDebt = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblDebt.setObjectName("lblDebt")
        self.gridLayout.addWidget(self.lblDebt, 5, 0, 1, 1)
        self.txtDebt = QtWidgets.QLineEdit(self.groupBoxSupplierForm)
        self.txtDebt.setMinimumSize(QtCore.QSize(200, 40))
        self.txtDebt.setObjectName("txtDebt")
        self.gridLayout.addWidget(self.txtDebt, 5, 1, 1, 1)
        self.lblSupplierStatus = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblSupplierStatus.setObjectName("lblSupplierStatus")
        self.gridLayout.addWidget(self.lblSupplierStatus, 5, 2, 1, 1)
        self.cboSupplierStatus = QtWidgets.QComboBox(self.groupBoxSupplierForm)
        self.cboSupplierStatus.setMinimumSize(QtCore.QSize(200, 40))
        self.cboSupplierStatus.setObjectName("cboSupplierStatus")
        self.cboSupplierStatus.addItem("")
        self.cboSupplierStatus.addItem("")
        self.cboSupplierStatus.addItem("")
        self.gridLayout.addWidget(self.cboSupplierStatus, 5, 3, 1, 1)
        self.lblNote = QtWidgets.QLabel(self.groupBoxSupplierForm)
        self.lblNote.setObjectName("lblNote")
        self.gridLayout.addWidget(self.lblNote, 6, 0, 1, 1)
        self.txtNote = QtWidgets.QTextEdit(self.groupBoxSupplierForm)
        self.txtNote.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txtNote.setMinimumSize(QtCore.QSize(0, 60))
        self.txtNote.setObjectName("txtNote")
        self.gridLayout.addWidget(self.txtNote, 6, 1, 1, 3)
        self.verticalLayout.addWidget(self.groupBoxSupplierForm)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.btnSave = QtWidgets.QPushButton(SupplierManagement)
        self.btnSave.setMinimumSize(QtCore.QSize(160, 50))
        self.btnSave.setObjectName("btnSave")
        self.buttonLayout.addWidget(self.btnSave)
        self.btnUpdate = QtWidgets.QPushButton(SupplierManagement)
        self.btnUpdate.setMinimumSize(QtCore.QSize(140, 50))
        self.btnUpdate.setObjectName("btnUpdate")
        self.buttonLayout.addWidget(self.btnUpdate)
        self.btnClear = QtWidgets.QPushButton(SupplierManagement)
        self.btnClear.setMinimumSize(QtCore.QSize(140, 50))
        self.btnClear.setObjectName("btnClear")
        self.buttonLayout.addWidget(self.btnClear)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(SupplierManagement)

    def retranslateUi(self, SupplierManagement):
        _translate = QtCore.QCoreApplication.translate
        SupplierManagement.setWindowTitle(_translate("SupplierManagement", "Quản lý nhà cung cấp"))
        self.lblTitle.setText(_translate("SupplierManagement", "🏭 QUẢN LÝ NHÀ CUNG CẤP"))
        self.groupBoxSearch.setTitle(_translate("SupplierManagement", "🔍 Tìm kiếm & Bộ lọc"))
        self.lblSearch.setText(_translate("SupplierManagement", "Tìm kiếm:"))
        self.txtSearch.setPlaceholderText(_translate("SupplierManagement", "Tìm theo tên, mã, số điện thoại, email..."))
        self.btnSearch.setText(_translate("SupplierManagement", "🔍 Tìm kiếm"))
        self.lblStatus.setText(_translate("SupplierManagement", "Trạng thái:"))
        self.cboStatus.setItemText(0, _translate("SupplierManagement", "Tất cả"))
        self.cboStatus.setItemText(1, _translate("SupplierManagement", "Đang hợp tác"))
        self.cboStatus.setItemText(2, _translate("SupplierManagement", "Tạm ngưng"))
        self.cboStatus.setItemText(3, _translate("SupplierManagement", "Ngừng hợp tác"))
        self.btnAdd.setText(_translate("SupplierManagement", "➕ Thêm nhà cung cấp"))
        self.groupBoxSupplierList.setTitle(_translate("SupplierManagement", "📋 Danh sách nhà cung cấp"))
        item = self.tableSuppliers.horizontalHeaderItem(0)
        item.setText(_translate("SupplierManagement", "Mã NCC"))
        item = self.tableSuppliers.horizontalHeaderItem(1)
        item.setText(_translate("SupplierManagement", "Tên nhà cung cấp"))
        item = self.tableSuppliers.horizontalHeaderItem(2)
        item.setText(_translate("SupplierManagement", "Số điện thoại"))
        item = self.tableSuppliers.horizontalHeaderItem(3)
        item.setText(_translate("SupplierManagement", "Email"))
        item = self.tableSuppliers.horizontalHeaderItem(4)
        item.setText(_translate("SupplierManagement", "Địa chỉ"))
        item = self.tableSuppliers.horizontalHeaderItem(5)
        item.setText(_translate("SupplierManagement", "Mã số thuế"))
        item = self.tableSuppliers.horizontalHeaderItem(6)
        item.setText(_translate("SupplierManagement", "Công nợ"))
        item = self.tableSuppliers.horizontalHeaderItem(7)
        item.setText(_translate("SupplierManagement", "Trạng thái"))
        self.lblTotalDebt.setText(_translate("SupplierManagement", "Tổng nợ hiện tại: 0 VNĐ"))
        self.btnEdit.setText(_translate("SupplierManagement", "✏️ Sửa"))
        self.btnDelete.setText(_translate("SupplierManagement", "🗑️ Xóa"))
        self.btnImport.setText(_translate("SupplierManagement", "📥 Nhập Excel"))
        self.btnExport.setText(_translate("SupplierManagement", "📤 Xuất Excel"))
        self.groupBoxSupplierForm.setTitle(_translate("SupplierManagement", "📝 Thông tin nhà cung cấp"))
        self.lblSupplierCode.setText(_translate("SupplierManagement", "Mã NCC:"))
        self.txtSupplierCode.setPlaceholderText(_translate("SupplierManagement", "Tự động sinh"))
        self.lblSupplierName.setText(_translate("SupplierManagement", "Tên nhà cung cấp:"))
        self.txtSupplierName.setPlaceholderText(_translate("SupplierManagement", "Nhập tên nhà cung cấp"))
        self.lblPhone.setText(_translate("SupplierManagement", "Số điện thoại:"))
        self.txtPhone.setPlaceholderText(_translate("SupplierManagement", "Nhập số điện thoại"))
        self.lblEmail.setText(_translate("SupplierManagement", "Email:"))
        self.txtEmail.setPlaceholderText(_translate("SupplierManagement", "Nhập địa chỉ email"))
        self.lblAddress.setText(_translate("SupplierManagement", "Địa chỉ:"))
        self.txtAddress.setPlaceholderText(_translate("SupplierManagement", "Nhập địa chỉ đầy đủ"))
        self.lblTaxCode.setText(_translate("SupplierManagement", "Mã số thuế:"))
        self.txtTaxCode.setPlaceholderText(_translate("SupplierManagement", "Nhập mã số thuế"))
        self.lblContactPerson.setText(_translate("SupplierManagement", "Người liên hệ:"))
        self.txtContactPerson.setPlaceholderText(_translate("SupplierManagement", "Nhập tên người liên hệ"))
        self.lblBankAccount.setText(_translate("SupplierManagement", "Số tài khoản:"))
        self.txtBankAccount.setPlaceholderText(_translate("SupplierManagement", "Số tài khoản ngân hàng"))
        self.lblBankName.setText(_translate("SupplierManagement", "Ngân hàng:"))
        self.txtBankName.setPlaceholderText(_translate("SupplierManagement", "Tên ngân hàng"))
        self.lblDebt.setText(_translate("SupplierManagement", "Công nợ:"))
        self.txtDebt.setPlaceholderText(_translate("SupplierManagement", "Số tiền công nợ"))
        self.lblSupplierStatus.setText(_translate("SupplierManagement", "Trạng thái:"))
        self.cboSupplierStatus.setItemText(0, _translate("SupplierManagement", "Đang hợp tác"))
        self.cboSupplierStatus.setItemText(1, _translate("SupplierManagement", "Tạm ngưng"))
        self.cboSupplierStatus.setItemText(2, _translate("SupplierManagement", "Ngừng hợp tác"))
        self.lblNote.setText(_translate("SupplierManagement", "Ghi chú:"))
        self.txtNote.setPlaceholderText(_translate("SupplierManagement", "Ghi chú thêm về nhà cung cấp..."))
        self.btnSave.setText(_translate("SupplierManagement", "💾 Lưu nhà cung cấp"))
        self.btnUpdate.setText(_translate("SupplierManagement", "🔄 Cập nhật"))
        self.btnClear.setText(_translate("SupplierManagement", "🔄 Xóa form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SupplierManagement = QtWidgets.QWidget()
    ui = Ui_SupplierManagement()
    ui.setupUi(SupplierManagement)
    SupplierManagement.show()
    sys.exit(app.exec_())
