# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MINH\OneDrive\문서\GitHub\quanlydo-giadung\quan-ly-dai-ly-kinh-doanh-do-gia-dung-main\ui\WarrantyManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WarrantyManagement(object):
    def setupUi(self, WarrantyManagement):
        WarrantyManagement.setObjectName("WarrantyManagement")
        WarrantyManagement.resize(1400, 900)
        WarrantyManagement.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f0f2f5;\n"
"    }\n"
"    QGroupBox {\n"
"        font-weight: bold;\n"
"        border: 2px solid #e1e8ed;\n"
"        border-radius: 12px;\n"
"        margin-top: 12px;\n"
"        padding-top: 12px;\n"
"        background-color: white;\n"
"    }\n"
"    QGroupBox::title {\n"
"        subcontrol-origin: margin;\n"
"        left: 15px;\n"
"        padding: 0 8px 0 8px;\n"
"        color: #2c3e50;\n"
"        font-size: 16px;\n"
"    }\n"
"    QTableWidget {\n"
"        background-color: white;\n"
"        alternate-background-color: #f9f9f9;\n"
"        gridline-color: #e0e0e0;\n"
"        selection-background-color: #3498db;\n"
"        selection-color: white;\n"
"        border-radius: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"    QHeaderView::section {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"        padding: 12px;\n"
"        font-weight: bold;\n"
"        font-size: 14px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton {\n"
"        border-radius: 8px;\n"
"        padding: 10px 24px;\n"
"        font-weight: bold;\n"
"        font-size: 16px;\n"
"        min-width: 120px;\n"
"        min-height: 40px;\n"
"    }\n"
"    QPushButton#btnRegister {\n"
"        background-color: #27ae60;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnRegister:hover {\n"
"        background-color: #2ecc71;\n"
"    }\n"
"    QPushButton#btnRepair {\n"
"        background-color: #f39c12;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnRepair:hover {\n"
"        background-color: #e67e22;\n"
"    }\n"
"    QPushButton#btnComplete {\n"
"        background-color: #3498db;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnComplete:hover {\n"
"        background-color: #2980b9;\n"
"    }\n"
"    QPushButton#btnSearch {\n"
"        background-color: #9b59b6;\n"
"        color: white;\n"
"    }\n"
"    QPushButton#btnSearch:hover {\n"
"        background-color: #8e44ad;\n"
"    }\n"
"    QPushButton#btnPrint {\n"
"        background-color: #1abc9c;\n"
"        color: white;\n"
"    }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit {\n"
"        padding: 12px 16px;\n"
"        border: 1px solid #dcdfe6;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"        font-size: 16px;\n"
"        min-height: 35px;\n"
"    }\n"
"    QLabel {\n"
"        color: #2c3e50;\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        font-size: 26px;\n"
"        font-weight: bold;\n"
"        color: #2c3e50;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 1px solid #ddd;\n"
"        border-radius: 8px;\n"
"        background-color: white;\n"
"    }\n"
"    QTabBar::tab {\n"
"        padding: 12px 24px;\n"
"        font-size: 15px;\n"
"        font-weight: bold;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(WarrantyManagement)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(WarrantyManagement)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.groupBoxFilter = QtWidgets.QGroupBox(WarrantyManagement)
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.lblWarrantyCode = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblWarrantyCode.setObjectName("lblWarrantyCode")
        self.gridLayout.addWidget(self.lblWarrantyCode, 0, 0, 1, 1)
        self.txtWarrantyCode = QtWidgets.QLineEdit(self.groupBoxFilter)
        self.txtWarrantyCode.setObjectName("txtWarrantyCode")
        self.gridLayout.addWidget(self.txtWarrantyCode, 0, 1, 1, 1)
        self.lblCustomer = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblCustomer.setObjectName("lblCustomer")
        self.gridLayout.addWidget(self.lblCustomer, 0, 2, 1, 1)
        self.txtCustomer = QtWidgets.QLineEdit(self.groupBoxFilter)
        self.txtCustomer.setObjectName("txtCustomer")
        self.gridLayout.addWidget(self.txtCustomer, 0, 3, 1, 1)
        self.lblStatus = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblStatus.setObjectName("lblStatus")
        self.gridLayout.addWidget(self.lblStatus, 1, 0, 1, 1)
        self.cboStatus = QtWidgets.QComboBox(self.groupBoxFilter)
        self.cboStatus.setObjectName("cboStatus")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.cboStatus.addItem("")
        self.gridLayout.addWidget(self.cboStatus, 1, 1, 1, 1)
        self.lblDateRange = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblDateRange.setObjectName("lblDateRange")
        self.gridLayout.addWidget(self.lblDateRange, 1, 2, 1, 1)
        self.dateLayout = QtWidgets.QHBoxLayout()
        self.dateLayout.setObjectName("dateLayout")
        self.dateFrom = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateFrom.setCalendarPopup(True)
        self.dateFrom.setObjectName("dateFrom")
        self.dateLayout.addWidget(self.dateFrom)
        self.lblTo = QtWidgets.QLabel(self.groupBoxFilter)
        self.lblTo.setObjectName("lblTo")
        self.dateLayout.addWidget(self.lblTo)
        self.dateTo = QtWidgets.QDateEdit(self.groupBoxFilter)
        self.dateTo.setCalendarPopup(True)
        self.dateTo.setObjectName("dateTo")
        self.dateLayout.addWidget(self.dateTo)
        self.gridLayout.addLayout(self.dateLayout, 1, 3, 1, 1)
        self.buttonFilterLayout = QtWidgets.QHBoxLayout()
        self.buttonFilterLayout.setObjectName("buttonFilterLayout")
        self.btnSearch = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnSearch.setObjectName("btnSearch")
        self.buttonFilterLayout.addWidget(self.btnSearch)
        self.btnReset = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnReset.setObjectName("btnReset")
        self.buttonFilterLayout.addWidget(self.btnReset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonFilterLayout.addItem(spacerItem)
        self.btnRegister = QtWidgets.QPushButton(self.groupBoxFilter)
        self.btnRegister.setObjectName("btnRegister")
        self.buttonFilterLayout.addWidget(self.btnRegister)
        self.gridLayout.addLayout(self.buttonFilterLayout, 2, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBoxFilter)
        self.groupBoxWarrantyList = QtWidgets.QGroupBox(WarrantyManagement)
        self.groupBoxWarrantyList.setObjectName("groupBoxWarrantyList")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxWarrantyList)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWarranties = QtWidgets.QTableWidget(self.groupBoxWarrantyList)
        self.tableWarranties.setAlternatingRowColors(True)
        self.tableWarranties.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWarranties.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWarranties.setMinimumSize(QtCore.QSize(0, 300))
        self.tableWarranties.setObjectName("tableWarranties")
        self.tableWarranties.setColumnCount(10)
        self.tableWarranties.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWarranties.setHorizontalHeaderItem(9, item)
        self.verticalLayout_2.addWidget(self.tableWarranties)
        self.verticalLayout.addWidget(self.groupBoxWarrantyList)
        self.groupBoxWarrantyForm = QtWidgets.QGroupBox(WarrantyManagement)
        self.groupBoxWarrantyForm.setObjectName("groupBoxWarrantyForm")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxWarrantyForm)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblProduct = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblProduct.setObjectName("lblProduct")
        self.gridLayout_2.addWidget(self.lblProduct, 0, 0, 1, 1)
        self.cboProduct = QtWidgets.QComboBox(self.groupBoxWarrantyForm)
        self.cboProduct.setMinimumSize(QtCore.QSize(250, 35))
        self.cboProduct.setObjectName("cboProduct")
        self.cboProduct.addItem("")
        self.cboProduct.addItem("")
        self.cboProduct.addItem("")
        self.gridLayout_2.addWidget(self.cboProduct, 0, 1, 1, 1)
        self.lblSerial = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblSerial.setObjectName("lblSerial")
        self.gridLayout_2.addWidget(self.lblSerial, 0, 2, 1, 1)
        self.txtSerial = QtWidgets.QLineEdit(self.groupBoxWarrantyForm)
        self.txtSerial.setObjectName("txtSerial")
        self.gridLayout_2.addWidget(self.txtSerial, 0, 3, 1, 1)
        self.lblCustomerName = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.gridLayout_2.addWidget(self.lblCustomerName, 1, 0, 1, 1)
        self.txtCustomerName = QtWidgets.QLineEdit(self.groupBoxWarrantyForm)
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.gridLayout_2.addWidget(self.txtCustomerName, 1, 1, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout_2.addWidget(self.lblPhone, 1, 2, 1, 1)
        self.txtPhone = QtWidgets.QLineEdit(self.groupBoxWarrantyForm)
        self.txtPhone.setObjectName("txtPhone")
        self.gridLayout_2.addWidget(self.txtPhone, 1, 3, 1, 1)
        self.lblPurchaseDate = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblPurchaseDate.setObjectName("lblPurchaseDate")
        self.gridLayout_2.addWidget(self.lblPurchaseDate, 2, 0, 1, 1)
        self.datePurchase = QtWidgets.QDateEdit(self.groupBoxWarrantyForm)
        self.datePurchase.setCalendarPopup(True)
        self.datePurchase.setObjectName("datePurchase")
        self.gridLayout_2.addWidget(self.datePurchase, 2, 1, 1, 1)
        self.lblExpiryDate = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblExpiryDate.setObjectName("lblExpiryDate")
        self.gridLayout_2.addWidget(self.lblExpiryDate, 2, 2, 1, 1)
        self.dateExpiry = QtWidgets.QDateEdit(self.groupBoxWarrantyForm)
        self.dateExpiry.setCalendarPopup(True)
        self.dateExpiry.setObjectName("dateExpiry")
        self.gridLayout_2.addWidget(self.dateExpiry, 2, 3, 1, 1)
        self.lblError = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblError.setObjectName("lblError")
        self.gridLayout_2.addWidget(self.lblError, 3, 0, 1, 1)
        self.txtError = QtWidgets.QTextEdit(self.groupBoxWarrantyForm)
        self.txtError.setMaximumSize(QtCore.QSize(16777215, 80))
        self.txtError.setObjectName("txtError")
        self.gridLayout_2.addWidget(self.txtError, 3, 1, 1, 3)
        self.lblNote = QtWidgets.QLabel(self.groupBoxWarrantyForm)
        self.lblNote.setObjectName("lblNote")
        self.gridLayout_2.addWidget(self.lblNote, 4, 0, 1, 1)
        self.txtNote = QtWidgets.QTextEdit(self.groupBoxWarrantyForm)
        self.txtNote.setMaximumSize(QtCore.QSize(16777215, 60))
        self.txtNote.setObjectName("txtNote")
        self.gridLayout_2.addWidget(self.txtNote, 4, 1, 1, 3)
        self.formButtonLayout = QtWidgets.QHBoxLayout()
        self.formButtonLayout.setObjectName("formButtonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formButtonLayout.addItem(spacerItem1)
        self.btnSave = QtWidgets.QPushButton(self.groupBoxWarrantyForm)
        self.btnSave.setObjectName("btnSave")
        self.formButtonLayout.addWidget(self.btnSave)
        self.btnRepair = QtWidgets.QPushButton(self.groupBoxWarrantyForm)
        self.btnRepair.setObjectName("btnRepair")
        self.formButtonLayout.addWidget(self.btnRepair)
        self.btnComplete = QtWidgets.QPushButton(self.groupBoxWarrantyForm)
        self.btnComplete.setObjectName("btnComplete")
        self.formButtonLayout.addWidget(self.btnComplete)
        self.btnPrint = QtWidgets.QPushButton(self.groupBoxWarrantyForm)
        self.btnPrint.setObjectName("btnPrint")
        self.formButtonLayout.addWidget(self.btnPrint)
        self.btnClear = QtWidgets.QPushButton(self.groupBoxWarrantyForm)
        self.btnClear.setObjectName("btnClear")
        self.formButtonLayout.addWidget(self.btnClear)
        self.gridLayout_2.addLayout(self.formButtonLayout, 5, 0, 1, 4)
        self.verticalLayout.addWidget(self.groupBoxWarrantyForm)

        self.retranslateUi(WarrantyManagement)

    def retranslateUi(self, WarrantyManagement):
        _translate = QtCore.QCoreApplication.translate
        WarrantyManagement.setWindowTitle(_translate("WarrantyManagement", "Quản lý bảo hành"))
        self.lblTitle.setText(_translate("WarrantyManagement", "🔧 QUẢN LÝ BẢO HÀNH"))
        self.groupBoxFilter.setTitle(_translate("WarrantyManagement", "🔍 Tìm kiếm & Bộ lọc"))
        self.lblWarrantyCode.setText(_translate("WarrantyManagement", "Mã bảo hành:"))
        self.txtWarrantyCode.setPlaceholderText(_translate("WarrantyManagement", "Nhập mã bảo hành"))
        self.lblCustomer.setText(_translate("WarrantyManagement", "Khách hàng:"))
        self.txtCustomer.setPlaceholderText(_translate("WarrantyManagement", "Tên hoặc SĐT khách hàng"))
        self.lblStatus.setText(_translate("WarrantyManagement", "Trạng thái:"))
        self.cboStatus.setItemText(0, _translate("WarrantyManagement", "Tất cả"))
        self.cboStatus.setItemText(1, _translate("WarrantyManagement", "Đang bảo hành"))
        self.cboStatus.setItemText(2, _translate("WarrantyManagement", "Đã sửa xong"))
        self.cboStatus.setItemText(3, _translate("WarrantyManagement", "Đã trả hàng"))
        self.cboStatus.setItemText(4, _translate("WarrantyManagement", "Hết bảo hành"))
        self.lblDateRange.setText(_translate("WarrantyManagement", "Ngày tiếp nhận:"))
        self.dateFrom.setDisplayFormat(_translate("WarrantyManagement", "dd/MM/yyyy"))
        self.lblTo.setText(_translate("WarrantyManagement", "→"))
        self.dateTo.setDisplayFormat(_translate("WarrantyManagement", "dd/MM/yyyy"))
        self.btnSearch.setText(_translate("WarrantyManagement", "🔍 Tìm kiếm"))
        self.btnReset.setText(_translate("WarrantyManagement", "🔄 Xóa bộ lọc"))
        self.btnRegister.setText(_translate("WarrantyManagement", "➕ Đăng ký bảo hành"))
        self.groupBoxWarrantyList.setTitle(_translate("WarrantyManagement", "📋 Danh sách phiếu bảo hành"))
        item = self.tableWarranties.horizontalHeaderItem(0)
        item.setText(_translate("WarrantyManagement", "Mã BH"))
        item = self.tableWarranties.horizontalHeaderItem(1)
        item.setText(_translate("WarrantyManagement", "Ngày tiếp nhận"))
        item = self.tableWarranties.horizontalHeaderItem(2)
        item.setText(_translate("WarrantyManagement", "Sản phẩm"))
        item = self.tableWarranties.horizontalHeaderItem(3)
        item.setText(_translate("WarrantyManagement", "Serial/Mã SP"))
        item = self.tableWarranties.horizontalHeaderItem(4)
        item.setText(_translate("WarrantyManagement", "Khách hàng"))
        item = self.tableWarranties.horizontalHeaderItem(5)
        item.setText(_translate("WarrantyManagement", "SĐT"))
        item = self.tableWarranties.horizontalHeaderItem(6)
        item.setText(_translate("WarrantyManagement", "Mã hóa đơn"))
        item = self.tableWarranties.horizontalHeaderItem(7)
        item.setText(_translate("WarrantyManagement", "Lỗi"))
        item = self.tableWarranties.horizontalHeaderItem(8)
        item.setText(_translate("WarrantyManagement", "Trạng thái"))
        item = self.tableWarranties.horizontalHeaderItem(9)
        item.setText(_translate("WarrantyManagement", "Thao tác"))
        self.groupBoxWarrantyForm.setTitle(_translate("WarrantyManagement", "📝 Thông tin bảo hành"))
        self.lblProduct.setText(_translate("WarrantyManagement", "Sản phẩm:"))
        self.cboProduct.setItemText(0, _translate("WarrantyManagement", "Tủ lạnh Samsung"))
        self.cboProduct.setItemText(1, _translate("WarrantyManagement", "Máy giặt Panasonic"))
        self.cboProduct.setItemText(2, _translate("WarrantyManagement", "TV Sony"))
        self.lblSerial.setText(_translate("WarrantyManagement", "Serial/Mã SP:"))
        self.txtSerial.setPlaceholderText(_translate("WarrantyManagement", "Nhập serial hoặc mã sản phẩm"))
        self.lblCustomerName.setText(_translate("WarrantyManagement", "Tên khách hàng:"))
        self.txtCustomerName.setPlaceholderText(_translate("WarrantyManagement", "Nhập tên khách hàng"))
        self.lblPhone.setText(_translate("WarrantyManagement", "Số điện thoại:"))
        self.txtPhone.setPlaceholderText(_translate("WarrantyManagement", "Nhập số điện thoại"))
        self.lblPurchaseDate.setText(_translate("WarrantyManagement", "Ngày mua:"))
        self.datePurchase.setDisplayFormat(_translate("WarrantyManagement", "dd/MM/yyyy"))
        self.lblExpiryDate.setText(_translate("WarrantyManagement", "Hết hạn BH:"))
        self.dateExpiry.setDisplayFormat(_translate("WarrantyManagement", "dd/MM/yyyy"))
        self.lblError.setText(_translate("WarrantyManagement", "Lỗi sản phẩm:"))
        self.txtError.setPlaceholderText(_translate("WarrantyManagement", "Mô tả lỗi sản phẩm..."))
        self.lblNote.setText(_translate("WarrantyManagement", "Ghi chú:"))
        self.txtNote.setPlaceholderText(_translate("WarrantyManagement", "Ghi chú thêm (nếu có)..."))
        self.btnSave.setText(_translate("WarrantyManagement", "💾 Lưu phiếu"))
        self.btnRepair.setText(_translate("WarrantyManagement", "🔧 Cập nhật sửa chữa"))
        self.btnComplete.setText(_translate("WarrantyManagement", "✅ Hoàn thành"))
        self.btnPrint.setText(_translate("WarrantyManagement", "🖨️ In phiếu"))
        self.btnClear.setText(_translate("WarrantyManagement", "🔄 Xóa form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WarrantyManagement = QtWidgets.QWidget()
    ui = Ui_WarrantyManagement()
    ui.setupUi(WarrantyManagement)
    WarrantyManagement.show()
    sys.exit(app.exec_())
