#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import re

ui_folder = 'ui'
py_files = [f for f in os.listdir(ui_folder) if f.endswith('.py')]

print(f"🔍 Tìm thấy {len(py_files)} file .py\n")

for py_file in py_files:
    filepath = os.path.join(ui_folder, py_file)
    print(f"🔄 Đang convert: {py_file}")
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Thay đổi import PyQt6 sang PyQt5
    content = content.replace('from PyQt6 import', 'from PyQt5 import')
    content = content.replace('PyQt6.QtCore', 'PyQt5.QtCore')
    content = content.replace('PyQt6.QtGui', 'PyQt5.QtGui')
    content = content.replace('PyQt6.QtWidgets', 'PyQt5.QtWidgets')
    
    # Thay đổi header comment
    content = content.replace('PyQt6 UI code generator', 'PyQt5 UI code generator')
    content = content.replace('run again.  Do not edit this file', 'run again.  Do not edit this file')
    content = content.replace('Warning: Any manual changes', 'WARNING: Any manual changes')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✅ Đã convert: {py_file}\n")

print("🎉 Hoàn tất convert PyQt6 → PyQt5!")
